### ISSUE TITLE
Add MP4 input support

### ISSUE THREAD

**Issue by kristofferR** [sandreas/m4b-tool#10]
I would really appreciate if you could add MP4 input support. I often convert video products into audio books, so I can listen to them on the go.

This should be really simple to add, as M4B-tool already works if you just rename the input .mp4 files to .aac .

**Comment by sandreas** [comment]
mp4 is supported via --include-extensions=mp4 parameter. To provide multiple extensions, you could use a comma separated list (--include-extensions=mp4,mp3,m4b,m4a,ogg,flac). However, beta5 now includes improved support for extensions beeing case-insensitive, mp4 is in the default list.
