### ISSUE TITLE
Official Docker Hub or Github Container Registry images?

### ISSUE THREAD

**Issue by burkasaurusrex** [sandreas/m4b-tool#102]
Given the heavy build here, I think it would be really beneficial to have an official image on Docker Hub or GHCR? I know Docker is free for public projects and is easy to set up so it rebuilds with every commit.

**Comment by sandreas** [comment]
Hey,

thanks for reporting. This is indeed correct. I always wanted to do that, but in the last time i was pretty busy all the time. Maybe in the next weeks i can provide an "official" image with an official `m4b-tool` account.

This would safe everyone a lot of time, even if docker-hub is now rate limited ;-)

Best
