### ISSUE TITLE
Remove "(1)" from chapter names

### ISSUE THREAD

**Issue by djdembeck** [sandreas/m4b-tool#104]
I am guessing the "(1)" is a placeholder for if/when there are sub-chapters, but when only single chapters are being used, it looks bad.

```
00:00:00.000 1 (1)
00:00:12.573 2 (1)
00:05:52.352 3 (1)
00:05:57.131 4 (1)
00:10:53.454 5 (1)
00:10:58.770 6 (1)
00:16:07.700 7 (1)
00:16:12.414 8 (1)
00:19:44.603 9 (1)
00:20:47.098 10 (1)
```

**Comment by sandreas** [comment]
Should be fixed (or at least improved behaviour) in the latest `pre-release` when using `--chapter-algo=grouping`. Feedback would be great.

**Comment by sandreas** [comment]
I'll assume this has been fixed with `--chapter-algo=grouping`, if not, feel free to reopen.
