### ISSUE TITLE
Add ability to set track number

### ISSUE THREAD

**Issue by djdembeck** [sandreas/m4b-tool#105]
Currently, when scanned into something like Plex, the resulting merged file has no track number, and just shows as track '0', which hurts my OCD a bit.

**Comment by sandreas** [comment]
Hey,

thanks for reporting. Which version of `m4b-tool` are you using?
Since you already reported another issue, I'll wait responding to that one until the version is clear. Just a hint: Chapter reindexing is broken in the latest pre-release and will be completely reworked.

Best,
sandreas

**Comment by djdembeck** [comment]
Hey there!

I have noticed this on both 0.4.2 and the 2020-10-11 pre-release (the latter of which I now use). I'm using the `meta` command on m4b files, and the `merge` command on mp3 files. The meta command retains embedded chapter information (without needing to analyze silence), and the merge on multiple files uses file names as chapter marks. So in that regard, everything is perfect :)

**Comment by sandreas** [comment]
I'm currently working on a complete rewrite of the chapter logic, which in my opinion will be MUCH better than the current one... I plan to provide an Option `--chapter-algo=...`, so that you are able to choose, what you like best and to be able to provide other mechanisms (`legacy` will be the default option for now)... this unfortunately will take a little while, because my time is very limited.

**Comment by sandreas** [comment]
Latest pre-release should contain the option `--chapter-algo=grouping`, which is a complete rewrite of the chapter indexing logic. Feedback would be great.

**Comment by sandreas** [comment]
Because there was no further feedback, I'll assume this has been fixed with the `--chapter-algo=grouping` parameter. If not, feel free to reopen.

**Comment by djdembeck** [comment]
Sorry for the extended delay in responding. This feature was not implemented (track number metadata), thus this should not be closed for chapter changes.
