### ISSUE TITLE
PHP Exception in twig

### ISSUE THREAD

**Issue by Brennanium** [sandreas/m4b-tool#108]
If I run m4b-tool split, it throws a PHP Exception after a few minutes.  In twig, "Unparenthesized `a ? b : c ? d : e` is not supported" was fixed in back in May 2019 in a PHP 7.4 compatibility update.

OS: macOS 11.1 Beta
Command: m4b-tool split --audio-format mp3 --audio-bitrate 63k --audio-channels 2 --audio-samplerate 22050 "book.m4b"
Error:

PHP Fatal error:  Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/vendor/twig/twig/src/Node/Node.php on line 43

Fatal error: Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/vendor/twig/twig/src/Node/Node.php on line 43
an error occured, that has not been caught:
Array
(
    [type] => 64
    [message] => Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)`
    [file] => phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/vendor/twig/twig/src/Node/Node.php
    [line] => 43
)

**Comment by Brennanium** [comment]
PHP Exception only occurs on release version, 0.4.2; I just tried it again using the latest pre-release version and it works fantastically!

**Comment by sandreas** [comment]
Thank you for researching this... can this bug be closed now?

**Comment by Brennanium** [comment]
I think so!
