### ISSUE TITLE
Error installing on mac

### ISSUE THREAD

**Issue by dorenava** [sandreas/m4b-tool#110]
Hello Andreas,

I would like to use your app, but I'm having an issue while installing it.
I went through the steps in [Recommended: High audio quality, sort tagging](https://github.com/sandreas/m4b-tool#recommended-high-audio-quality-sort-tagging) and during the step 

>$ brew install sandreas/tap/m4b-tool

I have the following error:

>==> Downloading https://github.com/sandreas/mp4v2/tarball/master
>==> Downloading from https://codeload.github.com/sandreas/mp4v2/legacy.tar.gz/master
>
>Error: SHA256 mismatch
>Expected: 7fdb74872b52aa21f284304962d30dc9b15cd06849295ae42ae867746bb5ff64
>  Actual: 3353b8289da1ddf84ea48d7e98ed8823d99548dbf8ada82dc3ef1c164bc81134
>    File: /Users/xxxxxxxxx/Library/Caches/Homebrew/downloads/ba4b9f24c9abc855b34ac70dc60f5eba7e94b3384170ca29d825de69ee0809b0--sandreas-mp4v2-Release-ThirdParty-MP4v2-4.1.0.0-11-gccea53c.tar.gz
>To retry an incomplete download, remove the file above

I tried to delete the file and restarted the process again, but I'm getting the same error..

Could you advice please what could be the reason?

> $ brew --version
>Homebrew 2.6.2
>Homebrew/homebrew-core (git revision d914a; last commit 2020-12-14)
>Homebrew/homebrew-cask (git revision f806f; last commit 2020-12-14)

Thanks in advance for your time!

**Comment by sandreas** [comment]
Hey there, it seems that there is a problem with the checksum regarding to a recent updated where i tried some things with the `purchaseDate`. I'll try to updated the hashes as soon as possible.

**Comment by dorenava** [comment]
Yep, confirm that, install finished w/o an error. Thanks for a quick fix!
