### ISSUE TITLE
Feature Request: Support for Overdrive Chapters (mp3, Tag with XML)

### ISSUE THREAD

**Issue by ink79** [sandreas/m4b-tool#114]
Overdrive Audiobooks are split into multiple part, each part has chapter embedded in them, right now im using inaudible to create chaptalized m4b file, is it possible to use those small chapter instead of part when creating m4b

**Comment by sandreas** [comment]
Try the latest pre-release. It should work with that.

**Comment by ink79** [comment]
m4b-tool latest-51-gc64182b

output file has the same part before, but got this error 

```
PHP Warning:  file_put_contents(): Filename cannot be empty in phar:///usr/local/bin/m4b-tool/src/library/Command/MergeCommand.php on line 226
an error occured, that has not been caught:
Array
(
    [type] => 2
    [message] => file_put_contents(): Filename cannot be empty
    [file] => phar:///usr/local/bin/m4b-tool/src/library/Command/MergeCommand.php
    [line] => 226
)
```

**Comment by sandreas** [comment]
Thanks for testing this. The last error is already reported and it has nothing to with the chapter problem - i already fixed it locally and will commit it in the next days. 
Could you go a bit more into detail with your problem? (short examples are enough)
- What files have you got with what chapters in it?
- What would you expect as output with what chapters?
- What do you get instead?

**Comment by ink79** [comment]
here is an example so the first mp3 file contain chapter tag like this 

`OverDrive MediaMarkers                   : <Markers><Marker><Name>Pretty Little Wife</Name><Time>0:00.000</Time></Marker><Marker><Name>Chapter 1</Name><Time>0:34.000</Time></Marker><Marker><Name>Chapter 2</Name><Time>3:24.000</Time></Marker><Marker><Name>Chapter 3</Name><Time>17:33.000</Time></Marker><Marker><Name>Chapter 4</Name><Time>34:32.000</Time></Marker><Marker><Name>Chapter 5</Name><Time>49:43.000</Time></Marker></Markers>`

i was hoping when i convert to m4b, the tool would use this Chapter Markers instead of use the file as chapter 1.

i have added one book so you can see for yourself https://dropmefiles.com/hNYVX

**Comment by Etothetaui** [comment]
I actually came to ask the same question. Running `ffprobe Elantris-Part01.mp3 ` gives the metadata including 
`<Markers><Marker><Name>Acknowledgements</Name><Time>0:00.000</Time></Marker><Marker><Name>Foreword</Name><Time>3:12.000</Time></Marker><Marker><Name>Prologue</Name><Time>10:45.000</Time></Marker><Marker><Name>Part 1 - Chapter 1</Name><Time>12:36.000</Time></Marker></Markers>`

However running merge creates an m4b with a chapter for each file, instead of a chapter for each timestamp in the OverDrive Media Markers tag.

I guess a work around would be to manually go through the metadata for the files and make a txt with the chapter times and then use the text file to chapterize using the chapters command

**Comment by Etothetaui** [comment]
Also is it possible to use this program to just convert the odm file to m4b directly instead of manually extracting the mp3s with overdrive's gui media program first?

**Comment by sandreas** [comment]
Thanks for providing the files... but please beware that sharing files with a copyright is not allowed (I'm not sure, if these are under a copyright - if so, please remove the link)

**Comment by Etothetaui** [comment]
Ok, well this is obviously not an ideal solution but it is the best I could do with my limited coding skills. Here is a badly written python script that will create a chapters.txt file with the correct time stamps based on the overdrive meta data. You will have to change the title from "Elantris" to whatever the names of your files are and the parts to however many parts overdrive gave you

`from mutagen.mp3 import MP3
from lxml import etree

title = 'Elantris'
parts = 27
totlength = 0.0
f = open(title+".chapters.txt", "w")

for i in range(parts):
	part = "{:02d}".format(i+1)
	
	file = MP3(title+'-Part'+part+'.mp3')
	chapters = etree.fromstring(file['TXXX:OverDrive MediaMarkers'][0])
	
	for chapter in chapters.getchildren():
		name = chapter[0].text

		time = chapter[1].text.split(":")
		time = totlength+float(time[0])*60+float(time[1])

		h = "{:02d}".format(int(time/3600))
		m = "{:02d}".format(int((time%3600)/60))
		s = "{:02d}".format(int(time%60))
		ms = "{:03d}".format(int((time%1)*1000))
		
		duration = h+":"+m+":"+s+"."+ms
		f.write(duration+"    "+name+"\n")

	totlength += file.info.length
		`

**Comment by ink79** [comment]
Thanks for the script, hopefully sandreas will add something like this to m4b tool or someone make the script better so it can work on multiple directory without manually adding book name & chapter number for each book

**Comment by Etothetaui** [comment]
I'm glad the script worked for you. Maybe you can figure out how to make it better

**Comment by ink79** [comment]
opened an request on fiverr, lets see if i can find someone to improve it

**Comment by sandreas** [comment]
Ahhh, now I understand what you would like to do... After analysing the files you provided, I can say the following:

- The mp3 files you provided do NOT contain embedded chapters via `ID3v2 Chapter Frame Addendum` (https://id3.org/id3v2-chapters-1.0)
- The Files contain a CUSTOM tag named `OverDrive MediaMarkers`, with a CUSTOM XML format, that contains Markers for the chapters (AFAIK this is not an official standard or RFC, but I have to research on this)

Here is an example:

```
ffprobe -hide_banner Pretty\ Little\ Wife-Part01.mp3 
[mp3 @ 0x7fa9ec009000].
[mp3 @ 0x7fa9ec009000] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from 'Pretty Little Wife-Part01.mp3':
  Metadata:
    artist          : Darby Kane
    copyright       : HarperAudio
    comment         : <p><strong>A Paperback Original</strong></p> <p><strong>Debut author Darby Kane thrills with this twisty domestic suspense novel that asks one central question: shouldn't a dead husband stay dead?<br/> <br/> </strong></p> <br/>Lila Ridgefield lives in an 
    title           : Pretty Little Wife - Part 1
    album           : Pretty Little Wife - A Novel
    genre           : Fiction/Suspense/Thriller
    publisher       : HarperCollins Publishers Inc.
    TIT3            : A Novel
    encoded_by      : OverDrive, Inc.
    OverDrive MediaMarkers: <Markers><Marker><Name>Pretty Little Wife</Name><Time>0:00.000</Time></Marker><Marker><Name>Chapter 1</Name><Time>0:34.000</Time></Marker><Marker><Name>Chapter 2</Name><Time>3:24.000</Time></Marker><Marker><Name>Chapter 3</Name><Time>17:33.000</Time></Mar
  Duration: 01:02:23.44, start: 0.000000, bitrate: 64 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 64 kb/s

```

As you see, `ffprobe` does not see this file as valid  (Warning: `Skipping 208 bytes of junk at 3100`). So it seems that either `ffprobe` does not yet support this kind of files or Overdrive is violating some standards.

Here is what I would suggest: 
- Changing this issue into a feature request "Support Overdrive Chapter Specification"
- Further investigation of how these files and tags can be supported
- Adding this feature to `m4b-tool` (should not take that long, IF the Overdrive format is reliable)

**Comment by ink79** [comment]
here you go...

`
from mutagen.mp3 import MP3
from lxml import etree
import os

directory = "overdrive"
for title in os.listdir(directory):    
    f = open(directory+"/"+title+"/"+"chapters.txt", "w")
    f.write("")
    f.close()
    
    f = open(directory+"/"+title+"/"+"chapters.txt", "a")
    
    total_parts=0
    totlength = 0.0
    for music_file in os.listdir(directory+"/"+title):
        if music_file.endswith(".mp3"):
            total_parts += 1
    for i in range(total_parts):
            part = "{:02d}".format(i+1)
            file = MP3(directory+"/"+title+"/"+title+'-Part'+part+'.mp3')
            chapters = etree.fromstring(file['TXXX:OverDrive MediaMarkers'][0])
            for chapter in chapters.getchildren():
                name = chapter[0].text
                time = chapter[1].text.split(":")
                time = totlength+float(time[0])*60+float(time[1])
                h = "{:02d}".format(int(time/3600))
                m = "{:02d}".format(int((time%3600)/60))
                s = "{:02d}".format(int(time%60))
                ms = "{:03d}".format(int((time%1)*1000))
                duration = h+":"+m+":"+s+"."+ms
                f.write(duration+"    "+name+"\n")
            totlength += file.info.length`

**Comment by ink79** [comment]
here you go

`

from mutagen.mp3 import MP3
from lxml import etree
import os

directory = "overdrive"
for title in os.listdir(directory):    
    f = open(directory+"/"+title+"/"+"chapters.txt", "w")
    f.write("")
    f.close()
    
    f = open(directory+"/"+title+"/"+"chapters.txt", "a")
    
    total_parts=0
    totlength = 0.0
    for music_file in os.listdir(directory+"/"+title):
        if music_file.endswith(".mp3"):
            total_parts += 1
    for i in range(total_parts):
            part = "{:02d}".format(i+1)
            file = MP3(directory+"/"+title+"/"+title+'-Part'+part+'.mp3')
            chapters = etree.fromstring(file['TXXX:OverDrive MediaMarkers'][0])
            for chapter in chapters.getchildren():
                name = chapter[0].text
                time = chapter[1].text.split(":")
                time = totlength+float(time[0])*60+float(time[1])
                h = "{:02d}".format(int(time/3600))
                m = "{:02d}".format(int((time%3600)/60))
                s = "{:02d}".format(int(time%60))
                ms = "{:03d}".format(int((time%1)*1000))
                duration = h+":"+m+":"+s+"."+ms
                f.write(duration+"    "+name+"\n")
            totlength += file.info.length

`

**Comment by sandreas** [comment]
So after a little experimenting session I published a new latest pre-release today, which should add basic support for Overdrive chapters. Important: This is experimental. I cannot verify, that the implementation works in every possible case, but with the provided files it did work.

Caveats:
- The length / chapter calculation is based on the original `mp3` files, which might result in a chapter position shift of a few ms to many seconds in the `m4b` file based on the correctness of length estimation for mp3 files
- The XML might be incomplete in some cases, which is not handled correctly and results in using file based chapters as before

Further feedback would be great.

**Comment by ink79** [comment]
I'm getting this error 

> ERROR       56817ms Call to undefined function M4bTool\Audio\Tag\simplexml_load_string()

**Comment by sandreas** [comment]
> I'm getting this error

Thanks for the feedback. You need to enable the xml module in `php.ini`. Depending on which operating system you use, you need to perform various steps.

- On Windows, it might be enough to change `;extension=php_xmlrpc.dll` to `extension=php_xmlrpc.dll` (remove the `;`)
- On Ubuntu-Linux `sudo apt-get install php-xml` will do the job
- On MacOS its more complex
- On Docker it should already work

But in the next release I will change all `simplexml_load_string` to `DOMDocument`, so this error will no longer happen. For now you unfortunately have to deal with it until the next pre-release.

**Comment by ink79** [comment]
im using the docker `m4b-tool latest-56-g2ac2631` also install `php-xml` same problem

**Comment by sandreas** [comment]
Mmh this is strange. Well, I reuploaded a version that uses `DOMDocument` now, so it might work. If not, I'll have to test this again tomorrow

**Comment by ink79** [comment]
thanks, i have installed the new one & its working perfectly.

**Comment by sandreas** [comment]
Thanks for providing such wonderful feedback. I'll close this for now, if you find a file set where this does not work, feel free to reopen the issue.

**Comment by ink79** [comment]
hi I was wondering is it possible to remove the narrator which overdrive put in Artist tag & use only the author name for the Artist tag

**Comment by sandreas** [comment]
Maybe... you could
- use `--artist="an artist"` if it is a single audio book
- `--batch-pattern...` with batch mode which overrides the tags by folder names if there are multiple audio books
- use an extra run of `mp4tags` to set the artist manually afterwards

Another useful option is `--equate=artist,composer,albumartist`, where you can use the same source tag for multiple destination tags...

But don't expect `m4b-tool` to sneak into your brain, find out, what you would like to do and then automagically (typo intended) to doing it... *This `m4b-tool` does not have Super Cow Powers* ;-)

**Comment by ink79** [comment]
is it possible to increase the character limit of --description[=DESCRIPTION] plex show only description from file not --longdesc[=LONGDESC]   or --comment[=COMMENT] & remove html tags like <br>,<I>,</i>,</strong><strong></p><p> etc

**Comment by sandreas** [comment]
> is it possible to increase the character limit of --description[=DESCRIPTION] 

Unfortunately not with `m4b-tool` - since iTunes is limited to 255 bytes (and I think the desc tag also is specificed like this), this is an automatic limit. If you would like to overcome this limit, you could try to use `mp4tags` or `ffmpeg` directly, but maybe this would make the file less compatible with other players / media managers.

> remove HTML tags from description

This is also not possible and has to be done before tagging. I try to prevent modifying strings in any way except length limits.

**Comment by RunTheGambit** [comment]
I am having an issue with the OverDrive MediaMarkers not creating chapters. I am using Docker on windows 10 with the most recent build. Is there an additional command I need to enter?

**Comment by sandreas** [comment]
> Is there an additional command I need to enter?

No, usually it should work without interaction. I'll have to investigate this, but without the files, it may be difficult. Are you using mp3 files?

**Comment by RunTheGambit** [comment]
Hi, thank you!
The Docker Image ID is 7f00e75a93ef
The m4b-tool git version is [06c897d]
Yes I am using mp3 files and working out of the C: drive. 
I verified that it did create a Chapters.txt file using each file as a chapter number:
```
00:00:00.000 1
01:17:23.683 2
02:22:19.585 3
03:36:21.629 4
04:40:54.020 5
05:53:13.115 6
07:10:15.430 7
08:23:04.174 8
09:21:38.191 9
10:15:32.515 10
11:12:50.359 11
12:03:35.113 12
12:58:08.360 13
14:06:35.096 14
15:19:58.034 15
16:36:07.895 16
17:40:56.952 17
18:44:02.251 18
```

I also verified in VLC that the Meta Markers are present in the mp3 files: 

```
<Markers>
<Marker>
<Name>NAME OF BOOK</Name>
<Time>0:00.000</Time>
</Marker>
<Marker>
<Name>NAME OF CHAPTER 1</Name>
<Time>1:39.000</Time>
</Marker>
<Marker>
<Name>Book 1 - Chapter 1</Name>
<Time>50:07.000</Time>
</Marker>
</Markers>
```

**Comment by RunTheGambit** [comment]
Here is the Verbose log, in case that helps
[DebugLog.txt](https://github.com/sandreas/m4b-tool/files/8743648/DebugLog.txt)

**Comment by sandreas** [comment]
Yeah that will help, thank you. Maybe I cannot respond in the next days because my wife is heavily pregnant... :-)

**Comment by RunTheGambit** [comment]
No problem, you need to take care of your wife first!

**Comment by sandreas** [comment]
@RunTheGambit 
Maybe the new *official*  docker image could solve your problems!? I would really appreciate if you could try it out... Let my cite my prepared announcement:

There is a new "official" (still experimental) docker multiarch image and *SHOULD* work on `x64`, and `Raspberry` platforms. It is completely handcrafted and available for the following archs:

- linux/arm/v6
- linux/arm/v7
- linux/arm64
- linux/amd64

```bash
docker pull sandreas/m4b-tool:latest
```

In the near future, it will use tagging based on my new project [`tone`](https://github.com/sandreas/tone), which *SHOULD* be a huge improvement over the existing `mp4v2` and `ffmpeg` strategies. [The code is already commited](https://github.com/sandreas/m4b-tool/blob/master/src/library/Executables/Tone.php) and integrated in the docker image, but unfortunately there are some [*Known Issues*](https://github.com/sandreas/tone#known-issues), that prevent me from declaring `tone` as stable enough for production usage.

I need your help: Try out the new docker image and give feedback, so that we can get to a production ready release as soon as possible.

Feel free to reopen.
