### ISSUE TITLE
Getting a weird error

### ISSUE THREAD

**Issue by Etothetaui** [sandreas/m4b-tool#117]
It was working before but I tried to merge mp3 files today and got this error

`could not convert /home/raviph/Audiobooks/Cosmere (Brandon Sanderson)/Other/Arcanum Unbounded/Arcanum Unbounded-Part01.mp3 to -tmpfiles/01-Arcanum Unbounded-Part01-finished.m4b`

**Comment by Etothetaui** [comment]
Nevermind, I was doing it wrong

**Comment by harshanand120** [comment]
What did you do to run it successfully? I am still getting this error.

**Comment by Etothetaui** [comment]
> What did you do to run it successfully? I am still getting this error.

I haven't been able to get it to work for that book. I haven't really tried a lot life got busy.

**Comment by sandreas** [comment]
Some mp3 files are bogus and `ffmpeg` cannot convert these files. Most of the time, `fdkaac` (if installed, e.g. with the docker image) fixes these kind of problems. To force `fdkaac`, use `--audio-profile=aac_he` (it still uses ffmpeg for encoding, but the destination file will be created using `fdkaac`.
**Note: This only works, if `fdkaac` is available.**

```
m4b-tool merge \
--batch-pattern="input/%g/%a/%s/%p - %n/" \
--batch-pattern="input/%g/%a/%n/" \
"input/" \
--output-file="output/" \
--max-chapter-length=300,900 \
--adjust-for-ipod \
--audio-channels=1 \
--audio-bitrate=64k \
--audio-samplerate=22050 \
--audio-codec=libfdk_aac \
--audio-profile=aac_he \
--equate=name,album \
--ignore-source-tags \
--prepend-series-to-longdesc \
--silence-min-length=1000 \
--chapter-algo=grouping \
--skip-cover-if-exists
```
