### ISSUE TITLE
Add chapters from File

### ISSUE THREAD

**Issue by jbroenstrup** [sandreas/m4b-tool#119]
I feed really stupid. I have a file `audiobook.m4b` without chapters. And I have a list of chapters in `chapters.txt` like so:

```
00:00:00.000 Intro
00:00:24.000 First chapter
```

How do I get this chapters into my file? I have been reading the docs and trying many different things, but have had no success ... what am I missing?

**Comment by littlejeem** [comment]
> I feed really stupid. I have a file `audiobook.m4b` without chapters. And I have a list of chapters in `chapters.txt` like so:
> 
> ```
> 00:00:00.000 Intro
> 00:00:24.000 First chapter
> ```
> 
> How do I get this chapters into my file? I have been reading the docs and trying many different things, but have had no success ... what am I missing?

@jbroenstrup I could be wrong and I'm writing at speed so I'm sure sandreas will correct if so

Section 3 of the readme is Chapters and states

```fixed chapters
If you would like to adjust chapters manually, you can add a chapters.txt (same location as cover.jpg) with following contents (<chapter-start> <chapter-title>):

00:00:00.000 Intro
00:04:19.153 This is
00:09:24.078 A way to add
00:14:34.500 Chapters manually```

I've used this method myself before

**Comment by sandreas** [comment]
@littlejeem Thanks for stepping in

@jbroenstrup 

> How do I get this chapters into my file? 

There are a few ways, depending on what your environment is and what you would expect. Here are 2 simple ways, you could try: 

# 1. With the latest pre-release of `m4b-tool` (recommended)
```
m4b-tool meta audiobook.m4b --import-chapters=chapters.txt
```

# 2. Use `mp4chaps` directly (NOT `m4b-tool`) 
If you have `mp4chaps` installed and not use the docker image, rename `chapters.txt` to `<name-of-m4b-file>.chapters.txt`, put it in the same directory as `<name-of-m4b-file>.m4b` and run:
```
mp4chaps -i `audiobook.m4b`
```

**Comment by jbroenstrup** [comment]
> # 1. With the latest pre-release of `m4b-tool` (recommended)
> ```
> m4b-tool meta audiobook.m4b --import-chapters=chapters.txt
> ```

This worked perfectly! Thank you so much!
