### ISSUE TITLE
Merging files with sub-chapters does not work (formerly: Merge Chapters from existing M4B files)

### ISSUE THREAD

**Issue by colwellkr** [sandreas/m4b-tool#122]
I'm using this tool for the first time, so I apologize if the feature exists and I missed it in the documentation, but I am attempting to merge two fully chapterized M4B files into a single file and the result ends up ignoring all of their chapters and creating two chapters no names and the timestamps of the two input files.

`m4b-tool merge . --no-conversion --output-file=Title.m4b`

The closest parameter I found was `--no-chapter-reindexing` but that just results in two chapters with slightly different names.

Is there any way to important the chapter tags from M4B files that are being merged?

I'm currently running the latest build from git in Docker on WSL2. Thanks!

**Comment by colwellkr** [comment]
One other thing I noticed that may be a relic from #27 is that when using `--no-conversion` the "-tmpfiles" directory does not get cleaned up at the end of the process.

**Comment by sandreas** [comment]
I'll take a look in the next days.

**Comment by sandreas** [comment]
Which version are you using? Its working for me with the latest pre-release.

**Comment by colwellkr** [comment]
Not sure why I didn't see the email about your reply, sorry for the delay.

I was using the latest code from GitHub as of 1 Feb built into a Docker container.

Running `--version` reports `m4b-tool v.0.4.2`. 

I see you've made several commits in the last few weeks, so I can try rebuilding either from the latest pre-release or the latest source.

**Comment by colwellkr** [comment]
Update: I figured out how to build from pre-release. I didn't realize I had to give a specific file/link in the docker build command.
I rebuilt on `m4b-tool latest-127-gb61f0f8` but it's still not quite working right.

Not sure if there is a better way to show the chapters list, but I'm doing my best..
Part 1 file's chapters:
![image](https://user-images.githubusercontent.com/8947323/107990372-5b2d1b80-6fa2-11eb-8ea2-e88db3a2e5f3.png)
Part 2 file's chapters:
![image](https://user-images.githubusercontent.com/8947323/107990412-6da75500-6fa2-11eb-8324-62aebbf1e790.png)
Output file:
![image](https://user-images.githubusercontent.com/8947323/107990510-992a3f80-6fa2-11eb-843d-a5bcbbb40a4b.png)
![image](https://user-images.githubusercontent.com/8947323/107990455-831c7f00-6fa2-11eb-99f0-b70a54336349.png)
![image](https://user-images.githubusercontent.com/8947323/107990522-9e878a00-6fa2-11eb-965d-d8cfb396ecb1.png)

What it looks like is happening is it is not offsetting the second file's chapters by the length of the first part. They'll all getting overlaid on top of each other. Because all of the chapter names are in there, just exactly where they would be if it were two separate files.

**Comment by sandreas** [comment]
Could you provide the full command line that you use?
`m4b-tool merge ....`

Then I can try to reproduce the problem. Thank you for your patience.

**Comment by colwellkr** [comment]
Yep, sorry for the late response.

Full command I used was: 
```docker run -it --rm -v "C:\path\to\book":/mnt m4b-tool merge . --no-conversion --output-file="Book.m4b")```

**Comment by sandreas** [comment]
Should be fixed in the latest pre-release. Feedback would be great.
