### ISSUE TITLE
Recommended workflow for merging audiobooks from disks?

### ISSUE THREAD

**Issue by csandman** [sandreas/m4b-tool#126]
I'm currently in the process of merging a bunch of audiobooks from CDs where each chapter is made up of multiple tracks.  I'd like to use the merge tool however I'm curious if there is a recommended way to assign chapters.  In the past I have used GUI tools like AudioBookBinder for MacOS where I can combine tracks into chapters, so I have no problem listening for which tracks are the starts of chapters and sorting them as such

However, for this tool it seems the only way to assign chapters would be to add up the lengths of the tracks that make up a chapter and create the `chapters.txt` file from that.  Is there a more efficient way I might be able to achieve the same result?

I love this tool by the way, I've been using it a lot and am a huge fan!

**Comment by sandreas** [comment]
> I love this tool by the way, I've been using it a lot and am a huge fan!

You're very welcome :-)

Normaly, `m4b-tool` does the following:
- load the file tracks
- look for a `title` tag
- create a chapter for each `title`
- if chapters have the same name (e.g. `Spinner's end`, `Spinner's end`), then it will try to reindex the chapters (e.g. `Spinner's end`, `Spinner's end`)
- if there are `meta` files (like `chapter.txt`), it will replace the generated chapters by these

So normally `m4b-tool` should do automatically, what you are trying to achieve. If it does not, there is a NEW algorithm `--chapter-algo=grouping`, you could try with the latest `pre-release`:

```
m4b-tool merge -v --jobs=2 --no-cache --output-file="output/" --max-chapter-length=300,900 --adjust-for-ipod --equate=name,album --chapter-algo=grouping --prepend-series-to-longdesc --batch-pattern="input/%g/%a/%s/%p - %n/"  --batch-pattern="input/%g/%a/%n/" "input/" 
```

- `--equate=name,album` - will set  album and name to the same value (required by some players)
- `--chapter-algo=grouping` - uses the new chapter algorithm
- `--prepend-series-to-longdesc` - will prepend the series name to the description, if present
- the rest is explained in `best pracises` in the docs

If this does not work for you, I need to know more about your file structure (filenames and tags) and the command you are using.

**Comment by sandreas** [comment]
Closing due to no further feedback. Feel free to reopen.
