### ISSUE TITLE
Windows Version Does Not Create Chapters in .M4b Books

### ISSUE THREAD

**Issue by gattaca44** [sandreas/m4b-tool#127]
OS: Windows 10 x64 with all updates
Command: php m4b-tool.phar merge --use-filenames-as-chapters --jobs=8 --ffmpeg-threads=8 d:\m4b_input\ --output-file=d:\m4b_output\merged.m4b

So I have had great success with running m4b-tool 0.4.2 on Ubuntu, which gives me no problems. But when I ran the above command in version 0.4.2 on Windows, m4b-tool merges a folder full of .mp3 files into an .m4b audiobook with absolutely no chapters or cover. M4b-tool does, however, leave a merged.chapters text file in the output folder, and the chapters are listed in the text file perfectly. They are just not being encoded into the .m4b file.

I have double-checked all dependencies, especially mp4v2, and they seem to be correct. I also tried the Feb. 9, 2021 pre-release build of m4b-tool, which DOES make the book with the correct chapters. But I am paranoid about using the pre-release build because, for all I know, it may have problems. The "BE CAREFUL" warnings all over the pre-release download page have me a little spooked.

Is there some kind of a known issue with the Windows version of 0.4.2? I recreated the problem on a Windows 7 machine as well. Same result - no chapters.

And as long as I am asking about chapters . . . the merged.chapters.txt file is useful to me. But I don't see that being created in the pre-release build I tried. Can I plead that the feature not be taken out of the next release? The merged.chapters.txt file is good insurance for when/if I ever need to re-do chapters on a particular book.

Thanks for any help or advice on this great program.

**Comment by sandreas** [comment]
Could you try the latest pre-release. I did not have the time to release so MANY bugfixes have not made it into `0.4.2`.

**Comment by gattaca44** [comment]
Yes, as I mention in my post: **I also tried the Feb. 9, 2021 pre-release build of m4b-tool, which DOES make the book with the correct chapters. But I am paranoid about using the pre-release build because, for all I know, it may have problems. The "BE CAREFUL" warnings all over the pre-release download page have me a little spooked.**

I am fine with using it, if your estimation is that it is not risky. But can you address this question I had in my post about the "merged.chapters.txt" no longer being output in the latest pre-release version? 

From my post: **The merged.chapters.txt file is useful to me. But I don't see that being created in the pre-release build I tried. Can I plead that the feature not be taken out of the next release? The merged.chapters.txt file is good insurance for when/if I ever need to re-do chapters on a particular book.**

**Comment by sandreas** [comment]
> But I am paranoid about using the pre-release build because, for all I know, it may have problems

Yeah, unfortunately there will be no `RC` for some time. The `pre-release` is working well so far and as long as you don't experience problems with your typical tasks, it should work. So if you don't wanna use the `pre-release`, I can't do much about it atm. Sorry.

**Comment by gattaca44** [comment]
No worries. I have used the latest pre-release on five or six books and I can find no issues. Thanks for all your responses, and thanks for this great program. It's the best there is.

**Comment by sandreas** [comment]
> Thanks for all your responses, and thanks for this great program. It's the best there is.

Thank you, your very welcome. Closing this issue then.
