### ISSUE TITLE
Error when trying to split m4b file

### ISSUE THREAD

**Issue by seannymurrs** [sandreas/m4b-tool#128]
I followed the recommended installation instructions for m4b-tool on macOS, but I am getting the following error when I tried to split an m4b file by chapters.

```
sean@714dfff7-2453-42ab-85b7-0a6f2ce086da ~ % m4b-tool split --audio-format mp3 --audio-bitrate 64k --audio-channels 2 --audio-samplerate 22050 "/Users/sean/Desktop/Uncharted.m4b"
PHP Fatal error:  Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in phar:///opt/homebrew/Cellar/m4b-tool/0.4.2/bin/m4b-tool/vendor/twig/twig/src/Node/Node.php on line 43

Fatal error: Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in phar:///opt/homebrew/Cellar/m4b-tool/0.4.2/bin/m4b-tool/vendor/twig/twig/src/Node/Node.php on line 43
an error occured, that has not been caught:
Array
(
    [type] => 64
    [message] => Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)`
    [file] => phar:///opt/homebrew/Cellar/m4b-tool/0.4.2/bin/m4b-tool/vendor/twig/twig/src/Node/Node.php
    [line] => 43
)
```

**Comment by sandreas** [comment]
Is that on the latest `pre-release` or is it `0.4.2`

**Comment by seannymurrs** [comment]
> Is that on the latest `pre-release` or is it `0.4.2`

Just checked, and I'm running 0.4.2. I installed it using Homebrew. I see the installation instructions for the latest pre-release; will those instructions work for an installation done via Homebrew, or do I need to uninstall and manually install the pre-release?

**Comment by sandreas** [comment]
Please see https://github.com/sandreas/m4b-tool/releases/tag/latest - *MacOS / Linux* for instructions

**Comment by seannymurrs** [comment]
I updated to the latest pre-release, but now I am getting a different error. Now I’m getting the following:
```
In Mp4art.php line 85:
                              
  exporting cover to  failed
```
I’m not sure if I should open up a new issue for this, or if it’s somehow still related to the same thing.

**Comment by sandreas** [comment]
No, I'll take a look. You could try to add `--skip-cover` if you don't wanna wait, till it is fixed. Maybe this helps.

**Comment by sandreas** [comment]
```
 exporting cover to  failed
```

happens when m4b does not contain any cover. This should be fixed in the latest pre-release. Feedback would be great.
