### ISSUE TITLE
build.phar incompatible with PHP 7.2

### ISSUE THREAD

**Issue by markbarnes** [sandreas/m4b-tool#13]
On PHP 7.2 (I tested with 7.2.3), build.phar gives the message:

`[ErrorException]
  count(): Parameter must be an array or an object that implements Countable`

**Comment by sandreas** [comment]
I tried it on MacOS High Sierra with PHP 7.2.2 and it worked like expected (shell log see below) ... Could you provide more information about your environment:

- Which OS are you using?
- Which php-version? (php -v)
- Did you install composer (http://getcomposer.org)
- Did you perform a composer update in the source folder before building?

and if there is anything else i should know (like custom php.ini settings), this could be useful to know.
```
$ ./build 
Building...
$ php -v
PHP 7.2.2 (cli) (built: Feb  1 2018 13:23:34) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.2, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans

```

**Comment by sandreas** [comment]
Closed (no feedback, problem seems to be solved)
