### ISSUE TITLE
Merge no-conversion producing corrupt m4b

### ISSUE THREAD

**Issue by 3ncod3** [sandreas/m4b-tool#130]
Running `v.0.4.2` on `macOS 11.2.3`:

`m4b-tool merge -v --no-conversion  The\ Innovator\'s\ Dilemma -o The\ Innovator\'s\ Dilemma.m4b`

gives the following output:

```
determine highest available audio codec
Your ffmpeg version cannot produce top quality aac using encoder aac instead of libfdk_aac
reading metadata and streaminfo for file /Users/3ncod3/Downloads/The Innovator's Dilemma/The Innovator's Dilemma-Part01.mp3
using cover  The Innovator's Dilemma/cover.jpg
searching for description.txt in The Innovator's Dilemma
file description.txt not found or too big
using cover  The Innovator's Dilemma/cover.jpg
searching for chapters.txt in The Innovator's Dilemma
file chapters.txt not found or too big
rebuilding chapters from converted files title tags
merging The Innovator's Dilemma-tmpfiles//tmp_The Innovator's Dilemma.m4b, this can take a while
+++
check for sorting support in mp4tags
supported, proceeding...
tagging file The Innovator's Dilemma-tmpfiles//tmp_The Innovator's Dilemma.m4b
adding cover The Innovator's Dilemma/cover.jpg to The Innovator's Dilemma-tmpfiles//tmp_The Innovator's Dilemma.m4b
importing chapters for The Innovator's Dilemma-tmpfiles//tmp_The Innovator's Dilemma.m4b
```

Produces the `The Innovator's Dilemma.m4b` but it doesn't play nor does it have the cover so it seems to be corrupt. 

I've tried the homebrew installation and the docker one but am getting the same results.

However, when I run it without the `--no-conversion` option it produces the right output but it's encoded:
```
$ m4b-tool merge -v The\ Innovator\'s\ Dilemma -o The\ Innovator\'s\ Dilemma\ Encoded.m4b
determine highest available audio codec
reading metadata and streaminfo for file /mnt/The Innovator's Dilemma/The Innovator's Dilemma-Part01.mp3
+
searching for cover in The Innovator's Dilemma
using cover  The Innovator's Dilemma/cover.jpg
searching for description.txt in The Innovator's Dilemma
file description.txt not found or too big
preparing conversion with 1 simultaneous job, please wait...
   0 remaining /   10 total, preparing next task /
using cover  The Innovator's Dilemma/cover.jpg
searching for chapters.txt in The Innovator's Dilemma
file chapters.txt not found or too big
rebuilding chapters from converted files title tags
merging The Innovator's Dilemma Encoded-tmpfiles//tmp_The Innovator's Dilemma Encoded.m4b, this can take a while
+
check for sorting support in mp4tags
supported, proceeding...
tagging file The Innovator's Dilemma Encoded-tmpfiles//tmp_The Innovator's Dilemma Encoded.m4b
adding cover The Innovator's Dilemma/cover.jpg to The Innovator's Dilemma Encoded-tmpfiles//tmp_The Innovator's Dilemma Encoded.m4b
importing chapters for The Innovator's Dilemma Encoded-tmpfiles//tmp_The Innovator's Dilemma Encoded.m4b
```

The `The Innovator's Dilemma` input directory contains:

```
The Innovator's Dilemma-Part01.mp3
The Innovator's Dilemma-Part02.mp3
The Innovator's Dilemma-Part03.mp3
The Innovator's Dilemma-Part04.mp3
The Innovator's Dilemma-Part05.mp3
The Innovator's Dilemma-Part06.mp3
The Innovator's Dilemma-Part07.mp3
The Innovator's Dilemma-Part08.mp3
The Innovator's Dilemma-Part09.mp3
The Innovator's Dilemma-Part10.mp3
The Innovator's Dilemma.chapters.txt
The Innovator's Dilemma.wax
cover.jpg
```

**Comment by sandreas** [comment]
This is intended. The `--no-conversion` flag is only useful to save time, if and only if the input files and the output file should the same codec, bitrate etc. 

So basically the `--no-conversion` results in concatening all the files, without reencoding them. If you have multiple `m4b` files as source, the result is not corrupt.

Maybe this should be made more clear in the docs.

**Comment by 3ncod3** [comment]
> This is intended. The `--no-conversion` flag is only useful to save time, if and only if the input files and the output file should the same codec, bitrate etc.
> 
> So basically the `--no-conversion` results in concatening all the files, without reencoding them. If you have multiple `m4b` files as source, the result is not corrupt.
> 
> Maybe this should be made more clear in the docs.

Yes, I do not want to re-encode them but just merge the mp3s into a m4b and add the cover.jpg image.

Is that not possible with this tool?

Do you have to re-encode to have the cover image embedded?

**Comment by sandreas** [comment]
> Yes, I do not want to re-encode them but just merge the mp3s into an m4b and add the cover.jpg image.

It is not possible to merge `mp3` without conversion into a valid `m4b` file. `m4b` was first used by apple, uses the `mp4` container format under the hood, which can store multiple streams of different content (like audio, video and subtitles). If only audio is used, these files are also referenced as `m4a` (which Apple uses for the file extensions `m4b`/*books* and `m4r`/*ringtones*). While the container format itself does not restrict the usable audio codecs, the supported audio codecs for `m4b` are AFAIK ONLY `aac` and `alac` (AND NOT `MP3`) - thus producing a valid `m4b` file without re-encoding the `mp3` files won't work in any tool that I know.

You could merge it with `--no-conversion` into a destination `mp3` file, since `--no-conversion` implies that the source files are in the same format as the destination. If you would like to have a valid `m4b` file out of `mp3`'s, you MUST re-encode them with the `aac` or `alac` codec, which `m4b-tool` does automatically for you, unless you force `--no-conversion`.

**Comment by 3ncod3** [comment]
> > Yes, I do not want to re-encode them but just merge the mp3s into an m4b and add the cover.jpg image.
> 
> It is not possible to merge `mp3` without conversion into a valid `m4b` file. `m4b` was first used by apple, uses the `mp4` container format under the hood, which can store multiple streams of different content (like audio, video and subtitles). If only audio is used, these files are also referenced as `m4a` (which Apple uses for the file extensions `m4b`/_books_ and `m4r`/_ringtones_). While the container format itself does not restrict the usable audio codecs, the supported audio codecs for `m4b` are AFAIK ONLY `aac` and `alac` (AND NOT `MP3`) - thus producing a valid `m4b` file without re-encoding the `mp3` files won't work in any tool that I know.
> 
> You could merge it with `--no-conversion` into a destination `mp3` file, since `--no-conversion` implies that the source files are in the same format as the destination. If you would like to have a valid `m4b` file out of `mp3`'s, you MUST re-encode them with the `aac` or `alac` codec, which `m4b-tool` does automatically for you, unless you force `--no-conversion`.

Thanks for the explanation.

I want the highest quality, so I need to manually deduce and specify the best bitrate, samplerate, ...? Or is there a high-quality preset I can use where `m4b-tool` automatically does that for me? 
 
Also if I just run without specifying any encoding params `m4b-tool merge "data/my-audio-book/" --output-file="data/merged.m4b"`, what default encoding params will it use?

**Comment by sandreas** [comment]
There are several options providing `--audio-...` parameters, e.g. `--audio-bitrate 96k`,  `--audio-channels 1` and `--audio-samplerate 22050`.  The defaults are `64k`, `mono`, `22050` which provides a decent balance between filesize and quality. If your source material is good enough, the quality is sufficient. Increasing the bitrate or sample rate might be quite useless, if your source material is `mp3` < 192kbps.

Here are my personal settings (only works with latest pre-release) - i marked the ones you probably won't need with a `!`:

```
--jobs=2 # ! two cpu cores
--no-cache # ! no caching
-v # verbose output
--max-chapter-length=300,900 # max chapter length 15 mins, try to match 5 minutes
--adjust-for-ipod # ! if samplerate is too high for ipods, auto correct
--audio-channels=1 # use mono
--audio-bitrate=64k # 64k aac by default
--audio-samplerate=22050 # 22050 samplerate by default
--audio-profile=aac_he # use fdkaac encoder with aac_he profile
--equate=name,album # if album is empty, use name tag and write it to album
--ignore-source-tags # ! ignore source material tags that are non chapter related
--prepend-series-to-longdesc # if series is set, prepend it to the long description - e.g. Harry Potter 1 - Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling.
--silence-min-length=1000 # on silence detection use 1000ms (instead of default 1750ms)
--chapter-algo=grouping  # use the new experimental chapter algorithm 'grouping'
--skip-cover-if-exists # ! if cover already exists in file system, do not export, even if -f is given
```

I'm closing this ticket, since it is more like a documentation issue and i plan to rewrite the docs, as soon as there is enough time.
