### ISSUE TITLE
Mac Bug: `could not convert ./._Disk 01 - Track 01.flac...`

### ISSUE THREAD

**Issue by csandman** [sandreas/m4b-tool#131]
It appears that this app is attempting to convert the `._` hidden files that are automatically created on MacOS to store file information.  I believe these are only created because the files are stored on an external drive, however it is pretty frustrating.

Here is the full error:

```
could not convert /mnt/Will Hobbs - Down the Yukon/._Disk 01 - Track 01.flac to ./Will Hobbs - Down the Yukon-tmpfiles/001-._Disk 01 - Track 01-finished.m4b
```

A preferred solution would be if this tool ignored all files that began with `._` as that is the common pattern among these files.

One way people can get around this manually is by running the following command on the folder where the files are stored:

```
dot_clean PATH_OF_FOLDER_OR_DRIVE
```

**Comment by sandreas** [comment]
Nice find... I did not know that the resource / data fork files are named with the exact same extension. The problem is, that this might also happen, when you are not using `MacOS` - e.g. when a linux user is accesing a share also used by `MacOS` users. So I think, that I will implement this as `--exclude-pattern` defaulting to `._*`... But this may take a while, I would like to think over a more generic concept for this.

**Comment by csandman** [comment]
@sandreas It sounds like in the problem you described, it would make sense to exclude all files files beginning with `._` automatically, regardless of the user's OS, and maybe add the option to exclude others as well?

If you wanted to use regex the basic pattern could just be something like `^\._`

**Comment by sandreas** [comment]
@csandman Yes, this would be my first approach. I prefer to use glob-patterns (`--exclude='._*'`), since they are a lot easier to use and to understand with an extension to regex, if required (`exclude-regex='^\._.*'`) because regex is happening under the hood anyway... But I have to verify that.

**Comment by csandman** [comment]
@sandreas Sounds good to me!  I'm not very familiar with glob patterns but if its just an extension of regex than I'm sure it's a good choice!

**Comment by csandman** [comment]
@sandreas  btw, I was wondering if there was a way to prevent the `book_title.chapters.txt` file from being created next to the output book file?  I could do it programmatically, but I was just curious if there was something built in.

Sorry if this should be its own issue, I just figured it was small so I might as well ask.

**Comment by sandreas** [comment]
Its ok to ask here. Are you using the latest pre-release? It should not be created (or at least not kept) there, if it did not already exist.
