### ISSUE TITLE
ffmpeg warning (homebrew)

### ISSUE THREAD

**Issue by kour1er** [sandreas/m4b-tool#134]
I'm not sure if I have something configured wrong but I'm getting the warning:

> ffmpeg version 4.0.0 or higher is required - installed version 2.0.0 is likely to cause errors or unexpected behaviour...

when my version of ffmpeg installed via homebrew is:

> ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers

this is with the latest (2021-02-09) of m4b-tool. Any pointers as to what I might be doing wrong?

**Comment by kour1er** [comment]
How odd! I'm pretty sure I'm running both as myself :)

I'm calling m4b-tool from a python script (I'm using python to do some pre and post sorting) but I'm running python as me. So just double checked, php python and ffmpeg are all running as me. Is there something else I can check? Just to be clear, m4b-tool is working great - I'd just like to get rid of the warning :)

**Comment by sandreas** [comment]
> Is there something else I can check?

The only things that i can think of are:
- Environment changes (maybe the PATH variable is different in your python env)
- Alias (maybe you have an alias for `ffmpeg`, that is not used in python)

> I wonder if ffmpeg is changing the way it is reporting it's version number?

I don't think so, this would be very odd and the code the detect that is pretty robust. I checked that twice and it worked on all my systems. Feedback would be awesome.
