### ISSUE TITLE
Failure to build on OSX following directions SHA mismatch

### ISSUE THREAD

**Issue by SUBnet192** [sandreas/m4b-tool#136]
Already downloaded: /Users/marc/Library/Caches/Homebrew/downloads/6d4bbe32e4ca89238100e048908e2341190b798ad32d67c558be81f154eeffb3--php--8.0.6_1.big_sur.bottle.tar.gz
==> Downloading https://github.com/sandreas/mp4v2/tarball/master
==> Downloading from https://codeload.github.com/sandreas/mp4v2/legacy.tar.gz/master
               -=O=- #    #     #     #
Error: SHA256 mismatch
Expected: 3353b8289da1ddf84ea48d7e98ed8823d99548dbf8ada82dc3ef1c164bc81134
  Actual: c1f05db85c4c9bc631f0e312b08b9d3ea88f12d4d69f1896a49b6a7e96812b8c
    File: /Users/marc/Library/Caches/Homebrew/downloads/ba4b9f24c9abc855b34ac70dc60f5eba7e94b3384170ca29d825de69ee0809b0--sandreas-mp4v2-Release-ThirdParty-MP4v2-4.1.0.0-51-gf5a9b18.tar.gz
To retry an incomplete download, remove the file above.

**Comment by sandreas** [comment]
Ah sure, i forgot to update the hash... I'll fix that soon.

**Comment by sandreas** [comment]
Ok, should be fixed.
