### ISSUE TITLE
Why is it saying it needs cue sheet? Why would I use it if I had it?

### ISSUE THREAD

**Issue by ghost** [sandreas/m4b-tool#139]
![image](https://user-images.githubusercontent.com/1394030/121788684-e2e50880-cbd7-11eb-9f73-6fe0702fb45f.png)

**Comment by mevsme** [comment]
````
D:\Downloads\Клуб Дюма, или тень Ришелье>php m4b-tool.phar split "d:\Downloads\Клуб Дюма, или тень Ришелье\Клуб Дюма, или тень Ришелье, Part 1.m4b"
Your ffmpeg version cannot produce top quality aac using encoder aac instead of libfdk_aac

In SplitCommand.php line 167:

  split command assumes that file d:\Downloads\Клуб Дюма, или тень Ришелье\Клуб Дюма, или тень Ришелье, Part 1.cue ex
  ists and is readable


````

Isn't it supposed to use chapters of the m4b?

**Comment by sandreas** [comment]
Hey there,

it seems, that you are not using the latest pre-release, are you? If not, please upgrade, `0.4.2` is very old and I did not have the time to release a newer version with documentation.

> Isn't it supposed to use chapters of the m4b?

It would, but if it did not find any chapters embedded in the file, it tries to finde a `chapters.txt` or a `.cue`-sheet. So a file can only be splitted, if there are some kind of chapters. 
You can also use `--fixed-length`, at least if you use the latest prerelease.

**Comment by sandreas** [comment]
Closed due to no further feedback.
