### ISSUE TITLE
Could not convert…

### ISSUE THREAD

**Issue by markbarnes** [sandreas/m4b-tool#14]
With every folder I try, I get an error message similar to this one:

```
In MergeCommand.php line 323:

  could not convert E:\Users\Mark\Downloads\Audiobooks\Annihilation\001.mp3 to E:\Users\Mark\Downloads\Audiobooks\Annihilation-tmpfiles\1-001-converting.m4b
```

How can I diagnose the issue?

**Comment by sandreas** [comment]
You could try

```
  -d, --debug                                    file to dump debugging info
      --debug-filename[=DEBUG-FILENAME]          file to dump debugging info [default: "m4b-tool_debug.log"]
```

It should contain all messages and converting calls to ffmpeg. In most cases the requirements are not available (mp4v2 and / or ffmpeg). It it is something else, let me know :-)

**Comment by sandreas** [comment]
Closed (no feedback, problem seems to be solved)

**Comment by pgvee** [comment]
Hi Sandreas, 

I'm running in to a similar issue. I just compiled today and tried to glue a bunch of files together. I've attached a debug log. I'm hitting one of the exceptions in MergeCommand.php (on line 588), but I'm not good enough in PHP to figure out why the file doesn't exist.. 

[m4b-tool.log](https://github.com/sandreas/m4b-tool/files/3882985/m4b-tool.log)

**Comment by sandreas** [comment]
I see that there is some hints in the logs, but the real reason for this is unclear. I have to investigate this further - thank you for the logfile. I replaced the Names in the logfile and removed personal information (thats why i removed the logfile from the comment above, i was not sure if you were ok publishing that or if you just missed it)...

Let me ask you some questions before I check the problems:
- Which operating system are you using? (Looks like Windows with Linux subsystem or Cygwin)
- If you use the `--debug` flag, are there still some `-tmpfiles` present in the according folder, is there an empty folder or just nothing but the original files?
- Does `ffmpeg` show any error, if you try to execute the command manually with command line (see below)?

You have to replace your names with them in the logfile.
```
'ffmpeg' '-hide_banner' '-i' 'input/Fantasy/Author/Series/4 - Title/001-track.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-strict' 'experimental' '-movflags' '+faststart' '-vn' '-ab' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'aac' '-f' 'mp4' '/mnt/c/Users/MyUser/m4b-tool/data/Title-tmpfiles/001-track-converting.m4b'
```

**Comment by pgvee** [comment]
Thank you for scrubbing my info off the internet. That was also a silly mistake.

To answer your questions:

- OS is Win 10 /w WSL running the ubuntu 16.04 WSL distro.
- No: There are no tmpfiles present
- YES: ffmpeg does not know what the max_muxing_queue_size is.

I see that my system-package FFMPEG version is ancient: 2.8.15. This does not support the max_muxing_queue_size option. I will update and we'll see what happens.

**Comment by sandreas** [comment]
> I see that my system-package FFMPEG version is ancient: 2.8.15. This does not support the max_muxing_queue_size option. I will update and we'll see what happens.

Yeah that might be the problem. I will soon add a check for the `ffmpeg` version - so that a warning is shown if the version is < `4.0.0`.

**Comment by pgvee** [comment]
I updated and the tool got through the conversion. Thank you for making this.

-Pete

**Comment by HabelStefan** [comment]
I am facing this issue too. Until a few hours ago everything works as expected but suddenly it stopped.
I am getting the following debug log which does not help me.
`
DEBUG           0ms ffmpeg -hide_banner -codecs
NOTICE          0ms determine highest available audio codec
DEBUG         254ms == load input files ==
NOTICE        268ms reading metadata and streaminfo for file /temp/fix/David Baldacci - Finstere Lügen (Gekürzt)/CD1/ 001 - David Baldacci - Kapitel 1 - Finstere Lügen.mp3
NOTICE        279ms searching for cover in David Baldacci - Finstere Lügen (Gekürzt)
NOTICE        279ms using cover  David Baldacci - Finstere Lügen (Gekürzt)/cover.jpg
NOTICE        279ms searching for description.txt in David Baldacci - Finstere Lügen (Gekürzt)
DEBUG         279ms checking file David Baldacci - Finstere Lügen (Gekürzt)/description.txt, realpath: 
NOTICE        279ms file description.txt not found or too big
NOTICE        279ms skip cover extraction, file David Baldacci - Finstere Lügen (Gekürzt)/cover.jpg already exists - use --force to overwrite
NOTICE        290ms preparing conversion with 1 simultaneous job, please wait...
ERROR       62312ms could not convert /temp/fix/David Baldacci - Finstere Lügen (Gekürzt)/CD1/ 001 - David Baldacci - Kapitel 1 - Finstere Lügen.mp3 to -tmpfiles/001- 001 - David Baldacci - Kapitel 1 - Finstere Lügen-finished.m4b
DEBUG       62312ms trace: #0 phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/MergeCommand.php(479): M4bTool\Command\MergeCommand->convertInputFiles()
#1 phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/MergeCommand.php(362): M4bTool\Command\MergeCommand->processInputFiles()
#2 phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/MergeCommand.php(194): M4bTool\Command\MergeCommand->processFiles()
#3 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Command/Command.php(255): M4bTool\Command\MergeCommand->execute()
#4 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(908): Symfony\Component\Console\Command\Command->run()
#5 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(269): Symfony\Component\Console\Application->doRunCommand()
#6 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun()
#7 phar:///usr/local/bin/m4b-tool/bin/m4b-tool.php(32): Symfony\Component\Console\Application->run()
#8 /usr/local/bin/m4b-tool(10): require('phar:///usr/loc...')
#9 {main}
`

Best regards,

Stefan
