### ISSUE TITLE
Unsatisfiable Constraints

### ISSUE THREAD

**Issue by hackmonker** [sandreas/m4b-tool#140]
This error keeps popping up while building. Any clues what might cause this?

```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/armv7/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.9/main/armv7/APKINDEX.tar.gz: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/armv7/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.9/community/armv7/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
```

**Comment by hackmonker** [comment]
I might add that I am trying to run this in a raspberry pi, so is that a problem?

**Comment by sandreas** [comment]
I'll have to check, if this is a problem - but it seems that the file that is required was temporarily not available. If it should  work within 48h, you can close the issue. If not, I'll take a look.

**Comment by hackmonker** [comment]
ok thanks

**Comment by hackmonker** [comment]
> 
> 
> I'll have to check, if this is a problem - but it seems that the file that is required was temporarily not available. If it should work within 48h, you can close the issue. If not, I'll take a look.

looks like using https, I can download it but http seems to not load. this is just with the link in browser so this might not be the issue. just informing in case it helps

**Comment by hackmonker** [comment]
still getting it. will check for another 24 hours and tell.

**Comment by sandreas** [comment]
I think the problem can be seen as confirmed. I'll take a look in the next days.

**Comment by hackmonker** [comment]
ok thanks

**Comment by hackmonker** [comment]
Any solutions for this yet?

**Comment by sandreas** [comment]
Unfortunately not... sorry busy atm.

**Comment by hackmonker** [comment]
ok sure. when you get free

**Comment by sandreas** [comment]
What raspberry btw?

**Comment by djdembeck** [comment]
Alpine 3.9 is no longer a supported release by Alpine: https://alpinelinux.org/releases/

It could be they are turning off some (or all) repositories

**Comment by hackmonker** [comment]
> 
> 
> What raspberry btw?

rpi 4 b

**Comment by sandreas** [comment]
Should be fixed (I updated all dependencies and `mp4v2`). Feel free to reopen, if it did not work for you.
