### ISSUE TITLE
Option to disable cover search

### ISSUE THREAD

**Issue by djdembeck** [sandreas/m4b-tool#143]
It seems even with `--skip-cover`, that autoCoverFile still runs.
https://github.com/sandreas/m4b-tool/blob/d5696aa27e01894dbb3cdca11df9a3002e421082/src/library/Command/AbstractConversionCommand.php#L477

This is problematic, as I can pass a single mp3 file in a folder of other books I am going to merge, and it searches until it finds the first random jpg file.

Example case I noticed this in:
Input file of: `/input/The Code of the Woosters - Read by Jonathan Cecil.mp3`
```
searching for cover in /input
using cover /input/05 - Coot Club/Coot Club.jpg
skip cover extraction, a custom cover has been specified: /input/05 - Coot Club/Coot Club.jpg
```

**Comment by sandreas** [comment]
Mmh strange... Could you provide the full command line?

The linked piece of code is not executed, if `--skip-cover` is used... see https://github.com/sandreas/m4b-tool/blob/d5696aa27e01894dbb3cdca11df9a3002e421082/src/library/Command/AbstractConversionCommand.php#L472

Early return, if `--skip-cover` is present - no cover lookup.

**Comment by djdembeck** [comment]
Total noob mistake: didn't reload after changing my argument array haha. Working as intended. Sorry to waste your time.
