### ISSUE TITLE
ffmpeg version 4.0.0 is required

### ISSUE THREAD

**Issue by elmpp** [sandreas/m4b-tool#146]
Hi,

Exact same issue as https://github.com/sandreas/m4b-tool/issues/134

I'm running the latest prerelease due to seeing the same error as [here](https://github.com/sandreas/m4b-tool/issues/128)

I don't have any different users on this machine, m4b-tool was originally installed via homebrew (without sudo) and the phar replaced as mentioned in the issue above. There are no env vars relating to ffmpeg.

![Screenshot 2021-07-16 at 22 26 23](https://user-images.githubusercontent.com/864612/126004827-cc3bb6c4-0046-485c-9e47-309c09689c62.png)

```
 2021-07-16 22:24:10 ⌚  Matthews-MBP-2 in ~/torrent/Audiobooks/acc
○ → which ffmpeg
/usr/local/bin/ffmpeg

 2021-07-16 22:26:40 ⌚  Matthews-MBP-2 in ~/torrent/Audiobooks/acc
○ → /usr/local/bin/ffmpeg -version
ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers
built with Apple clang version 12.0.0 (clang-1200.0.32.29)
configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4-with-options_1 --enable-shared --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-demuxer=dash --disable-libjack --disable-indev=jack --enable-opencl --enable-videotoolbox --disable-htmlpages --enable-libfdk-aac --enable-nonfree
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100
```

**Comment by sandreas** [comment]
Aah now I see. `ffmpeg version 4.4` has no minor version number (like in `4.4.0`). That results in the regex not matching. Should be an easy fix. Thanks for the detailed report - you can ignore that warning, it should all work like expected.

**Comment by elmpp** [comment]
Yeah i was unsure whether it was still working or not. Is there any progress indication at all?

I'm attempting splitting a large file - 1.4Gb m4b 

Ideally i'd like to split it in 2 but on an arbitrary chapter. Is that possible?

**Comment by sandreas** [comment]
> Yeah i was unsure whether it was still working or not. Is there any progress indication at all?
No, currently not.

> Ideally i'd like to split it in 2 but on an arbitrary chapter. Is that possible?
Arbitrary? If you mean a specific chapter, you could create a chapters.txt with one chapter at exact the point where you wanna split or use the fixed time splitting...

**Comment by elmpp** [comment]
I would like to split it at a chapter somewhere near the middle (there are over 50 chapters)

**Comment by sandreas** [comment]
- Create an empty file <filename>.chapters.txt (where the audiobook is named <filename>.m4b)
- Add two lines, edit the timestamp where you wanna split, see example below
- Add parameter `--use-existing-chapters-file` to you split command

Example:
```
00:00:00.000 Chapter 1
07:57:13.570 Chapter 2
```

**Comment by elmpp** [comment]
The `--use-existing-chapters` seems to have been ignored (more likely my command was wrong)

Wow, that took 4 hours to split. I assume this is due to the m4b format?
 
@sandreas 

```bash
 2021-07-22 20:06:33 ⌚  Matthews-MBP-2 in ~/torrent/Audiobooks/acc
○ → time m4b-tool split --audio-format mp3 --audio-bitrate 96k --audio-channels 1 --audio-samplerate 22050 --use-existing-chapters-file ./The\ Collected\ Stories\ of\ Arthur\ C.\ Clarke.m4b
ffmpeg version 4.0.0 or higher is required - installed version 2.0.0 is likely to cause errors or unexpected behaviour...
extracting cover to ./The Collected Stories of Arthur C. Clarke_splitted/cover.jpg failed - maybe there was no cover embedded in ./The Collected Stories of Arthur C. Clarke.m4b

real	235m38.829s
user	51m11.125s
sys	2m9.715s

 2021-07-23 00:02:39 ⌚  Matthews-MBP-2 in ~/torrent/Audiobooks/acc
○ → ls -lh
total 2849928
-rw-r--r--    1 matt  staff   2.6K 16 Jul 21:57 The Collected Stories of Arthur C. Clarke.chapters.txt
-rwxr-----@   1 matt  staff   1.4G 16 Jul 00:05 The Collected Stories of Arthur C. Clarke.m4b
drwxr-xr-x  241 matt  staff   7.5K 23 Jul 00:02 The Collected Stories of Arthur C. Clarke_splitted

 2021-07-23 09:28:56 ⌚  Matthews-MBP-2 in ~/torrent/Audiobooks/acc
○ → du -hs ./*
4.0K	./The Collected Stories of Arthur C. Clarke.chapters.txt
1.4G	./The Collected Stories of Arthur C. Clarke.m4b
774M	./The Collected Stories of Arthur C. Clarke_splitted
```

**Comment by elmpp** [comment]
Oh I see, there is an existing `.chapters.txt` file in the directory. I assume it was that which was picked up
