### ISSUE TITLE
Issue with split by silence only finding one MusicBrainz chapter and not splitting chapters by silence

### ISSUE THREAD

**Issue by parkerRose** [sandreas/m4b-tool#148]
Hello, I am trying to split an audiobook that was a single mp3 file into chapters based on silence; however, it is only creating one chapter at 0:00. I have gotten it to work on a different file but this one says in the output `found 1 musicbrainz chapters and 295 silences within length 22:18:23.309`.
Here is the full command plus output 
`m4b-tool chapters --adjust-by-silence -o "emperor2.m4b" "emperor.m4b" -vvv --no-cache
m4b-tool development, OS: Darwin ( - )
'ffmpeg' '-hide_banner' '-version'
ffmpeg version 4.0.0 or higher is required - installed version 2.0.5 is likely to cause errors or unexpected behaviour...
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' 'emperor.m4b' '-vn' '-c:a' 'copy' '-f' 'crc' '-'
'ffmpeg' '-hide_banner' '-i' 'emperor.m4b' '-af' 'silencedetect=noise=-30dB:d=1.75' '-f' 'null' '-'
running silence detection for file emperor.m4b with min length 00:00:01.750
silence detection finished
'ffmpeg' '-hide_banner' '-i' 'emperor2.m4b' '-f' 'ffmetadata' '-'
'mp4info' 'emperor.m4b'
found 1 musicbrainz chapters and 295 silences within length 22:18:23.309
chapter: 00:00:00.000, no silence
'ffmpeg' '-hide_banner' '-i' 'emperor.m4b' '-f' 'ffmetadata' '-'
'mp4tags' '-help'
'mp4tags' '-a' 'Siddhartha Mukherjee' '-t' '1/55' '-s' 'The Emperor of All Maladies: A Biography of Cancer' '-g' 'History, Science & Technology, Health and Medicine' '-w' 'Read by Fred Sanders' '-y' '2011' '-E' 'Lavf58.76.100' '-i' '2' 'emperor.m4b'
'mp4chaps' '-i' 'emperor.m4b'
'ffmpeg' '-hide_banner' '-i' 'emperor.m4b' '-f' 'ffmetadata' '-'`
Let me know what more information you need from me as I am new to this, but I love the app, thanks for the hard work!

**Comment by sandreas** [comment]
> Hello, I am trying to split an audiobook that was a single mp3 file into chapters based on silence

Splitting by chapters is not `m4b-tool chapters`, but `m4b-tool split`. 

`m4b-tool chapters --adjust-by-silence` takes the existing chapters of a file and adjusts their position to the nearest silence. Your mp4-file contains 1 single chapter - which of course cannot be adjusted to match an existing silence. So it seems, that your original `m4b` has not been chapterized correctly.  If there are no chapters, there is nothing to adjust or split. 

What you could to, though, is to *abbuse* the `merge` command, to guess chapters by silence and define a max chapter length.

```bash
m4b-tool merge --max-chapter-length=300,900 -o emperor2.m4b emperor.m4b
```

This will result in a file containing chapters at a maximum of 15 minutes, but adjusted to silences if possible. Although this will lead to a reencode, you have at least chapters. If you are happy with it, you could also export them as `chapters.txt` and re-import them into the original file, to keep the quality, once you got it.

**Comment by parkerRose** [comment]
Makes sense, sorry for the amateur error. I went ahead and reran my chapters command right from the mp3 instead of the m4b I constructed first (since in error I thought I had to construct an m4b first to use the chapters command) and it worked. Thanks for the detailed response and this wonderful tool.
