### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function loadRecordings() on null

### ISSUE THREAD

**Issue by shlemas** [sandreas/m4b-tool#15]
I installed dependencies with brew on macOS High Sierra 10.13.6, including php v7.1.16.

I tried using the tool to split chapters on silence, and after a while of "detecting silence", this exception was thrown:

$ php m4b-tool.phar chapters -- "My Book.m4b" 
detecting silence of My Book.m4b
+++++++++++++++++++++++++++++++++++++++

Fatal error: Uncaught Error: Call to a member function loadRecordings() on null in phar:///Users/me/Downloads/m4b-tool.phar/src/library/M4bTool/Command/ChaptersCommand.php:156
Stack trace:
#0 phar:///Users/me/Downloads/m4b-tool.phar/src/library/M4bTool/Command/ChaptersCommand.php(98): M4bTool\Command\ChaptersCommand->buildChapters()
#1 phar:///Users/me/Downloads/m4b-tool.phar/vendor/symfony/console/Command/Command.php(251): M4bTool\Command\ChaptersCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///Users/me/Downloads/m4b-tool.phar/vendor/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///Users/me/Downloads/m4b-tool.phar/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(M4bTool\Command\ChaptersCommand), Object(Symf in phar:///Users/me/Downloads/m4b-tool.phar/src/library/M4bTool/Command/ChaptersCommand.php on line 156

Thoughts?

**Comment by shlemas** [comment]
I wasn't able to fix this, but I found a different solution for what I was trying to do directly with ffmpeg, so I don't really need resolution on this issue.

**Comment by sandreas** [comment]
Hi shlemas,

thx for reporting... although you don't need the fix any more, i'll take a look at it in the next weeks (i hope). At the moment i'm busy with other projects, but this definitely is a problem with m4b-tool. I'll reopen it, if you don't mind.

sandreas

**Comment by shlemas** [comment]
Sure. If you get time to look into it, I can try to test your changes.
