### ISSUE TITLE
Doubling file size

### ISSUE THREAD

**Issue by paulhargreaves** [sandreas/m4b-tool#151]
I take an MP3 file and convert to an M4B file, and the m4b is roughly double the size of the mp3.

I'm using no parameters other than the input/output.

```
$ m4b-tool --version
m4b-tool latest-137-g14781fb
$ ls -la
total 3744152
drwxr-xr-x  13 paulhargreaves  staff        416 16 Aug 11:25 .
drwxr-xr-x   4 paulhargreaves  staff        128 16 Aug 08:51 ..
-rw-r--r--@  1 paulhargreaves  staff       6148 16 Aug 10:54 .DS_Store
-rw-r--r--@  1 paulhargreaves  staff  291443337 16 Aug 08:52 source.mp3
-rw-r--r--   1 paulhargreaves  staff  658178972 16 Aug 10:58 output.m4b
# Generation command
$ m4b-tool -v merge source.mp3 --output-file output.m4b
```

Looking in vlc, I see from the codec tab that both files look similar - mono, 22050 hz, 32 bits per sample. bitrate of 32kb.

In statistics I  see that source.mp3 shows an input bitrate of 32 kb, and a stream bitrate of 32 kb.
I also see that the m4b has an input bitrate that varies, around the 70k mark, similarly with the stream bitrate.

I can see from help that there is a --audio-quality option, but to get a similar file size I'm having to use --audio-quality=20 which makes the audio quality significantly worse.

What other options should I consider?

**Comment by sandreas** [comment]
`--audio-bitrate` and `--audio-channels` should work

**Comment by paulhargreaves** [comment]
If I use --audio-bitrate 22050, --audio-channels 1, then the output is still 658178972.
I realise I'm transcoding so there will be some loss of fidelity, but I wouldn't expect to have to drop the quality significantly to get a comparable filesize, given that aac is more efficient than mp3.

Are there other settings I should be considering?

Thank you btw.

**Comment by sandreas** [comment]
`22050` looks like a sample-rate, not a bitrate... I assume you would like to use `--audio-bitrate 32k`... With `32k` you cannot expect the quality to be even close to the original material and I have no experience with bitrates this low...

However, my suggestion would be:

```
m4b-tool merge --audio-bitrate 32k --audio-samplerate 11025 --audio-channels 1 input.mp3 -o output.m4b
```

Depending on the player you would like to use and if you installed `fdkaac` you could add `--audio-profile aac_he_v2` to use the high effiency low bitrate encoder, which might improve the quality. In my personal tests this did never result in a quality improvement, but maybe it is worth a test.

**Comment by paulhargreaves** [comment]
I've manually ran ffmpeg manually with a bunch of options to see what makes a difference:

```
% ls -lS
total 11290640
-rw-r--r--@ 1 paulhargreaves  staff  544153253 18 Aug 09:45 output-vbr5-ac2-aac_he.m4b
-rw-r--r--  1 paulhargreaves  staff  544152849 18 Aug 09:24 output-vbr4-ac2-aac_he.m4b
-rw-r--r--  1 paulhargreaves  staff  508028003 18 Aug 09:19 output-vbr4-ac1-aac_he.m4b
-rw-r--r--@ 1 paulhargreaves  staff  508028003 18 Aug 09:32 output-vbr5-ac1-aac_he.m4b
-rw-r--r--@ 1 paulhargreaves  staff  496996927 18 Aug 09:29 output-vbr4-ac2-aac_he_v2.m4b
-rw-r--r--  1 paulhargreaves  staff  496996927 18 Aug 09:49 output-vbr5-ac2-aac_he_v2.m4b
-rw-r--r--@ 2 paulhargreaves  staff  291443337 16 Aug 08:52 source.mp3
-rw-r--r--@ 1 paulhargreaves  staff  268798166 18 Aug 09:12 output-vbr3-ac2-aac_he.m4b
-rw-r--r--@ 1 paulhargreaves  staff  261702903 18 Aug 09:07 output-vbr3-ac1-aac_he.m4b
-rw-r--r--@ 1 paulhargreaves  staff  256903045 18 Aug 09:16 output-vbr3-ac2-aac_he_v2.m4b
-rw-r--r--  1 paulhargreaves  staff  252700185 18 Aug 08:48 output-vbr2-ac2-aac_he.m4b
-rw-r--r--  1 paulhargreaves  staff  244206182 18 Aug 08:43 output-vbr2-ac1-aac_he.m4b
-rw-r--r--@ 1 paulhargreaves  staff  244078382 18 Aug 08:19 output-vbr1-ac1-aac_he.m4b
-rw-r--r--  1 paulhargreaves  staff  238485810 18 Aug 08:40 output-vbr1-ac2-aac_he_v2.m4b
-rw-r--r--  1 paulhargreaves  staff  237976995 18 Aug 08:52 output-vbr2-ac2-aac_he_v2.m4b
-rw-r--r--@ 1 paulhargreaves  staff  224139321 18 Aug 08:24 output-vbr1-ac2-aac_he.m4b
-rw-r--r--  1 paulhargreaves  staff          0 18 Aug 08:19 output-vbr1-ac1-aac_he_v2.m4b
-rw-r--r--  1 paulhargreaves  staff          0 18 Aug 08:43 output-vbr2-ac1-aac_he_v2.m4b
-rw-r--r--  1 paulhargreaves  staff          0 18 Aug 09:07 output-vbr3-ac1-aac_he_v2.m4b
-rw-r--r--  1 paulhargreaves  staff          0 18 Aug 09:19 output-vbr4-ac1-aac_he_v2.m4b
-rw-r--r--  1 paulhargreaves  staff          0 18 Aug 09:32 output-vbr5-ac1-aac_he_v2.m4b

```
The quality of -vn -sn -i source.mp3 -c:a libfdk_aac -vbr 3 -ac aac_he -profile:a <output> is good enough. I'm not sure how to translate that into m4b-tool though.

e.g.  
```
$ m4b-tool -vvv merge source.mp3 --audio-codec=libfdk_aac --audio-profile=aac_he_v2 --output-file foo.m4b  
m4b-tool development, OS: Darwin ( - )
'ffmpeg' '-hide_banner' '-version'
ffmpeg version 4.0.0 or higher is required - installed version 2.0.5 is likely to cause errors or unexpected behaviour...
== load input files ==
found 1 files to convert
searching for cover in 
cover not found or not specified
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' 'source.mp3' '-an' '-vcodec' 'copy' 'source.mp3/cover.jpg'
extracting cover to source.mp3/cover.jpg failed - maybe there was no cover embedded in source.mp3
preparing conversion with 1 simultaneous job, please wait...
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' 'source.mp3' '-map_metadata' '0' '-max_muxing_queue_size' '9999' '-movflags' '+faststart' '-vn' '-b:a' '64k' '-ar' '22050' '-ac' '0' '-acodec' 'libfdk_aac' '-f' 'mp4' 'foo-tmpfiles/1-converting.m4b'
   1 remaining /    1 total /^C
```

E.g. how do I suppress the -b:a and -ar entries, and --audio-profile isn't working. -ac 0?

Thanks again.

**Comment by sandreas** [comment]
```
m4b-tool merge -vvv --audio-bitrate 32k --audio-samplerate 11025 --audio-channels 1 --audio-profile aac_he_v2 -o foo.m4b source.mp3 
```

**Comment by paulhargreaves** [comment]
Thank you. Had to change the samplerate to 22050 but then it worked. Your help is appreciated.
