### ISSUE TITLE
Chapter naming

### ISSUE THREAD

**Issue by MarcioOliveira** [sandreas/m4b-tool#157]
Hello, is it possible to have the name of the chapters as the name of the files that are gonna be merged?

**Comment by sandreas** [comment]
`--use-filenames-as-chapters`

**Comment by MarcioOliveira** [comment]
A-WE-SOME!

**Comment by NominationP** [comment]
` m4b-tool merge "Arenapsactuallygoodforus.mp3" --output-file="Are naps actually good for us.m4b" --use-filenames-as-chapters  --debug`

--use-filenames-as-chapters  is not work

`=== tone.json ===
{
    "meta": {
        "encodingTool": "m4b-tool",
        "itunesMediaType": 2,
        "chapters": [
            {
                "start": 0,
                "length": 137473,
                "title": "1" // I think it should be filename
            }
        ]
    }
}`

**Comment by NominationP** [comment]
Solved!
use --no-chapter-reindexing together
