### ISSUE TITLE
Silently reindexes chapters

### ISSUE THREAD

**Issue by neingeist** [sandreas/m4b-tool#158]
I have an audiobook where *most* chapter input MP3s are titled "Chapter xx", but some are not. This gets silently reindexed (if I don't say `--no-chapter-reindexing`). Could there be a message that reindexing is performed?

I'm a little confused because I can't find the strings from `rebuilding chapters from converted files title tags` anywhere in the source code. Maybe you could point me to it, so I can do a PR to add a log message myself?

P.S.: I like to use m4b-tool, it's a handy tool :1st_place_medal:

**Comment by sandreas** [comment]
Chapter adjusting is a complex topic. I did many experiments to improve automatic chapter reindexing, so there is a lot of code. Maintaining it is a mess, but if you would like to add a log message, I thing this would be the right place:

https://github.com/sandreas/m4b-tool/blob/77928d6b7e9174476dea60e12690bbee522da4e8/src/library/Audio/Tag/AdjustTooLongChapters.php#L88

In general, you can take a look at https://github.com/sandreas/m4b-tool/tree/master/src/library/Audio/Tag. Every file in there contains a class with an "Improver". A tag goes in, an "improved" tag goes out. What the improvements are, is implemented in the specific class, e.g. you can look for a file, read it and write all tag fields, that are currently empty.

Please be aware, that my current and in my opinion BEST approach for chapter reindexing is not enabled by default and only available in latest pre-release. It works by building chapter groups and can be enabled by `--chapter-algo=grouping`, details in:

https://github.com/sandreas/m4b-tool/blob/master/src/library/Audio/Tag/AdjustChaptersByGroupLogic.php

**Comment by sandreas** [comment]
closing due to no further feedback - feel free to reopen.
