### ISSUE TITLE
ERROR while building docker container with podman: unsatisfiable constraints:   fdk-aac-dev (missing):     required by: world[fdk-aac-dev]

### ISSUE THREAD

**Issue by dmuiX** [sandreas/m4b-tool#159]
podman build . --build-arg M4B_TOOL_DOWNLOAD_LINK=https://github.com/sandreas/m4b-tool/files/6598116/m4b-tool.tar.gz -t m4b-tool
STEP 1/11: FROM alpine:3.9.2
Resolved "alpine" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/alpine:3.9.2...
Getting image source signatures
Copying blob sha256:8e402f1a9c577ded051c1ef10e9fe4492890459522089959988a4852dee8ab2c
Copying blob sha256:8e402f1a9c577ded051c1ef10e9fe4492890459522089959988a4852dee8ab2c
Copying config sha256:5cb3aa00f89934411ffba5c063a9bc98ace875d8f92e77d0029543d9f2ef4ad0
Writing manifest to image destination
Storing signatures
STEP 2/11: ENV WORKDIR /mnt
--> 5d0b30674a7
STEP 3/11: ARG FFMPEG_VERSION=4.1
--> 152396bbbfa
STEP 4/11: ARG PREFIX=/ffmpeg_build
--> fc2676ec19a
STEP 5/11: RUN echo "---- INSTALL BUILD DEPENDENCIES ----"     && apk add --no-cache --update --upgrade --virtual=build-dependencies     autoconf     automake     boost-dev     build-base     gcc     lame-dev     libogg-dev     yasm     nasm     yasm-dev     zlib-dev     freetype-dev     libogg-dev     libtheora-dev     libvorbis-dev     openssl-dev     opus-dev     git     wget && echo "---- INSTALL RUNTIME PACKAGES ----"     && apk add --no-cache --update --upgrade bzip2     ca-certificates     coreutils     curl     file     libtool     freetype     lame     libogg     libvpx     libvorbis     libtheora     libvorbis     openssl     opus     pcre     php7-cli     php7-dom     php7-intl     php7-json     php7-xml     php7-curl     php7-mbstring     php7-simplexml     php7-phar     php7-openssl     php7-zip     pkgconf     pkgconfig     tar     && echo http://dl-cdn.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories     && apk add --update fdk-aac-dev     && echo "date.timezone = UTC" >> /etc/php7/php.ini && echo "---- COMPILE FFMPEG ----"     && cd /tmp/     && wget http://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.gz     && tar zxf ffmpeg-${FFMPEG_VERSION}.tar.gz     && rm ffmpeg-${FFMPEG_VERSION}.tar.gz     && cd /tmp/ffmpeg-${FFMPEG_VERSION}     && ./configure     --enable-version3     --enable-gpl     --enable-nonfree     --enable-small     --enable-libmp3lame     --enable-libtheora     --enable-libvorbis     --enable-libopus     --enable-libfdk_aac     --enable-avresample     --enable-libfreetype     --enable-openssl     --disable-debug     --disable-doc     --disable-ffplay     --prefix="/tmp${PREFIX}"      --extra-cflags="-I/tmp${PREFIX}/include"     --extra-ldflags="-L/tmp${PREFIX}/lib"     --extra-libs="-lpthread -lm"     --bindir="/usr/local/bin/"      && make -j4 && make install && make distclean && hash -r && rm -rf /tmp/* && echo "---- COMPILE SANDREAS MP4V2 ----"     && cd /tmp/     && wget https://github.com/sandreas/mp4v2/archive/master.zip     && unzip master.zip     && rm master.zip     && cd mp4v2-master     && ./configure && make -j4 && make install && make distclean && rm -rf /tmp/* && echo "---- COMPILE FDKAAC ----"     && cd /tmp/     && wget https://github.com/nu774/fdkaac/archive/1.0.0.tar.gz     && tar xzf 1.0.0.tar.gz     && rm 1.0.0.tar.gz     && cd fdkaac-1.0.0     && autoreconf -i && ./configure && make -j4 && make install && rm -rf /tmp/* && echo "---- REMOVE BUILD DEPENDENCIES ----"     && apk del --purge build-dependencies
---- INSTALL BUILD DEPENDENCIES ----
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/95) Upgrading musl (1.1.20-r3 -> 1.1.20-r6)
(2/95) Upgrading libcrypto1.1 (1.1.1a-r1 -> 1.1.1k-r0)
(3/95) Upgrading libssl1.1 (1.1.1a-r1 -> 1.1.1k-r0)
(4/95) Upgrading ca-certificates-cacert (20190108-r0 -> 20191127-r2)
(5/95) Installing m4 (1.4.18-r1)
(6/95) Installing libbz2 (1.0.6-r7)
(7/95) Installing perl (5.26.3-r1)
(8/95) Installing autoconf (2.69-r2)
(9/95) Installing automake (1.16.1-r0)
(10/95) Installing linux-headers (4.18.13-r1)
(11/95) Installing boost-atomic (1.67.0-r2)
(12/95) Installing boost-system (1.67.0-r2)
(13/95) Installing libgcc (8.3.0-r0)
(14/95) Installing boost-chrono (1.67.0-r2)
(15/95) Installing boost-container (1.67.0-r2)
(16/95) Installing boost-context (1.67.0-r2)
(17/95) Installing boost-contract (1.67.0-r2)
(18/95) Installing boost-thread (1.67.0-r2)
(19/95) Installing boost-coroutine (1.67.0-r2)
(20/95) Installing boost-date_time (1.67.0-r2)
(21/95) Installing boost-filesystem (1.67.0-r2)
(22/95) Installing boost-fiber (1.67.0-r2)
(23/95) Installing boost-regex (1.67.0-r2)
(24/95) Installing boost-graph (1.67.0-r2)
(25/95) Installing boost-iostreams (1.67.0-r2)
(26/95) Installing boost-math (1.67.0-r2)
(27/95) Installing boost-prg_exec_monitor (1.67.0-r2)
(28/95) Installing boost-program_options (1.67.0-r2)
(29/95) Installing expat (2.2.8-r0)
(30/95) Installing libffi (3.2.1-r6)
(31/95) Installing gdbm (1.13-r1)
(32/95) Installing xz-libs (5.2.4-r0)
(33/95) Installing ncurses-terminfo-base (6.1_p20190105-r0)
(34/95) Installing ncurses-terminfo (6.1_p20190105-r0)
(35/95) Installing ncurses-libs (6.1_p20190105-r0)
(36/95) Installing readline (7.0.003-r1)
(37/95) Installing sqlite-libs (3.28.0-r3)
(38/95) Installing python3 (3.6.9-r3)
(39/95) Installing boost-python3 (1.67.0-r2)
(40/95) Installing python2 (2.7.18-r0)
(41/95) Installing boost-python (1.67.0-r2)
(42/95) Installing boost-random (1.67.0-r2)
(43/95) Installing boost-serialization (1.67.0-r2)
(44/95) Installing boost-signals (1.67.0-r2)
(45/95) Installing boost-unit_test_framework (1.67.0-r2)
(46/95) Installing boost-wave (1.67.0-r2)
(47/95) Installing boost-wserialization (1.67.0-r2)
(48/95) Installing libstdc++ (8.3.0-r0)
(49/95) Installing boost (1.67.0-r2)
(50/95) Installing boost-dev (1.67.0-r2)
(51/95) Installing binutils (2.31.1-r2)
(52/95) Installing libmagic (5.36-r1)
(53/95) Installing file (5.36-r1)
(54/95) Installing gmp (6.1.2-r1)
(55/95) Installing isl (0.18-r0)
(56/95) Installing libgomp (8.3.0-r0)
(57/95) Installing libatomic (8.3.0-r0)
(58/95) Installing mpfr3 (3.1.5-r1)
(59/95) Installing mpc1 (1.0.3-r1)
(60/95) Installing gcc (8.3.0-r0)
(61/95) Installing musl-dev (1.1.20-r6)
(62/95) Installing libc-dev (0.7.1-r0)
(63/95) Installing g++ (8.3.0-r0)
(64/95) Installing make (4.2.1-r2)
(65/95) Installing fortify-headers (1.0-r0)
(66/95) Installing build-base (0.5-r1)
(67/95) Installing lame (3.100-r0)
(68/95) Installing lame-dev (3.100-r0)
(69/95) Installing libogg (1.3.3-r2)
(70/95) Installing pkgconf (1.6.0-r0)
(71/95) Installing libogg-dev (1.3.3-r2)
(72/95) Installing yasm (1.3.0-r1)
(73/95) Installing nasm (2.13.03-r0)
(74/95) Installing yasm-dev (1.3.0-r1)
(75/95) Installing zlib-dev (1.2.11-r1)
(76/95) Installing libpng (1.6.37-r0)
(77/95) Installing freetype (2.9.1-r3)
(78/95) Installing libpng-dev (1.6.37-r0)
(79/95) Installing freetype-dev (2.9.1-r3)
(80/95) Installing libtheora (1.1.1-r13)
(81/95) Installing libtheora-dev (1.1.1-r13)
(82/95) Installing libvorbis (1.3.6-r2)
(83/95) Installing libvorbis-dev (1.3.6-r2)
(84/95) Installing openssl-dev (1.1.1k-r0)
(85/95) Installing opus (1.3-r0)
(86/95) Installing opus-dev (1.3-r0)
(87/95) Installing ca-certificates (20191127-r2)
(88/95) Installing nghttp2-libs (1.35.1-r2)
(89/95) Installing libssh2 (1.9.0-r1)
(90/95) Installing libcurl (7.64.0-r5)
(91/95) Installing pcre2 (10.32-r1)
(92/95) Installing git (2.20.4-r0)
(93/95) Installing wget (1.20.3-r0)
(94/95) Installing build-dependencies (0)
(95/95) Upgrading musl-utils (1.1.20-r3 -> 1.1.20-r6)
Executing busybox-1.29.3-r10.trigger
Executing ca-certificates-20191127-r2.trigger
OK: 529 MiB in 104 packages
---- INSTALL RUNTIME PACKAGES ----
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/28) Installing bzip2 (1.0.6-r7)
(2/28) Installing libattr (2.4.47-r7)
(3/28) Installing libacl (2.2.52-r5)
(4/28) Installing coreutils (8.30-r0)
(5/28) Installing curl (7.64.0-r5)
(6/28) Installing bash (4.4.19-r1)
Executing bash-4.4.19-r1.post-install
(7/28) Installing libltdl (2.4.6-r5)
(8/28) Installing libtool (2.4.6-r5)
(9/28) Installing libvpx (1.6.1-r1)
(10/28) Installing openssl (1.1.1k-r0)
(11/28) Installing pcre (8.42-r2)
(12/28) Installing php7-common (7.2.33-r0)
(13/28) Installing libedit (20181209.3.1-r0)
(14/28) Installing libxml2 (2.9.9-r3)
(15/28) Installing php7 (7.2.33-r0)
(16/28) Installing php7-curl (7.2.33-r0)
(17/28) Installing php7-dom (7.2.33-r0)
(18/28) Installing icu-libs (62.1-r1)
FROM alpine:3.9.2

ENV WORKDIR /mnt
ARG FFMPEG_VERSION=4.1
ARG PREFIX=/ffmpeg_build

RUN \
echo "---- INSTALL BUILD DEPENDENCIES ----" \
    && apk add --no-cache --update --upgrade --virtual=build-dependencies \
    autoconf \
    automake \
    boost-dev \
    build-base \
    gcc \
    lame-dev \
    libogg-dev \
    yasm \
    nasm \
    yasm-dev \
    zlib-dev \
    freetype-dev \
    libogg-dev \
    libtheora-dev \
    libvorbis-dev \
    openssl-dev \
    opus-dev \
    git \
    wget && \
echo "---- INSTALL RUNTIME PACKAGES ----" \
    && apk add --no-cache --update --upgrade bzip2 \
    ca-certificates \
    coreutils \
    curl \
    file \
    libtool \
    freetype \
    lame \
    libogg \
    libvpx \
    libvorbis \
    libtheora \
    libvorbis \
    openssl \
    opus \
    pcre \
    php7-cli \
    php7-dom \
    php7-intl \
    php7-json \
    php7-xml \
    php7-curl \
    php7-mbstring \
    php7-simplexml \
    php7-phar \
    php7-openssl \
    pkgconfig \
    tar \
    && echo http://dl-cdn.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories \
echo "---- COMPILE FFMPEG ----" \
    && cd /tmp/ \
    && wget http://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.gz \
    && tar zxf ffmpeg-${FFMPEG_VERSION}.tar.gz \
    && rm ffmpeg-${FFMPEG_VERSION}.tar.gz \
    && cd /tmp/ffmpeg-${FFMPEG_VERSION} \
    && ./configure \
    --enable-version3 \
    --enable-gpl \
    --enable-nonfree \
    --enable-small \
    --enable-libmp3lame \
    --enable-libtheora \
    --enable-libvorbis \
(19/28) Installing php7-intl (7.2.33-r0)
(20/28) Installing php7-json (7.2.33-r0)
(21/28) Installing php7-mbstring (7.2.33-r0)
    --enable-libtheora \
    --enable-libvorbis \
    php7-xml \
(22/28) Installing php7-openssl (7.2.33-r0)
(23/28) Installing php7-phar (7.2.33-r0)
(24/28) Installing php7-simplexml (7.2.33-r0)
(25/28) Installing php7-xml (7.2.33-r0)
(26/28) Installing libzip (1.5.1-r2)
(27/28) Installing php7-zip (7.2.33-r0)
(28/28) Installing tar (1.32-r0)
Executing busybox-1.29.3-r10.trigger
OK: 577 MiB in 132 packages
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  fdk-aac-dev (missing):
    required by: world[fdk-aac-dev]
Error: error building at STEP "RUN echo "---- INSTALL BUILD DEPENDENCIES ----"     && apk add --no-cache --update --upgrade --virtual=build-dependencies     autoconf     automake     boost-dev     build-base     gcc     lame-dev     libogg-dev     yasm     nasm     yasm-dev     zlib-dev     freetype-dev     libogg-dev     libtheora-dev     libvorbis-dev     openssl-dev     opus-dev     git     wget && echo "---- INSTALL RUNTIME PACKAGES ----"     && apk add --no-cache --update --upgrade bzip2     ca-certificates     coreutils     curl     file     libtool     freetype     lame     libogg     libvpx     libvorbis     libtheora     libvorbis     openssl     opus     pcre     php7-cli     php7-dom     php7-intl     php7-json     php7-xml     php7-curl     php7-mbstring     php7-simplexml     php7-phar     php7-openssl     php7-zip     pkgconf     pkgconfig     tar     && echo http://dl-cdn.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories     && apk add --update fdk-aac-dev     && echo "date.timezone = UTC" >> /etc/php7/php.ini && echo "---- COMPILE FFMPEG ----"     && cd /tmp/     && wget http://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.gz     && tar zxf ffmpeg-${FFMPEG_VERSION}.tar.gz     && rm ffmpeg-${FFMPEG_VERSION}.tar.gz     && cd /tmp/ffmpeg-${FFMPEG_VERSION}     && ./configure     --enable-version3     --enable-gpl     --enable-nonfree     --enable-small     --enable-libmp3lame     --enable-libtheora     --enable-libvorbis     --enable-libopus     --enable-libfdk_aac     --enable-avresample     --enable-libfreetype     --enable-openssl     --disable-debug     --disable-doc     --disable-ffplay     --prefix="/tmp${PREFIX}"      --extra-cflags="-I/tmp${PREFIX}/include"     --extra-ldflags="-L/tmp${PREFIX}/lib"     --extra-libs="-lpthread -lm"     --bindir="/usr/local/bin/"      && make -j4 && make install && make distclean && hash -r && rm -rf /tmp/* && echo "---- COMPILE SANDREAS MP4V2 ----"     && cd /tmp/     && wget https://github.com/sandreas/mp4v2/archive/master.zip     && unzip master.zip     && rm master.zip     && cd mp4v2-master     && ./configure && make -j4 && make install && make distclean && rm -rf /tmp/* && echo "---- COMPILE FDKAAC ----"     && cd /tmp/     && wget https://github.com/nu774/fdkaac/archive/1.0.0.tar.gz     && tar xzf 1.0.0.tar.gz     && rm 1.0.0.tar.gz     && cd fdkaac-1.0.0     && autoreconf -i && ./configure && make -j4 && make install && rm -rf /tmp/* && echo "---- REMOVE BUILD DEPENDENCIES ----"     && apk del --purge build-dependencies": error while running runtime: exit status 1

**Comment by sandreas** [comment]
Thx for the solution. I'll try to fix this.

**Comment by sandreas** [comment]
Maybe the new *official*  docker image could solve your problems!? I would really appreciate if you could try it out... Let my cite my prepared announcement:

There is a new "official" (still experimental) docker multiarch image and *SHOULD* work on `x64`, and `Raspberry` platforms. It is completely handcrafted and available for the following archs:

- linux/arm/v6
- linux/arm/v7
- linux/arm64
- linux/amd64

```bash
docker pull sandreas/m4b-tool:latest
```

In the near future, it will use tagging based on my new project [`tone`](https://github.com/sandreas/tone), which *SHOULD* be a huge improvement over the existing `mp4v2` and `ffmpeg` strategies. [The code is already commited](https://github.com/sandreas/m4b-tool/blob/master/src/library/Executables/Tone.php) and integrated in the docker image, but unfortunately there are some [*Known Issues*](https://github.com/sandreas/tone#known-issues), that prevent me from declaring `tone` as stable enough for production usage.

I need your help: Try out the new docker image and give feedback, so that we can get to a production ready release as soon as possible.
