### ISSUE TITLE
checksum calculation failed - invalid output

### ISSUE THREAD

**Issue by jeff47** [sandreas/m4b-tool#164]
OK, updated to ```m4b-tool latest-137-g14781fb```.  I'm getting a checksum error, which I've seen before.  I didn't see any previous reports - is this a corrupt mp3 or something?

Debug log:
[m4b-tool.log](https://github.com/sandreas/m4b-tool/files/7604794/m4b-tool.log)

```
ffmpeg version n4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
configuration: --prefix= --prefix=/usr --disable-debug --disable-doc --disable-static --enable-cuda --enable-cuda-sdk --enable-cuvid --enable-libdrm --enable-ffplay --enable-gnutls --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfontconfig --enable-libfreetype --enable-libmp3lame --enable-libnpp --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopus --enable-libpulse --enable-sdl2 --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libv4l2 --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxvid --enable-nonfree --enable-nvenc --enable-omx --enable-openal --enable-opencl --enable-runtime-cpudetect --enable-shared --enable-vaapi --enable-vdpau --enable-version3 --enable-xlib
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100
```

```
PHP 7.4.3 (cli) (built: Oct 25 2021 18:20:54) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
```

```
mp4chaps - MP4v2 -r
```

```
fdkaac 0.6.3
```

**Comment by sandreas** [comment]
Could you provide the complete command you were trying to execute?
It seems that you either missed a `.` in `--output-file` or something is wrong in the latest pre-release.

Either way, I need the full command to reproduce.

**Comment by jeff47** [comment]
```m4b-tool -vvv merge "A Good American Family - David Maraniss (MP3)"/ --output-file="A Good American Family - David Maraniss.m4b" --no-cache --debug```

Just to be sure, I ran it again - log file attached.
[m4b-tool.log](https://github.com/sandreas/m4b-tool/files/7605092/m4b-tool.log)

**Comment by sandreas** [comment]
```
DEBUG       25577ms 'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' 'A Good American Family - David Maraniss-tmpfiles/tmp_A Good American Family - David Maranissm4b' '-vn' '-c:a' 'copy' '-f' 'crc' '-'
```
Seems `David Maranissm4b` is missing a dot somehow. I'll take a look but as I already said in other issues, my time is very limited right now. Maybe you want to try an earlier version or working around this somehow, e.g. by providing `--audio-channels=1 --audio-bitrate=64k --audio-samplerate=22050 --audio-codec=libfdk_aac --audio-profile=aac_he`

**Comment by jeff47** [comment]
Same error with the additional parameters.

I tried it with an alternative filename, and the error seems the same although the dot seems to be present.

```
==> trying improver AudibleChaptersJson
content_metadata_*.json not found - tags not improved
'ffmpeg' '-nostats' '-loglevel' 'panic' '-hide_banner' '-i' 'test-tmpfiles/tmp_test.m4b' '-vn' '-c:a' 'copy' '-f' 'crc' '-'
checksum calculation failed - invalid output CRC=0x2590a3d6

```

**Comment by sandreas** [comment]
I think I might have found something:

What about the additional Slash (`/`) you provided in `"A Good American Family - David Maraniss (MP3)"/ `?
```
m4b-tool -vvv merge "A Good American Family - David Maraniss (MP3)"/ --output-file="A Good American Family - David Maraniss.m4b" --no-cache --debug
```
Could you try: `"A Good American Family - David Maraniss (MP3)"`?

If that does not help, I'll try to figure it out, the piece of code that might go wrong is here:

https://github.com/sandreas/m4b-tool/blob/801544de9e576bdf5e82d35d68f47efb1234aab3/src/library/Command/MergeCommand.php#L767
