### ISSUE TITLE
Docker image for arm64

### ISSUE THREAD

**Issue by hackmonker** [sandreas/m4b-tool#165]
Any chance of an arm docker to be used in rpi? really want to use it but only have an rpi currently. hopefully the dev or someone else can spin up an arm container

**Comment by sandreas** [comment]
Thanks for reporting. I'm quite sure this has already been reported somewhere, but unfortunately I have no clue, whats wrong with it. My guess would be that this is something with either `ffmpeg` or `mp4v2`... I'll leave this issue open until someone is able to help.

**Comment by cartwmic** [comment]
I was able to get m4b-tool working by replacing https://github.com/sandreas/m4b-tool/blob/06c897dd4f91b770d0300c7bf3f267b6abe3f308/Dockerfile#L1-L4 with `
  FROM node:alpine3.15 AS ffmpeg_binary

  RUN npm install ffmpeg-static; \
      cp /cartwmic-home/node_modules/ffmpeg-static/ffmpeg /ffmpeg
  ARG FFMPEG_PATH="/ffmpeg"

`

**Comment by sandreas** [comment]
> I was able to get m4b-tool working by replacing 

Thanks for the hint. 

You could also download the according release manually from: https://github.com/eugeneware/ffmpeg-static/releases/ (where the `npm` gets its release from).

The only caveat is, that it does not support `fdk`, which is the better codec, but this should only be a hardly noticable quality difference.

I would fix this myself but maintaining an `ffmpeg` docker image is just not possible atm.

**Comment by sandreas** [comment]
This should fixed in the dependency image. Feedback is welcome, if there is none, I'll close this assuming that it now works.

**Comment by Snuffy2** [comment]
Just tried it and it is now working for me on arm64. Thanks!
