### ISSUE TITLE
Issue with docker build command.  wget: bad address 'github.com'

### ISSUE THREAD

**Issue by DarthDobber** [sandreas/m4b-tool#168]
When running the build command I receive the following error message. 

`---- INSTALL M4B-TOOL ----
wget: bad address 'github.com'
The command '/bin/sh -c echo "---- INSTALL M4B-TOOL ----"     && if [ ! -f /tmp/m4b-tool.phar ]; then             wget "${M4B_TOOL_DOWNLOAD_LINK}" -O /tmp/m4b-tool.tar.gz &&             if [ ! -f /tmp/m4b-tool.phar ]; then                 tar xzf /tmp/m4b-tool.tar.gz -C /tmp/ && rm /tmp/m4b-tool.tar.gz ;            fi        fi     && mv /tmp/m4b-tool.phar /usr/local/bin/m4b-tool     && M4B_TOOL_PRE_RELEASE_LINK=$(wget -q -O - https://github.com/sandreas/m4b-tool/releases/tag/latest | grep -o 'M4B_TOOL_DOWNLOAD_LINK=[^ ]*' | head -1 | cut -d '=' -f 2)     && wget "${M4B_TOOL_PRE_RELEASE_LINK}" -O /tmp/m4b-tool.tar.gz     && tar xzf /tmp/m4b-tool.tar.gz -C /tmp/ && rm /tmp/m4b-tool.tar.gz     && mv /tmp/m4b-tool.phar /usr/local/bin/m4b-tool-pre     && chmod +x /usr/local/bin/m4b-tool /usr/local/bin/m4b-tool-pre' returned a non-zero code: 1
`

**Comment by sandreas** [comment]
This may be a temporary issue... to get rid of this, try to download and extract the desired `m4b-tool.phar` manually to the `dist` dir and rerun the `docker build ...` command.

**Comment by DarthDobber** [comment]
That fixed it.  Thanks!
