### ISSUE TITLE
SHA256 mismatch

### ISSUE THREAD

**Issue by garlik82** [sandreas/m4b-tool#172]
When trying to install m4b-tool on Mac over brew I get this while following the install instructions: 

==> Downloading https://github.com/sandreas/mp4v2/tarball/master
Already downloaded: /Users/tiagalho/Library/Caches/Homebrew/downloads/ba4b9f24c9abc855b34ac70dc60f5eba7e94b3384170ca29d825de69ee0809b0--sandreas-mp4v2-Release-ThirdParty-MP4v2-4.1.0.0-67-g480a733.tar.gz
Error: m4b-tool: SHA256 mismatch
Expected: 2b37a9300b2cba9bb54cf49e2fec7d46b527c4f73f5ca401bc79c9426152f061
  Actual: 09e5342d1f19523641ce3c3ea7e8a7158af54b731dde7c595e5e11231c9f59fc
    File: /Users/tiagalho/Library/Caches/Homebrew/downloads/ba4b9f24c9abc855b34ac70dc60f5eba7e94b3384170ca29d825de69ee0809b0--sandreas-mp4v2-Release-ThirdParty-MP4v2-4.1.0.0-67-g480a733.tar.gz
To retry an incomplete download, remove the file above.

I remove the file but get the same result.
Thanks for the awesome tool.

OS: Monterey 12.2

**Comment by sandreas** [comment]
Thanks for reporting, I have to investigate that, maybe my last commit crashed something. I will invest some time in `m4b-tool` in the next weeks.

**Comment by garlik82** [comment]
Thanks for the speedy response and thanks for your work.

**Comment by fabianlischka** [comment]
Same issue, on Monterey 12.1.
Danke, Andreas!

```
> brew install sandreas/tap/m4b-tool
[.......]
==> Downloading https://github.com/sandreas/mp4v2/tarball/master
==> Downloading from https://codeload.github.com/sandreas/mp4v2/legacy.tar.gz/master
      # -=#=- #    #                                                          
Error: m4b-tool: SHA256 mismatch
Expected: 2b37a9300b2cba9bb54cf49e2fec7d46b527c4f73f5ca401bc79c9426152f061
  Actual: 09e5342d1f19523641ce3c3ea7e8a7158af54b731dde7c595e5e11231c9f59fc
    File: /Users/frl/Library/Caches/Homebrew/downloads/ba4b9f24c9abc855b34ac70dc60f5eba7e94b3384170ca29d825de69ee0809b0--sandreas-mp4v2-Release-ThirdParty-MP4v2-4.1.0.0-67-g480a733.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by sandreas** [comment]
Please retry, should be fixed. 

Reason was fetch from upstream mp4v2 with updating the hash.

**Comment by fabianlischka** [comment]
Installed without a hitch now and works. Can be closed, I think. Thanks!
