### ISSUE TITLE
Regression with `--musicbrainz-id`

### ISSUE THREAD

**Issue by apetresc** [sandreas/m4b-tool#174]
I'd previously been using the latest stable release, and in those fortunate situations where I could find a musicbrainz.org ID for a book, it would basically always work without issue. However, I just built a docker image using the latest [6598116](https://github.com/sandreas/m4b-tool/files/6598116/m4b-tool.tar.gz) prerelease build and suddenly `--musicbrainz-id` seems broken even for releases that I had previously used successfully with v0.4.2.

Attached below is a log that shows me attempting to associate a merge with [this release](https://musicbrainz.org/release/86eab68d-15d2-44bf-84bb-c13d4e57816e) (it merges fine with v0.4.2 with an identical call and parameterization). I'm not sure if this is a straight-up regression, or maybe the semantics of the flag have somehow changed in a way that I'm not expecting. Either way, I'd appreciate some help since I'd like to stay up-to-date with the newest version in my workflow 😄 Thanks!

[out.log](https://github.com/sandreas/m4b-tool/files/8085161/out.log)

There's nothing in the logs that indicates an explicit failure in the mb-id matching; it just glosses over the "ChaptersFromMusicBrainz improver" without any consideration at all, seemingly.

**Comment by sandreas** [comment]
This maybe an issue, i did not test musicbrainz for a longer time - but I'll take a look.
