### ISSUE TITLE
docker build errors on ubuntu

### ISSUE THREAD

**Issue by myrison** [sandreas/m4b-tool#176]
Thank you for maintaining this repo & tool.

After I clone the repository and attempt to build the docker file (whether using the pre-release or the latest release), I get the following errors:

_All previous steps in logs ok to this point..._
`checking if GCC precompiled-headers should be created... yes
checking arch flags... none
configure: creating ./config.status
config.status: creating GNUmakefile
config.status: creating include/mp4v2/project.h
config.status: creating project/project.m4
config.status: creating libplatform/config.h
config.status: libplatform/config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing libtool commands`
**Errors / warnings begin here** 

`doc/GNUmakefile.mk:207: target 'doc/articles/html/Authors.html' given more than once in the same rule
doc/GNUmakefile.mk:207: target 'doc/articles/html/BuildRepository.html' given more than once in the same rule
doc/GNUmakefile.mk:207: target 'doc/articles/html/BuildSource.html' given more than once in the same rule
doc/GNUmakefile.mk:207: target 'doc/articles/html/Documentation.html' given more than once in the same rule
doc/GNUmakefile.mk:207: target 'doc/articles/html/ReleaseNotes.html' given more than once in the same rule
doc/GNUmakefile.mk:207: target 'doc/articles/html/ToolGuide.html' given more than once in the same rule
doc/GNUmakefile.mk:211: target 'doc/articles/txt/Authors.txt' given more than once in the same rule
doc/GNUmakefile.mk:211: target 'doc/articles/txt/BuildRepository.txt' given more than once in the same rule
doc/GNUmakefile.mk:211: target 'doc/articles/txt/BuildSource.txt' given more than once in the same rule
doc/GNUmakefile.mk:211: target 'doc/articles/txt/Documentation.txt' given more than once in the same rule
doc/GNUmakefile.mk:211: target 'doc/articles/txt/ReleaseNotes.txt' given more than once in the same rule
doc/GNUmakefile.mk:211: target 'doc/articles/txt/ToolGuide.txt' given more than once in the same rule
doc/GNUmakefile.mk:215: target 'doc/articles/xml/Authors.xml' given more than once in the same rule
doc/GNUmakefile.mk:215: target 'doc/articles/xml/BuildRepository.xml' given more than once in the same rule
doc/GNUmakefile.mk:215: target 'doc/articles/xml/BuildSource.xml' given more than once in the same rule
doc/GNUmakefile.mk:215: target 'doc/articles/xml/Documentation.xml' given more than once in the same rule
doc/GNUmakefile.mk:215: target 'doc/articles/xml/ReleaseNotes.xml' given more than once in the same rule
doc/GNUmakefile.mk:215: target 'doc/articles/xml/ToolGuide.xml' given more than once in the same rule
doc/GNUmakefile.mk:219: target 'doc/articles/wiki/Authors.wiki' given more than once in the same rule
doc/GNUmakefile.mk:219: target 'doc/articles/wiki/BuildRepository.wiki' given more than once in the same rule
doc/GNUmakefile.mk:219: target 'doc/articles/wiki/BuildSource.wiki' given more than once in the same rule
doc/GNUmakefile.mk:219: target 'doc/articles/wiki/Documentation.wiki' given more than once in the same rule
doc/GNUmakefile.mk:219: target 'doc/articles/wiki/ReleaseNotes.wiki' given more than once in the same rule
doc/GNUmakefile.mk:219: target 'doc/articles/wiki/ToolGuide.wiki' given more than once in the same rule
doc/GNUmakefile.mk:258: target 'doc/site/Authors.html' given more than once in the same rule
doc/GNUmakefile.mk:258: target 'doc/site/BuildRepository.html' given more than once in the same rule
doc/GNUmakefile.mk:258: target 'doc/site/BuildSource.html' given more than once in the same rule
doc/GNUmakefile.mk:258: target 'doc/site/ReleaseNotes.html' given more than once in the same rule
doc/GNUmakefile.mk:258: target 'doc/site/ToolGuide.html' given more than once in the same rule
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /tmp/mp4v2-master/autoaux/missing --run aclocal-1.11
make: /bin/sh: Operation not permitted
make: *** [GNUmakefile:629: aclocal.m4] Error 127
The command '/bin/sh -c echo "---- INSTALL BUILD DEPENDENCIES ----"     && apk add --no-cache --update --upgrade --virtual=build-dependencies     autoconf     libtool     automake     boost-dev     build-base     gcc     git     tar     wget && echo "---- COMPILE SANDREAS MP4V2 (for sort-title, sort-album and sort-author) ----"   && cd /tmp/   && wget https://github.com/sandreas/mp4v2/archive/master.zip   && unzip master.zip   && cd mp4v2-master   && ./configure &&   make -j4 &&   make install && make distclean && echo "---- PREPARE FDKAAC-DEPENDENCIES ----"   && cd /tmp/   && wget -O fdk-aac.tar.gz "$FDK_AAC_URL"   && tar xfz fdk-aac.tar.gz   && cd fdk-aac-* && ./autogen.sh && ./configure --enable-static --disable-shared && make -j$(nproc) install && echo "---- COMPILE FDKAAC ENCODER (executable binary for usage of --audio-profile) ----"     && cd /tmp/     && wget https://github.com/nu774/fdkaac/archive/1.0.0.tar.gz     && tar xzf 1.0.0.tar.gz     && cd fdkaac-1.0.0     && autoreconf -i && ./configure --enable-static --disable-shared && make -j4 && make install && rm -rf /tmp/* && echo "---- REMOVE BUILD DEPENDENCIES (to keep image small) ----"     && apk del --purge build-dependencies && rm -rf /tmp/*' returned a non-zero code: 2`

Because it mentions a 'not permitted' error in the middle I tried the build with and without sudo, but with no change.  If I can provide more information to help troubleshoot, please let me know.

Thank you for reviewing when you have time.

**Comment by sandreas** [comment]
Thank you for reporting this. Compiling `mp4v2` seems to fail, maybe because I merged upstream a few weeks ago. Since the `mp4v2` project is a *maintainers nightmare* (nobody wanted to REALLY maintain it for a long time), I'm thinking about switching from https://github.com/TechSmith/mp4v2 to https://github.com/enzo1982/mp4v2. 

He promised to maintain and merge pull requests in a more frequent way, but it is a long way to a fully maintained project. I only have this project online to support `sort-name` tags, because these parameters were not in the main repo.

I'll take a look and see if I can change the `Dockerfile` to a fixed tag again.

**Comment by sandreas** [comment]
This should be fixed. Can you retry?

**Comment by sandreas** [comment]
Closing due to no further feedback. Feel free to reopen...
