### ISSUE TITLE
Need help understanding error

### ISSUE THREAD

**Issue by flintstones-fred** [sandreas/m4b-tool#177]
I am getting the following error when I try to merge a folder containing mp3 files. 

`PHP Warning:  mkdir(): Permission denied in phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/MergeCommand.php on line 748

Could not create temp directory /home/user/Downloads/audiobook-tmpfiles/
an error occured, that has not been caught:
Array
(
    [type] => 2
    [message] => mkdir(): Permission denied
    [file] => phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/MergeCommand.php
    [line] => 748
)`

Can someone help me? I have installed m4b-tool using the docker instructions provided in the wiki. Any my output for "m4b-tool --version" command returns v.0.4.2

**Comment by sandreas** [comment]
Could you please provide the full command you tried to execute?

**Comment by flintstones-fred** [comment]
> Could you please provide the full command you tried to execute?
> 
> `docker run ...`

Thanks for the response. Let me explain my process for trying to get this working -
First, I installed the m4b-tool based on your instructions (with a slight change in the build step where I had to use sudo as docker explained that I don't have permissions. 

clone m4b-tool repository
git clone https://github.com/sandreas/m4b-tool.git

change directory
cd m4b-tool

build docker image - this will take a while
sudo docker build . -t m4b-tool

create an alias for m4b-tool running docker
alias m4b-tool='docker run -it --rm -u $(id -u):$(id -g) -v "$(pwd)":/mnt m4b-tool'

testing the command
m4b-tool --version

At this stage, I get the output as expected (v.0.4.2)

Then my next command was 
`m4b-tool merge audiobook/ --output-file="/home/user/Downloads/audiobook.m4b` 

This is where I get the error described above.

**Comment by sandreas** [comment]
```
 m4b-tool merge audiobook/ --output-file="/home/user/Downloads/audiobook.m4b
```
So here is the problem. Citing the docs:

> Note: If you use the alias above, keep in mind that you cannot use absolute paths (e.g. /tmp/data/audiobooks/harry potter 1) or symlinks. You must change into the directory and use relative paths (e.g. cd /tmp/data && m4b-tool merge "audiobooks/harry potter 1" --output-file harry.m4b)

You have to use relative paths without parent traversing (`../` does not work!) because they are mounted into the docker image. The docker image does not contain a path like `/home/user/Downloads/`, because it is only on your machine.

```
m4b-tool merge audiobook/ --output-file="audiobook.m4b"
```
should work.

**Comment by flintstones-fred** [comment]
> ```
>  m4b-tool merge audiobook/ --output-file="/home/user/Downloads/audiobook.m4b
> ```
> 
> So here is the problem. Citing the docs:
> 
> > Note: If you use the alias above, keep in mind that you cannot use absolute paths (e.g. /tmp/data/audiobooks/harry potter 1) or symlinks. You must change into the directory and use relative paths (e.g. cd /tmp/data && m4b-tool merge "audiobooks/harry potter 1" --output-file harry.m4b)
> 
> You have to use relative paths without parent traversing (`../` does not work!) because they are mounted into the docker image. The docker image does not contain a path like `/home/user/Downloads/`, because it is only on your machine.
> 
> ```
> m4b-tool merge audiobook/ --output-file="audiobook.m4b"
> ```
> 
> should work.

Thank you for your help! This worked. I am going to close the issue.
