### ISSUE TITLE
Setting alias getting a ":$(id was unexpected at this time." error

### ISSUE THREAD

**Issue by SaiKDot** [sandreas/m4b-tool#181]
After running the   `docker build . -t m4b-tool` command successfully, I tried to run 

`alias m4b-tool='docker run -it --rm -u $(id -u):$(id -g) -v "$(pwd)":/mnt m4b-tool'`
 as said in  the instructions. But when I do, I'm getting the error '`:$(id was unexpected at this time`'

**Comment by sandreas** [comment]
Which OS? If it is Windows, it won't work like this. 

Otherwise, you could also use `alias m4b-tool='docker run -it --rm -u <your-custom-uid>:<your-custom-gid> -v "$(pwd)":/mnt m4b-tool'`, most of the time this will be:

```bash
alias m4b-tool='docker run -it --rm -u 1000:1000 -v "$(pwd)":/mnt m4b-tool'
```

on a Linux system with one main user.

**Comment by SaiKDot** [comment]
I'm on windows

**Comment by sandreas** [comment]
Mmh, maybe this helps:

- try running the commands `id -u` and `id -g`
- if they dump numbers, replace `$(id -u)` and `$(id -g)` with this numbers (like I said above, on Linux by default it is `1000:1000`.
- if they don't dump anything or if there is an error, try to remove `-u ...` completely
- create a `m4b-tool.bat` in `C:/windows` (or somewhere else in your `%Path%`)
- put the command in this batch file:

Without `-u`
```
docker run -it --rm -v "%cd%":/mnt m4b-tool
```

I'll have to check that, I never worked with `m4b-tool` on Windows with `docker`.

**Comment by sandreas** [comment]
So create a bat file `m4b-tool.bat` in `C:\Windows` (or any other path in the `%Path%` environment variables) with the following contents:

```
@echo off
docker run -it --rm -v "%cd%":/mnt m4b-tool %*
```

This should work.
