### ISSUE TITLE
Cannot install custom mp4v2

### ISSUE THREAD

**Issue by trustosas** [sandreas/m4b-tool#182]
Command:
#install-custom-mp4v2
!git clone https://github.com/sandreas/mp4v2
!cd mp4v2
!./configure
!make && sudo make install

Error:
Cloning into 'mp4v2'...
remote: Enumerating objects: 1346, done.
remote: Counting objects: 100% (152/152), done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 1346 (delta 73), reused 137 (delta 69), pack-reused 1194
Receiving objects: 100% (1346/1346), 44.48 MiB | 13.34 MiB/s, done.
Resolving deltas: 100% (621/621), done.
/bin/bash: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop

**Comment by sandreas** [comment]
Please migrate to https://github.com/enzo1982/mp4v2/ with the latest pre-release, it is the official maintained fork.
