### ISSUE TITLE
Unable to add newlines in --comment option/field with the merge command: returns only '\n'

### ISSUE THREAD

**Issue by trustosas** [sandreas/m4b-tool#184]
I want to add newlines to my comment option in merge command. However when I've written to the file all I see is '\n' instead of line break. What is going wrong here:

Sample:
(It's pretty long, but focus on the comment section)
m4b-tool merge --name=I'Joy on Demand' --sortname='Joy on Demand' --album='Joy on Demand: The Art of Discovering the Happiness Within' --sortalbum='null' --artist='Chade-Meng Tan' --genre='Business & Careers, Career Success, Career Success, Meditation, Psychology, Personal Success' --writer='Chade-Meng Tan' --albumartist='Telly Leung' --year='2016-05-31' --comment="A long-awaited follow-up to the New York Times best-selling Search Inside Yourself shows us how to cultivate joy within the context of our fast-paced lives and explains why it is critical to creativity, innovation, confidence, and ultimately success in every arena. \n\nIn Joy on Demand, Chade-Meng Tan shows that you don\'t need to meditate for hours, days, months, or years to achieve lasting joy - you can actually get consistent access to it in as little as 15 seconds. Explaining joy and meditation as complementary things that naturally reinforce each other, Meng explains how these two skills form a virtuous cycle and, once put into motion, become a solid practice that can be sustained in daily life. \n\nFor many years, meditation has been taught and practiced in cultures where almost all meditators practice full-time for years, resulting in training programs optimized for practitioners with lots of free time and not much else to do but develop profound mastery over the mind. Seeing a disconnect between the traditional practice and the modern world, the best-selling author and Google\'s \"Jolly Good Fellow\" has developed a program, through \"wise laziness\", to help listeners meditate more efficiently and effectively. Meng shares the three pillars of joy (inner peace, insight, and happiness) and why joy is the secret is to success and demonstrates the practical tools anyone can use to cultivate it on demand. '" --copyright='© HarperAudio' --series=0 --series-part='null' --audio-format='m4b' --output-file='/content/drive/MyDrive/output/Joy on Demand.m4a' '/content/drive/MyDrive/input/' -v --jobs=2

Output:
A long-awaited follow-up to the New York Times best-selling Search Inside Yourself shows us how to cultivate joy within the context of our fast-paced lives and explains why it is critical to creativity, innovation, confidence, and ultimately success in every arena. \n\nIn Joy on Demand, Chade-Meng Tan shows that you don't need to meditate for hours, days, months, or years to achieve lasting joy - you can actually get consistent access to it in as little as 15 seconds. Explaining joy and meditation as complementary things that naturally reinforce each other, Meng explains how these two skills form a virtuous cycle and, once put into motion, become a solid practice that can be sustained in daily life. \n\nFor many years, meditation has been taught and practiced in cultures where almost all meditators practice full-time for years, resulting in training programs optimized for practitioners with lots of free time and not much else to do but develop profound mastery over the mind. Seeing a disconnect between the traditional practice and the modern world, the best-selling author and Google's "Jolly Good Fellow" has developed a program, through "wise laziness", to help listeners meditate more efficiently and effectively. Meng shares the three pillars of joy (inner peace, insight, and happiness) and why joy is the secret is to success and demonstrates the practical tools anyone can use to cultivate it on demand.

**Comment by trustosas** [comment]
Problem lied with my code. Avoiding errors like this can be done by adding the $ sign in front of the comment string, and ensuring the string is a single quote string, not double quotes

**Comment by sandreas** [comment]
Good add, glad that it is fixed for you and not an `m4b-tool` issue. Thanks :-)
