### ISSUE TITLE
Update and document the new official docker image

### ISSUE THREAD

**Issue by sandreas** [sandreas/m4b-tool#187]
Todo: 
- [x] Bump `tone` version in https://github.com/sandreas/dockerhub-builds/tree/main/m4b-tool/latest
- [x] Test and upload new latest pre-release (with workaround for tone being removed)
- [x] Manually update the latest official `m4b-tool` docker image
- [x] Update `Dockerfile` in `m4b-tool` repository
- [ ] Publish anouncement (see below)

There is a new "official" (still experimental) docker multiarch image and SHOULD work on x64, and Raspberry platforms. It is completely handcrafted and available for the following archs:

- linux/arm/v6
- linux/arm/v7
- linux/arm64
- linux/amd64

```bash
# latest tag (usually stable, but sometimes there is a problem)
docker pull sandreas/m4b-tool:latest

# dated tag - considered as stable without major bugs
docker pull sandreas/m4b-tool:2022-09-25
```

Every now and then I will publish a dated tag (e.g. `sandreas/m4b-tool:2022-09-25`), that I personally consider as *pretty* stable. That is to ensure a broken `latest` image will not break your whole setup. You can pull all images on dockerhub:

- https://hub.docker.com/repository/docker/sandreas/m4b-tool/tags?page=1&ordering=name

In the (far) future, it will use tagging based on my new project [tone](https://github.com/sandreas/tone), which SHOULD be a huge improvement over the existing mp4v2 and ffmpeg strategies.

I need your help: Try out the new docker image and give feedback, so that we can get to a production ready release as soon as possible.

**Comment by alsack** [comment]
See issue I'm experiencing with the new docker image: https://github.com/sandreas/m4b-tool/issues/197

**Comment by sandreas** [comment]
done, announcement no longer necessary since it is already in readme.md
