### ISSUE TITLE
Issue with the split command

### ISSUE THREAD

**Issue by MituButChi** [sandreas/m4b-tool#189]
Hi, it's me again from #188.
I've successfully pulled the docker image (it was sooooo easy. I wish I had known about it sooner, I would have saved so much time trying to manually install the tool).

Now I have one problem. As far as I understand, the `split` command is supposed to split the .m4b file by chapters right?

I used exactly the command you sent me yesterday, I only changed the \ to the /:

```
# split audio book C:\Users\MituButChi\audiobooks_to_split\my-audio-book.m4b
docker run -it --rm -v "C:/Users/MituButChi/":/mnt sandreas/m4b-tool:latest split --audio-format mp3 --audio-bitrate 96k --audio-channels 1 --audio-samplerate 22050 "audiobooks_to_split/my-audio-book.m4b"
```

The .m4b file has 18 chapters, in both QuickTime and Nero tags. But the tool split it into 124 files with different duration, from 5s to 15m long.
This is the same problem as yesterday's. But yesterday I thought it might be because I didn't install the tool correctly. So please help on this one.

Thank you! Hope you're having a nice weekend.

**Comment by sandreas** [comment]
> The .m4b file has 18 chapters, in both QuickTime and Nero tags. But the tool split it into 124 files with different duration, from 5s to 15m long.

Are you sure on that? Please run:

```bash
docker run -it --rm -v "C:/Users/MituButChi/":/mnt sandreas/m4b-tool:latest meta "audiobooks_to_split/my-audio-book.m4b"
```

This dumps the chapters and should look something like this:

```
... more stuff...

chapters         
## total-duration:: 00:21:29.000
00:00:00.000 01 - A Christmas Of Long Ago (1906)
00:07:17.835 02 - Lou's Clarionet (1896)

... more stuff...
```

**Comment by MituButChi** [comment]
> Like I said, docker is the way to go for `m4b-tool`. Maybe I can improve that in the new project `tone`.
Absolutely. I didn't know what docker was so I didn't understand anything in the instruction, it was like walking through a dark forest haha. It's worth learning though, now I believe I could use more stuff from GitHub.

Can't wait to use `tone` from you.
---
Yes I'm sure. Because I merged the file myself, from 18 mp3 files. I used it to test the tool.
Also, I ran it through `Mediainfo` before I split it. It has 2 Menus with the 2 different kinds of tags.

I just used m4b-tool to check again. Yes, it definitely has 18 chapters.

**Comment by sandreas** [comment]
Mh maybe you can use a workaround:

```
      --use-existing-chapters-file               use an existing manually edited chapters file <audiobook-name>.chapters.txt instead of embedded chapters for splitting
```

Use the `meta` command to dump your chapters, then create a `<yourfile>.chapters.txt` beneath `<yourfile>.m4b` and fill up the contents with the dump. Then use `--use-existing-chapters-file` for the split... hopefully it will work. 

But I think the `split` command could be buggy... maybe it is time to fix this ;)

**Comment by MituButChi** [comment]
Just tried, didn't work 😢 

I tried with both versions of the file:

```
chapters
duration: [...]
00:00:00.000 Chapter 1
00:18:31.926 Chapter 2
00:39:36.345 Chapter 3
```

and 

```
00:00:00.000 Chapter 1
00:18:31.926 Chapter 2
00:39:36.345 Chapter 3
```

neither worked 😞 

I mostly need the `merge` command so it's good for now. Let me know when it's fixed though. Thank you.

**Comment by sandreas** [comment]
> I mostly need the merge command so it's good for now. Let me know when it's fixed though. Thank you.

Yeah I try to reproduce this first... I'll let you know. Thanks for reporting back.

**Comment by MituButChi** [comment]
One more question, I can't use the `mp4chaps` command with docker on Windows.
I tried:

```
docker run -it --rm -v "C:/audiobooks/":/mnt sandreas/m4b-tool:latest mp4chaps -i "filename.m4b"
```
It says
> Command mp4chaps is not defined.

**Comment by sandreas** [comment]
NO forward slash, relative paths: https://github.com/sandreas/m4b-tool#docker
```
docker run -it --rm -v "C:/audiobooks/":/mnt sandreas/m4b-tool:latest merge "input" --output-file="output/merged.m4b"
```

You have to provide an `--entrypoint`...
```
docker run --entrypoint mp4chaps -it --rm -v "C:/audiobooks/":/mnt sandreas/m4b-tool:latest -i "filename.m4b"
```

I strongly recommend you to read some documentation and UNDERSTAND what you are doing - not just trying to get it working... :-)

**Comment by MituButChi** [comment]
Thank you. It works beautifully now.

Looks like I've bothered you with dumb questions. Sorry for that :D
Trust me I tried. I read the documentation but it's not easy for me to understand. Putting everything to the test actually helps me to understand it better and faster.

Thank you for your time. I really appreciate it.

**Comment by sandreas** [comment]
> Thank you for your time. I really appreciate it.

You're welcome, glad it works now :-)
