### ISSUE TITLE
--batch-pattern not being accepted

### ISSUE THREAD

**Issue by Dekker500** [sandreas/m4b-tool#190]
Using the latest docker image, built, and created alias. m4b-tool latest-168-gb154c85
Ubuntu 22.04.

This worked in the past (with NON docker image), however something has changed in the last 6 months (OS upgrade, and m4b-tool upgrade) and I cannot tell how to resolve it... Tried manual compile, and finally docker, and had different blocking problems on each.

I have the following folder structure:
```
Home
|-Converted
|-Queue
  |-Book 1
    |-1.mp3
    |-2.mp3
    |-x.mp3
  |-Book 2
    |-1.mp3
    |-2.mp3
    |-x.mp3
```
I am trying to end up with my m4b output files in Converted. Should have Book 1.m4b and Book 2.m4b. As I mentioned, this used to work.

I am issuing this command, and getting the following error:

```
$m4b-tool merge --audio-codec="libfdk_aac" --audio-bitrate="256k" --jobs="2" --fix-mime-type --output-file="./Converted/" --batch-pattern="./Queue/%n/"  "./Queue/" -vvv

The use of --batch-pattern assumes that exactly one directory is processed - please provide a valid and existing directory
trace: #0 phar:///usr/local/bin/m4b-tool/src/library/Command/MergeCommand.php(171): M4bTool\Command\MergeCommand->ensureValidInputForBatchMode()
#1 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Command/Command.php(255): M4bTool\Command\MergeCommand->execute()
#2 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#3 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#4 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#5 phar:///usr/local/bin/m4b-tool/bin/m4b-tool.php(47): Symfony\Component\Console\Application->run()
#6 /usr/local/bin/m4b-tool(10): require('...')
#7 {main}
```

I can see that MergeCommand.php:210 is throwing the exception when input files is > 0 OR if input is not a folder... but neither should be true! In my case, the input folder TWO sub-folders, each with numerous mp3 files.

Thoughts? Ideas?

**Comment by sandreas** [comment]
I tried to reproduce this in the exact way, you described it... I even copied the files to the same place and ran exactly your command without modification and it worked for me...

The only way this error message can happen I could think of is, that the input directory `./Queue/` does not exist. If I move `./Queue/` to e.g. `./Queue2/`, the exact error message you describe comes up.

So if you go to the directory, you run the command in and type `ls ./Queue/`, it should fail. Maybe there is a case sensitivity problem? (`./queue/` vs `./Queue`)?

**Comment by Dekker500** [comment]
Finally got around to trying again, and I think I found the problem and the (very simple) solution.

This is my first foray into the docker world, but I think the problem goes beyond docker's limitation with relative paths. It seems to have problems with permissions!

My media files are in a VirtualBox share. The files are owned by root, but with a common "group" to which my user is a member. I believe the docker thread does not share my user's group permissions, and hence cannot "see" the folder!

I simply copied my media folders to a location under my "home" folder, repeated the exact command, and everything worked!

So this issue can be marked as "resolved", however I recommend you add a note to the documentation that the input/output folders/files should have USER level permissions, not just GROUP level permissions... That might

**Comment by sandreas** [comment]
> So this issue can be marked as "resolved", however I recommend you add a note to the documentation that the input/output folders/files should have USER level permissions, not just GROUP level permissions... That might help some other unsuspecting users!

I'll think over this...
