### ISSUE TITLE
Question: How to reduce filesizes of the output m4b files

### ISSUE THREAD

**Issue by trustosas** [sandreas/m4b-tool#194]
m4b-tool works fine for merging mp3(s) to a single m4b. However, the m4b is normally twice as large as the source mp3. In encoding to AAC, why does this almost doubling of filesize happen? I thought AAC was more space efficient than MP3, so why the weird bump in filesize? Is there some settings I need to tweak?

**Comment by sandreas** [comment]
There are several things you can do, but almost certainly you did not specify the `--audio-bitrate` parameter. So if you got a 96kbps mp3 and use the default setting of 128kbps for `m4b`, its not surprising, that your files are larger.

Please post the complete command you are using and which version of `m4b-tool`...

**Comment by trustosas** [comment]
m4b-tool v.0.4.2

m4b-tool merge --name='The Subtle Art of Not Giving a F*ck' --sortname='The Subtle Art of Not Giving a F*ck' --album='The Subtle Art of Not Giving a F*ck: A Counterintuitive Approach to Living a Good Life' --sortalbum='null' --artist='Mark Manson' --genre='Relationships, Parenting & Personal Development, Personal Development, Personal Success' --writer='Mark Manson' --albumartist='Roger Wayne' --year='2016-09-13' --comment=$'In this generation-defining self-help guide, a superstar blogger cuts through the crap to show us how to stop trying to be positive all the time so that we can truly become better, happier people.\n\nFor decades we\'ve been told that positive thinking is the key to a happy, rich life. "F*ck positivity," Mark Manson says. "Let\'s be honest, shit is f*cked, and we have to live with it." In his wildly popular Internet blog, Manson doesn\'t sugarcoat or equivocate. He tells it like it is - a dose of raw, refreshing, honest truth that is sorely lacking today. The Subtle Art of Not Giving a F*ck is his antidote to the coddling, let\'s-all-feel-good mind-set that has infected modern society and spoiled a generation, rewarding them with gold medals just for showing up.\n\nManson makes the argument, backed by both academic research and well-timed poop jokes, that improving our lives hinges not on our ability to turn lemons into lemonade but on learning to stomach lemons better. Human beings are flawed and limited - "not everybody can be extraordinary; there are winners and losers in society, and some of it is not fair or your fault". Manson advises us to get to know our limitations and accept them. Once we embrace our fears, faults, and uncertainties, once we stop running and avoiding and start confronting painful truths, we can begin to find the courage, perseverance, honesty, responsibility, curiosity, and forgiveness we seek.\n\nThere are only so many things we can give a f*ck about, so we need to figure out which ones really matter, Manson makes clear. While money is nice, caring about what you do with your life is better, because true wealth is about experience. A much-needed grab-you-by-the-shoulders-and-look-you-in-the-eye moment of real talk, filled with entertaining stories and profane, ruthless humor, The Subtle Art of Not Giving a F*ck is a refreshing slap for a generation to help them lead contented, grounded lives.' --copyright='©2016 Mark Manson' --series=0 --series-part='null' --audio-format='m4b' --output-file='/content/drive/MyDrive/output/The Subtle Art of Not Giving a F*ck.m4b' '/content/drive/MyDrive/input/' -v --jobs=2

**Comment by trustosas** [comment]
Why doesn't m4b-tool encode by default at the bitrate of the source file?

**Comment by sandreas** [comment]
> m4b-tool v.0.4.2

I would recommend upgrading to the latest pre-release. The latest stable is very very old, but I did not manage to publish a new stable release yet. The pre-release is pretty stable, I use it on a daily basis...

> `m4b-tool merge --name ...`

Phew, this is one impressive command :-) Some comments:

- In my opinion `--sortalbum='null'` whill not result in removing or unsetting sortalbum, but setting it to the string `null`... same for `--series` and `--series-part`
- In your case, you should be able to reduce size significantly using `--audio-bitrate=64k  --audio-samplerate=22050 --audio-channels=1`

> Why doesn't m4b-tool encode by default at the bitrate of the source file?

Its hard to detect and most of the time not a good idea. In your case I would assume the `mp3` files have `96k` or even more. The `m4b` uses aac, which will sound similar using only `64k`... Using `opus` you could even go lower with `48k` or less. So using some "auto" setting would basically mean adding sample configs for each possible case, which would be a lot of work... I think the latest pre-release uses 64k for `m4b` as default setting, but I still prefer providing a parameter.

**Comment by trustosas** [comment]
Is it ok for me to leave this open until I can verify that the suggestion works?

**Comment by sandreas** [comment]
> Is it ok for me to leave this open until I can verify that the suggestion works? (It may take a while because at the moment I'm not acquiring books and I've deleted source files for more storage)

I would say we close this and you reopen if something does not work... It's no shame for me to reopen a ticket ;)
