### ISSUE TITLE
Directly copy audio input into output (mp3 to m4b) (Overdrive)

### ISSUE THREAD

**Issue by elin1023** [sandreas/m4b-tool#208]
# Issue
Hi! I am trying to convert a bunch of mp3 files downloaded from Overdrive into an m4b file, with proper chapters marked in the m4b file. The audio should be directly copied from the mp3 files into the m4b file to reduce loss in quality. 

**Issue**: Is it possible to add a m4b-tool merge argument that directly copies the audio stream from the mp3 files to m4b file?

OS: Windows 10

m4b-tool version: [https://github.com/sandreas/m4b-tool/files/9721007/m4b-tool.tar.gz](url)
PHP version: PHP 8.2.0 (cli)
ffmpeg version: ffmpeg version N-106528-g4fbf3c828b-sherpya
mp4 chaps version: mp4chaps - MP4v2 2.0-r477

I have tried adding ffmpeg parameters and this seems to partially work. 
Command used:
`php m4b-tool.phar merge -vvv --ffmpeg-threads=20 --jobs=17 --album="Jade City - Green Bone Saga, Book 1" --series="Green Bone Saga" --series-part=1 --writer="Fonda Lee" --ffmpeg-param="-c:a" --ffmpeg-param="copy" --ffmpeg-param="-metadata" --ffmpeg-param="title=Jade City" "F:/Audiobooks/The Green Bone Saga 01 - Jade City/" --output-file="F:/Audiobooks/Jade City4.m4b"`

However, the command used for ffmpeg when converting ended up being this:
`ffmpeg -nostats -loglevel panic -hide_banner -i "F:/Audiobooks/The Green Bone Saga 01 - Jade City\Jade City-Part01.mp3" -map_metadata 0 -max_muxing_queue_size 9999 -strict experimental -movflags +faststart -vn -ab 64k -ar 22050 -ac 0 -acodec aac -f mp4 -c:a copy -metadata "title=Jade City" -threads 20 "F:/Audiobooks\Jade City4-tmpfiles\01-converting.m4b"`

With the -ab, -ar, -ac, -acodec still being set. May I check if this will affect the final m4b output?

Log file from running the command:
[log-jadecity4.txt](https://github.com/sandreas/m4b-tool/files/10201770/log-jadecity4.txt)

There also seems to be a bunch of deprecated PHP warnings in the log file above, I hope they don't affect anything.

# Reasoning
I want to directly copy the audio streams because using the quality seems to be better without increasing file size.

I have tried running it without setting any audio settings and using the default, but there is a very noticeable loss in quality, there was a higher pitched crackling sound throughout. 
Command:
`php m4b-tool.phar merge -vvv "F:/Audiobooks/The Green Bone Saga 01 - Jade City/" --output-file="F:/Audiobooks/Jade City.m4b"`
MediaInfo of output m4b file:
```
Audio
ID                                       : 1
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 19 h 7 min
Bit rate mode                            : Variable
Bit rate                                 : 63.7 kb/s
Maximum bit rate                         : 4 084 Mb/s / 63.7 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 22.05 kHz
Frame rate                               : 21.533 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 523 MiB (99%)
Default                                  : Yes
Alternate group                          : 1
Menus                                    : 2
```
MediaInfo of original mp3 file (part 1 only, since Overdrive has a bunch of mp3 files in parts):
```
Audio
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Format settings                          : Joint stereo
Duration                                 : 1 h 10 min
Bit rate mode                            : Constant
Bit rate                                 : 64.0 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 kHz
Frame rate                               : 38.281 FPS (1152 SPF)
Compression mode                         : Lossy
Stream size                              : 32.4 MiB (100%)
Writing library                          : LAMEUUULAME3.91
Language                                 : English
```

As seen from comparing the 2 MediaInfo output above, the sampling rate dropped from 44.1kHz to 22.05kHz if it is not explicitly set.

If I set the sampling rate myself in the m4b-tool command, then the file size of the m4b will double to 1.04GB, even though the original folder of mp3 files from Overdrive sum up to 525 MB. But at least the crackling sound is not there.
Command used:
`php m4b-tool.phar merge -vvv --ffmpeg-threads=17 --jobs=17 --series="Green Bone Saga" --series-part=1 --writer="Fonda Lee" --audio-samplerate=44100 --ffmpeg-param="-metadata" --ffmpeg-param="title='Jade City'" "F:/Audiobooks/The Green Bone Saga 01 - Jade City/" --output-file="F:/Audiobooks/Jade City2.m4b"`
MediaInfo of the resulting m4b file (Jade City2.m4b):
```
Audio
ID                                       : 1
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 19 h 7 min
Bit rate mode                            : Variable
Bit rate                                 : 129 kb/s
Maximum bit rate                         : 1 718 Mb/s / 129 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 1.03 GiB (99%)
Default                                  : Yes
Alternate group                          : 1
Menus                                    : 2
```

Thank you!

**Comment by sandreas** [comment]
Phew. Thank you for your detailed issue report. Since I do not know, how your background knowledge about audio codecs is, pardon me if my explanation is simplified...

Let's try to summarize, what you are trying to do:
- Convert a bunch of `mp3` (lossy mp3 codec, 64kbps) files into one single `m4b` (lossy aac codec)

So let's see, what I can say about this:
- The original files (`mp3`, 64kbps) are really low quality in my opinion - this is a bad starting point
- To have a valid `m4b` file, the files **MUST** be re-encoded with `aac` or `alac` codec using these low quality (you can't *simply copy audio streams*, because `mp3` already is lossy and you can't re-insert this lost information)
- If you do not want to re-encode these files, you will not get a valid `m4b`, because you can't stuff `mp3` codec into `m4b` in a valid way (you can force this with `--no-conversion`, but this will result in an invalid file - VLC will play it but it is not a valid file)
-  The required re-encoding step will reduce quality, even if you use `128kpbs` / `48100` sampling rate, because `aac` is also a lossy codec - the lower the destination quality, the more audio information is lost
- `m4b-tool` tries to use *sane defaults* for resulting `m4b` files, which are 64kbps, 22050hz
So in my opinion the crackling and noise is coming from the original files when trying to use a low quality setting for `aac`. I take this question very serious and maybe I'm wrong, but I think it is not possible to convert these files into a small and good sounding `m4b`.

Here are some things you could try to get small files with better quality:

-  1 channel is less audio information
- 64k is enough bitrate for audio books
- samplerate of 22050 is enough
- codec is libfdk_aac (better quality)
- `audio-profile=aac_he` - internally use `fdkaac` which is higher audio quality (`fdkaac` must be installed though)

```bash
 --audio-channels=1 --audio-bitrate=64k --audio-samplerate=22050 --audio-codec=libfdk_aac --audio-profile=aac_he 
```

I hope this answers your question :-)

**Comment by elin1023** [comment]
Thanks for the reply! I don't have any background knowledge in audio codecs.

If the original mp3 is already low quality, won't re-encoding it to aac reduce the quality even more? Since the quality won't increase no matter what if re-encoding.
I was able to get a playable m4b file with the command: 
`php m4b-tool.phar merge -vvv --ffmpeg-threads=20 --jobs=17 --album="Jade City - Green Bone Saga, Book 1" --series="Green Bone Saga" --series-part=1 --writer="Fonda Lee" --ffmpeg-param="-c:a" --ffmpeg-param="copy" --ffmpeg-param="-metadata" --ffmpeg-param="title=Jade City" "F:/Audiobooks/The Green Bone Saga 01 - Jade City/" --output-file="F:/Audiobooks/Jade City4.m4b"`

The MediaInfo for that was as follows (excluding the Menu 1 and Menu 2):
```
General
Complete name                            : F:\Audiobooks\Jade City4.m4b
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/mp41)
File size                                : 536 MiB
Duration                                 : 19 h 7 min
Overall bit rate mode                    : Constant
Overall bit rate                         : 65.3 kb/s
Album                                    : Jade City - Green Bone Saga, Book 1
Track name                               : Jade City
Performer                                : Fonda Lee
Composer                                 : Fonda Lee
Genre                                    : Fantasy/Fiction/Science Fiction
Description                              : Jade City / Green Bone Saga, Book 1 / Fonda Lee /  / In this World Fantasy Award-winning novel of magic and kungfu, four siblings battle rival clans for honor and power in an Asia-inspired fantasy metropolis.  / *Named one of TIME's Top 100 Fantasy Book ...
Tagged date                              : UTC 2022-12-11 08:51:24
Writing application                      : m4b-tool / OverDrive, Inc.
Copyright                                : Hachette Audio
Cover                                    : Yes
Comment                                  : <p><b>"Stylish and action-packed, full of ambitious families and guilt-ridden loves, <i>Jade City</i> is an epic drama reminiscent of the best classic Hong Kong gangster films but takes place in a fantasy metropolis so gritty and well-imagined that you'll forget you're reading a book." &#8211;Ken Liu, winner of the Hugo, Nebula, and World Fantasy Awards and author of <i>The Grace of Kings</i> and <i>The Paper Menagerie and Other Stories</i></b><p><b>Family is duty. Magic is power. Honor is everything.</b><p>Jade is the lifeblood of the island of Kekon. It has been mined, traded, stolen, and killed for&#8212;and for centuries, honorable Green Bone warriors like the Kaul family have used it to enhance their magical abilities and defend the island from foreign invasion.<p>Now, the war is over and a new generation of Kauls vies for control of Kekon's bustling capital city. They care about nothing but protecting their own, cornering the jade market, and defending the districts under their...
LongDescription                          : Jade City / Green Bone Saga, Book 1 / Fonda Lee /  / In this World Fantasy Award-winning novel of magic and kungfu, four siblings battle rival clans for honor and power in an Asia-inspired fantasy metropolis.  / *Named one of TIME's Top 100 Fantasy Book Of All Time / ​* World Fantasy Award for Best Novel, winner / * Aurora Award for Best Novel, winner / * Nebula Award for Best Novel, nominee / * Locus Award for Best Fantasy Novel, finalist / Jade is the lifeblood of the island of Kekon. It has been mined, traded, stolen, and killed for — and for centuries, honorable Green Bone warriors like the Kaul family have used it to enhance their magical abilities and defend the island from foreign invasion. / Now, the war is over and a new generation of Kauls vies for control of Kekon's bustling capital city. They care about nothing but protecting their own, cornering the jade market, and defending the districts under their protection. Ancient tradition has little place in this rapidly changing...

Audio
ID                                       : 1
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Format settings                          : Joint stereo
Codec ID                                 : mp4a-6B
Duration                                 : 19 h 7 min
Source duration                          : 19 h 7 min
Bit rate mode                            : Constant
Bit rate                                 : 64.0 kb/s
Maximum bit rate                         : 64.8 kb/s / 64.0 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 kHz
Compression mode                         : Lossy
Stream size                              : 525 MiB (98%)
Source stream size                       : 525 MiB (98%)
Writing library                          : LAMEUUULAME3.91
Default                                  : Yes
Alternate group                          : 1
Menus                                    : 2
```
The Audio section seems almost the same as the original mp3 files.

Does this mean that my m4b file is not valid? I can still play it using MPC-HC, VLC, foobar2000, but as you said, they aren't valid. How do I check whether my m4b file is valid or not?

Thanks for the flags to use, I'll try them out!

**Comment by sandreas** [comment]
> If the original mp3 is already low quality, won't re-encoding it to aac reduce the quality even more? Since the quality won't increase no matter what if re-encoding.

Exactly, that's what I was trying to say and I assume that you get this crackling noise because of the encoding with even *lower quality* :-)

> Does this mean that my m4b file is not valid? 

Well, I would say *yes* (it IS invalid) - I never used the `mp3` codec in `m4b` files. 

> How do I check whether my m4b file is valid or not?

The *gold standard* for testing `m4b` files (which internally are `m4a` / `mp4` files with other extension) in my opinion is Apple iTunes. They kind of invented `m4b`  and therefore the codecs in all `m4b` files I've seen are either `aac` or `alac` - both pretty apple-ish. 

Since `mp4` is a pretty open format, you could stuff `mp3` codec in it, but `m4b` is special because of the extension. See https://stackoverflow.com/questions/60365432/how-would-i-go-about-packaging-an-mp3-file-into-an-mp4-container

**Comment by elin1023** [comment]
I tried to encode again with some of the flags you recommended earlier. This time, I am using the docker latest image.
However, I am trying to encode with 2 channels instead of 1, but it still proceeds to encode with 1 channel, the Centre channel. 

Is there any way to encode with 2 channels, if the original files mediainfo show 2 channels?
Original files (mp3) mediaInfo:
```
Audio
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Format settings                          : Joint stereo
Duration                                 : 1 h 10 min
Bit rate mode                            : Constant
Bit rate                                 : 64.0 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 kHz
Frame rate                               : 38.281 FPS (1152 SPF)
Compression mode                         : Lossy
Stream size                              : 32.4 MiB (100%)
Writing library                          : LAMEUUULAME3.91
Language                                 : English
```

Command: `m4b-tool merge -vvv --ffmpeg-threads=20 --jobs=17 --album="Jade City - Green Bone Saga, Book 1" --series="Green Bone Saga" --series-part=1 --writer="Fonda Lee" --audio-channels=2 --audio-bitrate=64k --audio-samplerate=44100 --audio-codec=libfdk_aac --audio-profile=aac_he --ffmpeg-param="-metadata" --ffmpeg-param="title=Jade City" "input/" --output-file="output/Jade City8.m4b"`

The ffmpeg command used shown in the command output ended up being: `'ffmpeg' '-i' 'input/Jade City-Part01.mp3' '-vn' '-ac' '1' '-ar' '44100' '-f' 'caf' '-' | 'fdkaac' '--raw-channels' '1' '--raw-rate' '44100' '-p' '5' '-b' '64k' '-o' '/tmp/m4b-tool/01-converting.m4b' '-'`

Resultant m4b MediaInfo:
```
Audio
ID                                       : 1
Format                                   : AAC LC SBR
Format/Info                              : Advanced Audio Codec Low Complexity with Spectral Band Replication
Commercial name                          : HE-AAC
Format settings                          : Explicit
Codec ID                                 : mp4a-40-2
Duration                                 : 19 h 7 min
Bit rate mode                            : Constant
Bit rate                                 : 64.0 kb/s
Channel(s)                               : 1 channel
Channel layout                           : C
Sampling rate                            : 44.1 kHz
Frame rate                               : 21.533 FPS (2048 SPF)
Compression mode                         : Lossy
Stream size                              : 525 MiB (99%)
Default                                  : Yes
Alternate group                          : 1
Menus                                    : 2
```

Output log of command:
[log-jadecity8.txt](https://github.com/sandreas/m4b-tool/files/10202896/log-jadecity8.txt)

**Comment by sandreas** [comment]
A while ago I did some research about audio quality. I did this pretty long time ago, so I'm not totally sure, why I wrote this piece of code, which forces 1 channel audio on `aac_he` profile, but usually, I do this for a good reason... pretty likely  the `acc_he` profile does not support more than one channel in `fdkaac`.

https://github.com/sandreas/m4b-tool/blob/ed1610812dda817ea9cd8c69d29adbb9dc92702e/src/library/Executables/Fdkaac.php#L115

As you can see in the code, there is `--audio-profile=aac_he_v2`, which should support  2 channels. However, I would not recommend to do so. Your source material is REALLY low quality and having 2 channels will pretty likely not improve the audio quality, but only the file size. Keep in mind that 1 audio channel (mono) will not result in having audio signal on one speaker only. It will be just cloned to all available speakers and you barely hear a difference between stereo audiobooks and mono ones - especially, if there is one single narrator.

**Comment by elin1023** [comment]
Thanks for all the insight! I'll stick to the one channel then. Would using aac_he limit the amount/type of devices this can play on? I would assume not since it looks like this was standardised in 2003?

Also, I used 17 jobs because there are 17 of the original Overdrive mp3 part files. It's so that all of them can run/process at the same time, which they are able to with this setting. The ffmpeg-threads was kind of random.

**Comment by sandreas** [comment]
>  Would using aac_he limit the amount/type of devices this can play on? 

I don't think so... never had any issues. 

> Also, I used 17 jobs because there are 17 of the original Overdrive mp3 part files. 

I would not do that - `--jobs` should NOT have a value higher than the count of your CPU cores. If it is higher, it will be slower conversion, not faster. And I would also not use `--ffmpeg-threads` then. If you have 4 cores, use `--jobs=4`.


I'm closing this issue, since this is more a discussion now :-)

**Comment by elin1023** [comment]
Alright then thanks!
