### ISSUE TITLE
MP3s merged in wrong order in final M4B

### ISSUE THREAD

**Issue by majant0** [sandreas/m4b-tool#214]
I'm following the same process that I referenced in #212 where I use Audacity to split my single MP3 into one MP3 per chapter. I also used Audacity to ensure the files were properly tagged with Album, Track, Title, & Artist. After using the `merge` command, my final M4B is out of order. It placed the Intro at the end (the rest of the chapters were in correct order). Does `m4b-tool` use the `track` tag to determine the order of the MP3s?

Here was the command I used:
`m4b-tool merge "Audiobook/" -v --output-file="Audiobook.m4b"`

Here is an abbreviated mediainfo for a the first two chapters:
<img width="663" alt="image" src="https://user-images.githubusercontent.com/95008455/213498209-e9bb63d5-39ea-49e6-8b6c-b5e8ed1404f1.png">
<img width="659" alt="image" src="https://user-images.githubusercontent.com/95008455/213498477-7844c6c8-1df5-4811-84b6-5b170dc0f818.png">

**Comment by sandreas** [comment]
> Does m4b-tool use the track tag to determine the order of the MP3s?

no, filenames in natural order. never had a case that did not work

**Comment by sandreas** [comment]
So I tried to reproduce this and failed. If you don't want to publish the filenames you used, I could give you an invite to a private repository, where you can share the files privately. Unfortunately I don't see another option to reproduce this issue. 

What do you think?

**Comment by majant0** [comment]
No worries. I'll just append the track number to the start of the filename.

**Comment by sandreas** [comment]
@majant0 Ok, if this is ok... maybe the issue re-appears on someone else's files. We'll see. Thanks for closing and your patience.
