### ISSUE TITLE
PHP Deprecated

### ISSUE THREAD

**Issue by thecrazyturkey** [sandreas/m4b-tool#215]
Keep getting the same errors. Uninstalled and reinstalled twice

PHP Deprecated:  Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/vendor/symfony/console/Helper/HelperSet.php on line 104

Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/vendor/symfony/console/Helper/HelperSet.php on line 104
m4b-tool v.0.4.2
an error occured, that has not been caught:
Array
(
    [type] => 8192
    [message] => Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
    [file] => phar:///usr/local/Cellar/m4b-tool/0.4.2/bin/m4b-tool/vendor/symfony/console/Helper/HelperSet.php
    [line] => 104
)

**Comment by sandreas** [comment]
Please upgrade to [latest pre-release](https://github.com/sandreas/m4b-tool/releases/tag/latest)... I'm really sorry I can't release a new stable but ATM I'm so busy with family things I can't even write documentation. 

It might be that the pre-release also shows some deprecation warnings, but these basically can be ignored, it's just a Notice in most cases.

**Comment by sandreas** [comment]
closed due to no further feedback. Feel free to reopen.
