### ISSUE TITLE
Splitting book adds extra chapters

### ISSUE THREAD

**Issue by gazpachoking** [sandreas/m4b-tool#219]
It seems when I run the split command to split a book, each resulting file contains more than one chapter, which is confusing my audio player (audiobookshelf.) (Not sure if this is related to #218, I did get those errors when doing this split.)

For example, here is the metadata for the first 3 files created by the split command for one book:
![image](https://user-images.githubusercontent.com/187133/218334684-31c3ba66-8d24-413a-84c7-e4c8d0a29a41.png)
![image](https://user-images.githubusercontent.com/187133/218334699-113060f6-306f-46e4-8542-b72943fc8836.png)
![image](https://user-images.githubusercontent.com/187133/218334716-f66cb466-4e83-4325-acc8-cfc03ee36959.png)

The rest of the files follow the same pattern, where they mark the previous and current chapter as starting at 00:00, and also mark the next chapter as starting right at the end of the file.

I'm not 100% confident on how the embedded chapters in an m4b file work, but it seems to me that each file should only contain 1 chapter starting at 00:00:00, since I've just run the command to split the book on chapter lines. The second two files seem especially wrong, since they mark 2 separate chapters as starting at the beginning of the track.

The result, is that when importing the book, I get a crazy amount more chapters marked than actually exist, and using the next/previous track buttons also requires redundant presses:
![image](https://user-images.githubusercontent.com/187133/218334854-012cf198-0c6c-4234-9529-9874633bdfa9.png)

**Comment by sandreas** [comment]
Confirmed, thanks for reporting. This is `ffmpeg` "behaviour" (maybe a bug), but I was able to workaround this in my tests. Fix follows hopefully in the next days.

**Comment by gazpachoking** [comment]
Awesome! Thanks so much for this project and all your work on it. 🍾
