### ISSUE TITLE
Option '--use-existing-chapters-file' not recognized

### ISSUE THREAD

**Issue by edrozenberg** [sandreas/m4b-tool#22]
```$ m4b-tool.phar --version```
```m4b-tool v.0.3.1```

I'm trying to use the option ```--use-existing-chapters-file``` to specify a chapters file I manually edited, and it gives the following error:

```
The "--use-existing-chapters-file" option does not exist.
```

In addition, the description for this feature in the doc/manual seems like it describes a different feature:

```
--use-existing-chapters-file           adjust chapter position by nearest found silence
 ```

**Comment by sandreas** [comment]
Thanks for reporting, seems that this option is not used very often... I'll take a look at this in the next days.

**Comment by sandreas** [comment]
Should be fixed, there was also an issue with chapter index, I released an alpha version, so you don't have to wait until the next release...

https://github.com/sandreas/m4b-tool/releases/tag/0.3.2-alpha1

You should also take a look at the new `--output-directory` and `--filename-template` Option, if you would like to use other naming than `<audiobookname>_splitted/<chapter-index>-<chapter-name>`...
