### ISSUE TITLE
Embed subtitles into m4b

### ISSUE THREAD

**Issue by kanjieater** [sandreas/m4b-tool#220]
I was wondering if it's possible to embed a transcript of the audio into the m4b file using m4b-tool. I have an audiobook with corresponding SRT subtitle file that I would like to combine if possible.

**Comment by sandreas** [comment]
Interesting idea. There are several ways to achieve this, but unfortunately this feature is not integrated `m4b-tool`. I would try to go for **Synchronized Lyrics**, where you need the timestamp in the file and the according line in the text.

`tone` may have support for similar metadata (I would need to check) but definitely not via SRT file, this would have to be converted. 

I'm still pretty sure that there are not many players supporting this kind of integration. What would you need this for?

**Comment by kanjieater** [comment]
Honestly it's not too much trouble to just have a srt file unembedded - so no pressure to implement something highly specific like this. 

I use this for language learning with synchronized texts & audiobooks. MPV as well as players that allow for mp3s to play with sub files support this type of functionality already (animebook, absplayer, memento, etc)

I'll close this for now, as it was out of curiosity - but if someone else thinks this is worth discussing more we can open it.
