### ISSUE TITLE
Chapters with / get split into folders

### ISSUE THREAD

**Issue by kanjieater** [sandreas/m4b-tool#228]
![image](https://user-images.githubusercontent.com/32607317/221290643-18654f0f-f4db-45d5-92a8-ba51e75d73f0.png)
![image](https://user-images.githubusercontent.com/32607317/221290713-0aaabc00-07b8-4b41-8783-0b9a1bf5621e.png)

A bit strange, but this seems valid. Could m4b-tool escape the chapter name? 
I'm guessing any of these could cause problems
![image](https://user-images.githubusercontent.com/32607317/221291327-adfd33ed-82ec-4018-afe1-fa68dd60d3cb.png)

Chapters are still copied over correctly it looks like (it's not taking just Introduction for instance - yay): 
![image](https://user-images.githubusercontent.com/32607317/221291133-73b16e31-c5fc-4858-bde1-0184c9e6b94d.png)

**Comment by kanjieater** [comment]
It does seem like it left off the timestamps for the / chapter too - not sure why? 
![image](https://user-images.githubusercontent.com/32607317/221292858-6569bf35-222c-470a-b5b6-a91dfdec61b2.png)

**Comment by gazpachoking** [comment]
> It does seem like it left off the timestamps for the / chapter too - not sure why?

I don't think it left out any times. That chapter title is just long and wrapped to the next line. `Part 1  What ? ............Why ? /Introduction`

**Comment by sandreas** [comment]
This is definitely not intended and should be fixed. Thanks for reporting.
