### ISSUE TITLE
Issue reindexing chapters for audiobooks with many chapters.

### ISSUE THREAD

**Issue by HabelStefan** [sandreas/m4b-tool#234]
I'm running into an issue which large audiobooks (do know if its the file size (all are bigger than 1GB) or the chapter number).

found 563 chapters to reindex                                                                                                                                                               
Error: Object reference not set to an instance of an object.       
                                                                                                                                                                                         

Any ideas?

Best regards,

Stefan

_Originally posted by @HabelStefan in https://github.com/sandreas/m4b-tool/issues/216#issuecomment-1483459119_

**Comment by sandreas** [comment]
Hey Stefan,

I'll close this issue since it is not an `m4b-tool` one, but a `tone` scripting issue. I'll add this issue to `tone` soon, ut let me first try some experiments, maybe it is just a script error, not a `tone` error. I hacked this script together in a very short time :-)

Best
sandreas

**Comment by HabelStefan** [comment]
Oh sry, you’re right, wrong repository :)

**Comment by sandreas** [comment]
Moved to https://github.com/sandreas/tone/issues/40
