### ISSUE TITLE
Chapters not being marked with --no-conversion

### ISSUE THREAD

**Issue by ja2ui0** [sandreas/m4b-tool#237]
### syntax used
`i="foldername"; m4b-tool merge --no-conversion -vv "${i}" --output-file="${i}/${i}.m4b"`

### expectation
`foldername.m4b` file contains unprocessed merge of all mp3 files in folder with chapter markings based on title tags

### reality
resulting m4b file contains merge of all mp3 files, but no chapters marked
(tried adding `--mark-tracks` but it seems to be ignored by `--no-conversion`)

### workaround
`i="foldername"; m4b-tool merge --audio-channels 1 --jobs 6 -vv "${i}" --output-file="${i}/${i}.m4b"`

### outcome
`foldername.m4b` contains reprocessed output of all mp3s in folder, with chapters, but ~10% larger filesize, which is not ideal. I can't imagine that ~20 chapters should add ~20MB padding to a ~200MB audio file compared to storing the encoded stream as-is in an m4b container.

**Comment by sandreas** [comment]
Ok, this is clearly a problem, I'll take a look. Thanks for reporting.

**Comment by ja2ui0** [comment]
To add, I just checked a file where I tried this again (to be sure that I'm not crazy) and not only do chapter markings get skipped with `--no-conversion`, but ALL tags from the original source files are discarded and the resulting m4b is completely bereft of all tags other than `title`.

**Comment by ja2ui0** [comment]
this actually seems not to be an issue with the latest beta. My bad for not checking first.

**Comment by sandreas** [comment]
> this actually seems not to be an issue with the latest beta. My bad for not checking first.

Oh great, thanks for re-checking and closing the issue
