### ISSUE TITLE
Cue sheets for reading metadata

### ISSUE THREAD

**Issue by bibstha** [sandreas/m4b-tool#243]
Is it possible to make a cue sheet parser as a way to read metadata? 

I've got a cuesheet like this

```
TITLE "Book Name"
FILE "somefile.mp3" MP3
  TRACK 01 AUDIO
    TITLE "Introduction"
    INDEX 01 00:00
  TRACK 02 AUDIO
    TITLE "Chapter 1"
    INDEX 01 00:12
  TRACK 03 AUDIO
    TITLE "Chapter 2"
    INDEX 01 12:05
```

Would love to use this to extract chapter information instead of silence detection.

**Comment by sandreas** [comment]
`m4b-tool` already has a cue parser, but currently only splitting is supported (see https://github.com/sandreas/m4b-tool/issues/103#issuecomment-731322965)

I could write a `CueImprover` detecting any `cue` files in the root dir of an  audio book, should not be too much effort, similar to https://github.com/sandreas/m4b-tool/blob/ccfb548cda1bfc5f764771ca10d11ba153488476/src/library/Audio/Tag/Cover.php#L11

I'm not sure how long this will take, I'm totally busy atm, sorry.

**Comment by sandreas** [comment]
`merge` support will be in the next pre-release...
