### ISSUE TITLE
Not adding metadata to the output file

### ISSUE THREAD

**Issue by filippoteso** [sandreas/m4b-tool#244]
I tried merging .mp3 files in a .m4b audiobook on Windows, using the system command prompt, but the output file has no metadata, cover image, or description.

**OS:** Windows 11 Pro 21H2 (x64)
**Command:** `php m4b-tool.phar merge --name="The Two Towers" --series="The Lord of the Rings" --series-part="2" --output-file="C:\Users\Utente\Desktop\Libri e audiolibri\Audiolibri m4b\Fantasy\J. R. R. Tolkien\The Lord of the Rings\2 - The Two Towers\The Two Towers.m4b" "C:\Users\Utente\Desktop\Libri e audiolibri\Audiolibri m4b\Fantasy\J. R. R. Tolkien\The Lord of the Rings\2 - The Two Towers"`

I also tried to force the metadata, but to no avail:
**Command:** `php m4b-tool.phar merge --name="The Two Towers" --artist="Rob Inglis" --series="The Lord of the Rings" --series-part="2" --genre="Fantasy" --writer="J. R. R. Tolkien" --year="1990" --cover="cover.jpg" --description="description.txt" --output-file="C:\Users\Utente\Desktop\Libri e audiolibri\Audiolibri m4b\Fantasy\J. R. R. Tolkien\The Lord of the Rings\2 - The Two Towers\The Two Towers.m4b" "C:\Users\Utente\Desktop\Libri e audiolibri\Audiolibri m4b\Fantasy\J. R. R. Tolkien\The Lord of the Rings\2 - The Two Towers"`

[cover.jpg](https://github.com/sandreas/m4b-tool/assets/53758364/79c22be6-4a5d-4543-b4d8-4955419d7cc1)
[description.txt](https://github.com/sandreas/m4b-tool/files/12240377/description.txt)

**Comment by sandreas** [comment]
Which version are you using?
You could try to use `--debug` to get more info what is going wrong.

**Comment by filippoteso** [comment]
Thanks for replying, I'm using m4b-tool v.0.4.2

I tried running:
`php m4b-tool.phar merge` **`--debug`** `--name="The Two Towers" --series="The Lord of the Rings" --series-part="2" --output-file="C:\Users\Utente\Desktop\Libri e audiolibri\Audiolibri m4b\Fantasy\J. R. R. Tolkien\The Lord of the Rings\2 - The Two Towers\The Two Towers.m4b" "C:\Users\Utente\Desktop\Libri e audiolibri\Audiolibri m4b\Fantasy\J. R. R. Tolkien\The Lord of the Rings\2 - The Two Towers"`

... and this is what I got:
`ffmpeg -hide_banner -codecs`
`determine highest available audio codec`
`Your ffmpeg version cannot produce top quality aac using encoder aac instead of libfdk_aac`
`== load input files ==`
`reading metadata and streaminfo for file C:\Users\Utente\Desktop\Libri e audiolibri\Audiolibri m4b\Fantasy\J. R. R. Tolkien\The Lord of the Rings\2 - The Two Towers\Book III - Chapter 01 - The Departure of Boromir.mp3`
`searching for cover in C:\Users\Utente\Desktop\Libri e audiolibri\Audiolibri m4b\Fantasy\J. R. R. Tolkien\The Lord of the Rings\2 - The Two Towers`
`using cover  C:\Users\Utente\Desktop\Libri e audiolibri\Audiolibri m4b\Fantasy\J. R. R. Tolkien\The Lord of the Rings\2 - The Two Towers\cover.jpg`
`searching for description.txt in C:\Users\Utente\Desktop\Libri e audiolibri\Audiolibri m4b\Fantasy\J. R. R. Tolkien\The Lord of the Rings\2 - The Two Towers`
`checking file C:\Users\Utente\Desktop\Libri e audiolibri\Audiolibri m4b\Fantasy\J. R. R. Tolkien\The Lord of the Rings\2 - The Two Towers\description.txt, realpath: C:\Users\Utente\Desktop\Libri e audiolibri\Audiolibri m4b\Fantasy\J. R. R. Tolkien\The Lord of the Rings\2 - The Two Towers\description.txt`
`success: found description.txt for import`
`skip cover extraction, file C:\Users\Utente\Desktop\Libri e audiolibri\Audiolibri m4b\Fantasy\J. R. R. Tolkien\The Lord of the Rings\2 - The Two Towers/cover.jpg already exists - use --force to overwrite`
`preparing conversion with 1 simultaneous job, please wait...`
`  21 remaining /   21 total \`

**Comment by sandreas** [comment]
Try upgrading to latest pre-release 
Should fix your issues 
Instructions on the releases page

**Comment by filippoteso** [comment]
not sure how I'd do that

**Comment by filippoteso** [comment]
Trying it rn, will update this comment after it finishes running.

**Comment by filippoteso** [comment]
Sorry to reopen the issue but I have created a satisfactory audiobook to which I already added a lot of metadata (mostly sorting) via the iTunes app for Windows. I’d like to rename some chapters without having to go through the whole process once again. I wonder if and how this can be done via m4b-tool and if doing that would delete the iTunes specific metadata

**Comment by filippoteso** [comment]
Sorry to reopen the issue but I have created a satisfactory audiobook to which I already added a lot of metadata (mostly sorting) via the iTunes app for Windows. I’d like to rename some chapters without having to go through the whole process once again. I wonder if and how this can be done via m4b-tool and if doing that would delete the iTunes specific metadata

**Comment by sandreas** [comment]
> I wonder if and how this can be done via m4b-tool and if doing that would delete the iTunes specific metadata

```bash
m4b-tool meta "Santa Claus.m4b" --export-chapters

# edit manually "Santa Clause.chapters.txt"

m4b-tool meta "Santa Claus.m4b" --import-chapters

rm "Santa Clause.chapters.txt"
```
