### ISSUE TITLE
ffmpeg version 4.0.0 or higher is required

### ISSUE THREAD

**Issue by PetrusVermaak** [sandreas/m4b-tool#246]
First off, total noob. I had this running on my virtual Ubuntu server. Upgraded pc and now cannot re-install it because mp4v2 is not available on Ubuntu anymore.

Spent a whole two weeks trying to get docker going on Windows 11 but its a total no-go. I suspect it's because I am on AMD Ryzon processors, but anyway. Meh.

I finally managed to get the Windows version running.

Here is my cmd:
 ./php -f C:\m4b-tool\m4b-tool.phar merge -v --artist "Artist" --name "DemoBookName"  --audio-bitrate 16k --audio-samplerate 44100 --audio-codec aac --audio-profile aac_he_v2 --jobs 4 "C:\Book_Build\" -o "C:\Book_Build\Demo.m4b"

I get these errors: 
1. ffmpeg version 4.0.0 or higher is required - installed version 3.2.0 is likely to cause errors or unexpected behaviour.
2. could not convert C:\Book_Build\01_File.mp3 to C:\Book_Build\Demo-tmpfiles\01-finished.m4b

I've downloaded the latest ffmpeg and added it to my Environment Path, so when I enter ffmpeg -version in the cmd line, I get: 
ffmpeg version 2023-10-12-git-a7663c9604-full_build-www.gyan.dev

I'm so desperate I would even encode the files straight with ffmpeg but I cannot manage to get the --audio-bitrate 16k --audio-samplerate 44100 --audio-codec aac --audio-profile aac_he_v2 compression no matter what I try.

I've spent about 30 days trying various things, which shows my absolute incompetence. If anyone could please put me out of my misery, I would greatly appreciate it!! 🙈 🤣 😊

**Comment by sandreas** [comment]
> Upgraded pc and now cannot re-install it because mp4v2 is not available on Ubuntu anymore.

Well, you can still copy all the binaries or download the old package, should work.

> I've spent about 30 days trying various things, which shows my absolute incompetence. If anyone could please put me out of my misery, I would greatly appreciate it!! 🙈 🤣 😊

It's not your fault. `m4b-tool` is designed as a power user tool for experts and you have to bring a lot of knowledge, if you aren't using docker.

However, I would recommend to re-validate your possibilities. You have a Win-11 machine, so you have three options to use `m4b-tool`:
- Windows 11 Professional: Install docker desktop (https://docs.docker.com/desktop/install/windows-install/)
- Use VirtualBox with Shared-folders to install a Linux VM and install docker within this VM (complicated)
- Install `m4b-tool` manually with all the tools (very complicated, that's what you did)

So my recommendation would be:
- Download and install VirtualBox
- Install latest Ubuntu in a new VM
- Install docker with this: 
```bash
## docker (Community Edition)
dpkg -s "docker-ce" &> /dev/null 
if [ "$?" -ne "0" ]; then 
	curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
	sudo add-apt-repository \
	   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
	   $(lsb_release -cs) \
	   stable"
	
	sudo apt -y purge docker docker-engine docker.io
	sudo apt -y update
	sudo apt -y install docker-ce
	sudo groupadd docker
	sudo usermod -aG docker "$USER"
  sudo systemctl enable docker
  sudo systemctl start docker
fi
```


After this you can use `m4b-tool` like described in the README...

**Comment by PetrusVermaak** [comment]
Awesome!!

Followed everything and docker is installed and running, but when I try to check the version I get this:
ubuntu@ubuntu2004:~/m4b-tool$ sudo docker pull sandreas/m4b-tool:latest
ubuntu@ubuntu2004:~/m4b-tool$ alias m4b-tool='docker run -it --rm -u $(id -u):$(id -g) -v "$(pwd)":/mnt sandreas/m4b-tool:latest'
**ubuntu@ubuntu2004:~/m4b-tool$ m4b-tool --version**
docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
ubuntu@ubuntu2004:~/m4b-tool$

**Comment by sandreas** [comment]
> Followed everything and docker is installed and running, but when I try to check the version I get this:

Either the docker service is not running:
```bash
sudo systemctl status docker
```

Or you forgot to add your user to the `docker` group:

```bash
	sudo usermod -aG docker "<your-username>"
```

Restart your VM to be sure everything is working like expected.

**Comment by sandreas** [comment]
Closed, seems resolved. Feel free to reopen.

**Comment by PetrusVermaak** [comment]
Hi @sandreas,

I hit a wall of frustration dealing with this issue, so I finally got some pro help. Now, I've got an Oracle VM Image of Ubuntu 14.04.3 all set up, with everything you'd need, including a handy mapped folder. Just drop your files into a Windows folder (or whatever OS you want to run Oracle VM on), and you're good to go in seven easy steps. I even whipped up a guide that walks you through the whole setup and how to use the tool. Trust me, if I can manage it, anyone can—it's that user-friendly.

I made this for myself, but your tool is too awesome to keep this solution to myself. Would you mind adding it to your GitHub? Your tool is the gold standard, no doubt, and everyone should be using it.

**Comment by sandreas** [comment]
> I made this for myself, but your tool is too awesome to keep this solution to myself. Would you mind adding it to your GitHub? Your tool is the gold standard, no doubt, and everyone should be using it.

I'm glad it works for you. What do you want me to share? A tutorial? Or a VM?
Don't get me wrong, but I would prefer having a more modern OS, Ubuntu 14.04 does not seem to be the right choice for a current setup :-)

**Comment by PetrusVermaak** [comment]
The VM can be shared with the tutorial for other noobs like me. Would you prefer if the VM was Ubuntu 20 or another newer version?

**Comment by sandreas** [comment]
> The VM can be shared with the tutorial for other noobs like me. Would you prefer if the VM was Ubuntu 20 or another newer version?

Well, best case scenario would be having a very small distribution like [Alpine](https://wiki.alpinelinux.org/wiki/Installing_Alpine_in_a_virtual_machine), if it has to be ubuntu, I would use the latest LTS (22.04).

**Comment by PetrusVermaak** [comment]
@sandreas I tried to make Alpine go but its beyond my skills.

I successfully created the following, no idea why some are larger when on the same version of Ubuntu. All of them can be upgraded to the latest version so I guess in that regard Ubuntu 18 is not too bad because one can upgrade if needed.

**Ubuntu + GUI + Docker + m4b-tools:**
Ubuntu_18.04.3_docker-m4b-tools_VirtualBox_Image.ova 4 GB
Ubuntu_20.04.6_docker-m4b-tools_VirtualBox_Image.ova 9.1 GB
Ubuntu_22.04.3_docker-m4b-tools_VirtualBox_Image.ova 11.5 GB

**Ubuntu + GUI + native install of m4b-tools:**
Ubuntu_18.04.3_native-m4b-tools-VirtualBox_Image.ova 14 GB 

**Ubuntu + No GUI + Docker + m4b-tools:**
Ubuntu_18.04.6_no_gui_docker-m4b-tools_VirtualBox_Image.ova 2.5 GB

The procedure and password is the same for all, except the no GUI has different password.

Which ones would you like? They all work great but the no GUI one is very limited. Better to ssh or telnet into it as you can then copy and paste and scroll up and down.
