### ISSUE TITLE
Anyway to merge and use individual .mp3 filenames as chapter titles?

### ISSUE THREAD

**Issue by tylermanning** [sandreas/m4b-tool#250]
The merging works pretty well and does a good job of maintaining metadata from .mp3 files but in instances when the .mp3 files are named after each chapter, is there a way to use the filename as chapter titles?

I'm using Subler by the way to double check the final output and fix any issues.

**Comment by sandreas** [comment]
Try `--use-filenames-as-chapters`. Let me know if it is working...
