### ISSUE TITLE
homebrew options for ffmpeg in readme deprecated

### ISSUE THREAD

**Issue by gennaios** [sandreas/m4b-tool#26]
Hello,

Many of the options for ffmpeg install via homebrew have been removed, such as --with-fdk-aac.

https://github.com/Homebrew/homebrew-core/issues/36938

As such, with a default install, I get the message:

>Your ffmpeg version cannot produce top quality aac using encoder aac instead of libfdk_aac

**Comment by kpumuk** [comment]
A very sad decision from homebrew team. The easiest option now is to use a fork with brew options https://github.com/varenc/homebrew-ffmpeg

**Comment by sandreas** [comment]
I'll take a look into this in the next days. Thanks for reporting...

**Comment by gennaios** [comment]
Thank you. I tried that fork a few days ago but am trying again now. I think the only options available with it are `--with-chromaprint` and `--with-fdk-aac`. I'm trying --HEAD to see mainly to figure out how to properly get `--no-conversion` to work.

**Comment by kpumuk** [comment]
```
brew tap varenc/ffmpeg
brew tap-pin varenc/ffmpeg
brew uninstall ffmpeg
brew install --with-chromaprint --with-fdk-aac
```

The rest of options are enabled by default now.

**Comment by gennaios** [comment]
Those are the options I used. Thank you.

**Comment by sandreas** [comment]
Man, this was tough... i did not manage to find an easy solution for this, so i had to update the documentation with more commands i'd like to.

It seems that there is or once was a formula of m4b-tool in the core brew repo, which confused my `brew` installation and he always tried to install `v.0.3.1`, which is not the latest one and crashed with wrong checksums... very strange.

Furthermore, there is no handy command to install ffmpeg with libfdk besides the varenc repo. I hope i did not miss something, but if someone knows a better / shorter approach, i would appreciate it.

**Comment by kpumuk** [comment]
Looks good to me. FYI, I have noticed that m4b-tool when using ffmpeg without fdk-aac (yeah, that message about missing lib is really hard to notice, and homebrew silently dropped options, so it installed vanilla ffmpeg instead of pre-configured version), all m4b parts were converted correctly, but then it failed to merge them (e.g. the result was 5kb file without any sound).

Should it, maybe, fail by default without fdk-aac, and add a param like `--ignore-missing-fdk-aac` for those who willingly want to screw themselves?

**Comment by sandreas** [comment]
> all m4b parts were converted correctly, but then it failed to merge them (e.g. the result was 5kb file without any sound).

@kpumuk 
Would you mind adding an extra issue for this? I need the exact circumstances and error messages, so that i can reproduce and fix the issue...

**Comment by gennaios** [comment]
Hello,

Looks like the tap mentioned in the README is no longer maintained. The new repo is 

https://github.com/homebrew-ffmpeg/homebrew-ffmpeg

**Comment by sandreas** [comment]
Ok, I'll take a look in the next days.
