### ISSUE TITLE
If input file number gets to big, auto-m4b skips parts

### ISSUE THREAD

**Issue by mupsza** [sandreas/m4b-tool#267]
I tried to process a audiobook that consists of 540 mp3 files (well named, one folder etc).
auto-m4b processes the book / folder without visible problems, but the result only contains approx. 50 input files.

I tried to reencode the einput file before processing but it still skips files.
Interestingly, other files are skipped, after reencoding the source.

no problems visible in log file

**Comment by sandreas** [comment]
`auto-m4b` is a third party product, unfortunately I cannot provide support for it.

If you provide a `m4b-tool` only command that does not work, I would take a look. Maybe this has to do with issue #109?

**Comment by sandreas** [comment]
Closed due to no further feedback.
