### ISSUE TITLE
ChapterTitleBuilder.php crash

### ISSUE THREAD

**Issue by popcorn9499** [sandreas/m4b-tool#32]
```
In ChapterTitleBuilder.php line 42:
                                                                           
  could not get duration for file data/merged-tmpfiles/01-01-finished.m4b  
                                                                           
```

I am running Arch Linux all i did was run the tool and it worked up until it threw this error unsure what I did wrong.

just ran 
`m4b-tool merge $(some input path) --output-file=$(some output path)`

**Comment by sandreas** [comment]
Thanks for reporting. I think I already fixed this in the nightly builds... 

[Download m4b-tool nightly](https://github.com/sandreas/m4b-tool/files/3116038/m4b-tool.tar.gz)

Could you check it with this version?

**Comment by popcorn9499** [comment]
that seems to of fixed all issues thank you
