### ISSUE TITLE
No possibility to add a comment tag on audiobooks

### ISSUE THREAD

**Issue by kaileu** [sandreas/m4b-tool#4]
Hi,

it would be nice to add the possibility to give a comment tag like --Name for a title.

**Comment by sandreas** [comment]
Could you explain how this would look in a real command line call?

```
e.g. ./m4b-tool tag --name="My Title"
```

Since m4b-tool depends on mp4v2 utils, you could use mp4tags for this already... 

```
mp4tags -help
```

Is this what you meant?

**Comment by kaileu** [comment]
In a real commandline:

./m4b-tool.phar merge --comment "my Comment" --name="My Title" Input output

error: The "--comment" option does not exist.

mp4tags is working like that if you tag a a actual file:

mp4tags --comment "my Comment" C:\Users\bla\Music\file.m4b


It would be nice if that command Option would be added to the merge Operation so thats can be done from one command.

**Comment by sandreas** [comment]
Ok, I'll take this as an enhancement :-) 

Todo:
- Wrap all mp4tags-Parameters to be more flexible editing metadata
- Adopt all metadata from files into merged file

**Comment by sandreas** [comment]
Done:
- Added comment, copyright and encoded-by parameter

Todo:
- Further testing with ffmpeg metadata (seems to be unescaped at the moment)
