### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function M4bTool\Parser\simplexml_load_string()

### ISSUE THREAD

**Issue by dmuiX** [sandreas/m4b-tool#40]
**While trying to add chapters to an m4b audiobook with this command:**

m4b-tool chapters --first-chapter-offset 4000 --last-chapter-offset 3500 -m 969d83a3-e80c-4b47-895a-5b8a410836bd "/mnt/d/Download/Star Wars Erben des Imperiums Hörbuch (Band 1).m4a"

**I've got this error:**

PHP Fatal error:  Uncaught Error: Call to undefined function M4bTool\Parser\simplexml_load_string() in phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Parser/MusicBrainzChapterParser.php:85
Stack trace:
#0 phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/ChaptersCommand.php(125): M4bTool\Parser\MusicBrainzChapterParser->parseRecordings('<?xml version="...')
#1 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Command/Command.php(255): M4bTool\Command\ChaptersCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(908): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(269): Symfony\Component\Console\Application->doRunCommand(Object(M4bTool\Command\ChaptersCommand), Object(Symfony\Component\Console\ in phar:///usr/local/bin/m4b-to
ol/src/library/M4bTool/Parser/MusicBrainzChapterParser.php on line 85
an error occured, that has not been caught:
Array
(
    [type] => 1
    [message] => Uncaught Error: Call to undefined function M4bTool\Parser\simplexml_load_string() in phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Parser/MusicBrainzChapterParser.php:85
Stack trace:
#0 phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/ChaptersCommand.php(125): M4bTool\Parser\MusicBrainzChapterParser->parseRecordings('<?xml version="...')
#1 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Command/Command.php(255): M4bTool\Command\ChaptersCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(908): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Application.php(269): Symfony\Component\Console\Application->doRunCommand(Object(M4bTool\Command\ChaptersCommand), Object(Symfony\Component\Console\
    [file] => phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Parser/MusicBrainzChapterParser.php
    [line] => 85
)

But I **solved** it by installing the php7.2-xml extension. Maybe you should put this as a dependency in the Installation Description of Ubuntu. I am using the WSL based on ubuntu.

**Comment by sandreas** [comment]
> Maybe you should put this as a dependency in the Installation Description of Ubuntu
Yes, this one of some extensions, that are required. I'll try to enhance the documentation :-) Thank you for reporting.
