### ISSUE TITLE
Feature Request: Parse opf file for metadata

### ISSUE THREAD

**Issue by drneal12** [sandreas/m4b-tool#41]
It would be great if the merge functionality could take a 'metadata.opf' file from a program like calibre and use that as the metadata.

**Comment by sandreas** [comment]
Is this the specification, you are talking about? 
http://www.idpf.org/epub/20/spec/OPF_2.0.1_draft.htm

If so, could you provide an example file, that i could start with? Does not matter which language, but it should include as much data fields as possible for testing.

**Comment by drneal12** [comment]
Yup I'm pretty sure that is the one! Github won't let me attach that format so I converted to a txt so that github will accept it.

[metadata.txt](https://github.com/sandreas/m4b-tool/files/3524157/metadata.txt)

**Comment by sandreas** [comment]
Nice. Thank you. I'll check it in the next days.

**Comment by sandreas** [comment]
Ok, should work... Here is a testing build:

[m4b-tool.tar.gz](https://github.com/sandreas/m4b-tool/files/3528490/m4b-tool.tar.gz)

**Comment by sandreas** [comment]
Short question, since there was no feedback: Did it work? :-)

**Comment by drneal12** [comment]
Like a dream!  Works great!  This tool (plus mp4chaps) combined with calibre have upped my audiobook library game a ton.

**Comment by sandreas** [comment]
This is great news. Then i will integrated it in the next official release. 

You say:

> plus mp4chaps

Since `m4b-tool` already uses `mp4chaps`, are you using `mp4chaps` for? 

Perhaps you did not notice, that you can just put a `chapters.txt` besides the `metadata.opf` and `mp4chaps` is used automatically to create the chapters for you - see https://github.com/sandreas/m4b-tool#step-3---chapters *fixed chapters* for details.

**Comment by drneal12** [comment]
I use it to change the chapter names.  So if I already have an m4b file:
```
mp4chaps -x book.m4b
change the chapter names
mp4chaps -i book.m4b
```
Or if I have mp3 files to merge I let m4btool get me all the right times, but then change the names and then import them with mp4chaps

**Comment by sandreas** [comment]
Ah I see :-) Thank you for your quick feedback.
