### ISSUE TITLE
m4b-tool php parse

### ISSUE THREAD

**Issue by littlejeem** [sandreas/m4b-tool#42]
Title: m4b-tool does not give a vaild install version - array syntax error

First of all I just want to say that this looks like a first class job, I'm so grateful that people like you take the time to write stuff like this.......he says bowing down in a Waynes World type "we're not worthy" salute........

If i run ```m4b-tool --version``` I receive a PHP Parse Error as follows.

OS: Ubuntu 16.04.6 LTS
Command: ```m4b-tool --version```
Error:
```php
PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Output/Output.php on line 40
an error occured, that has not been caught:
Array
(
    [type] => 4
    [message] => syntax error, unexpected '?', expecting variable (T_VARIABLE)
    [file] => phar:///usr/local/bin/m4b-tool/vendor/symfony/console/Output/Output.php
    [line] => 40
)
```

**Comment by sandreas** [comment]
> First of all I just want to say that this looks like a first class job, I'm so grateful that people like you take the time to write stuff like this.......he says bowing down in a Waynes World type "we're not worthy" salute........

thank you, comments like these are very motivating! It is an honor.

> If i run m4b-tool --version I receive a PHP Parse Error as follows.

Well, since this is an error, that points to a library path of Symfony (`vendor/symfony/console/Output/Output.php`) and not to an `m4b-tool` specific file, i guess this has to do something with your PHP Version. `m4b-tool` might be incompatible with PHP 7.0...

Could you provide the output of:

`php -v`

As you are on linux you might try to overcome this issue without having to install another PHP version by switching to the `docker` image, see https://github.com/sandreas/m4b-tool#user-content-best-practices for usage details.

I for myself prefer the community edition, to install `docker` you could use:

```
dpkg -s "docker-ce" &> /dev/null 
if [ "$?" -ne "0" ]; then 
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository \
           "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
           $(lsb_release -cs) \
           stable"
        
        sudo apt -y purge docker docker-engine docker.io
        sudo apt -y update
        sudo apt -y install docker-ce
        sudo groupadd docker
        sudo usermod -aG docker "$USER"
  sudo systemctl enable docker
  sudo systemctl start docker
fi
```

**Comment by littlejeem** [comment]
>Could you provide the output of:
>```php -v```

the output of ```php -v``` is:
```bash
PHP 7.0.33-0ubuntu0.16.04.6 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0ubuntu0.16.04.6, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by littlejeem** [comment]
I've not played with dockers yet and would rather not on this machine. Ill try to resolve the php issue so I can run natively......

**Comment by littlejeem** [comment]
> > First of all I just want to say that this looks like a first class job, I'm so grateful that people like you take the time to write stuff like this.......he says bowing down in a Waynes World type "we're not worthy" salute........
> 
> thank you, comments like these are very motivating! It is an honor.
> 
> > If i run m4b-tool --version I receive a PHP Parse Error as follows.
> 
> Well, since this is an error, that points to a library path of Symfony (`vendor/symfony/console/Output/Output.php`) and not to an `m4b-tool` specific file, i guess this has to do something with your PHP Version. `m4b-tool` might be incompatible with PHP 7.0...
> 
> Could you provide the output of:
> 
> `php -v`
> 
> As you are on linux you might try to overcome this issue without having to install another PHP version by switching to the `docker` image, see https://github.com/sandreas/m4b-tool#user-content-best-practices for usage details.
> 
> I for myself prefer the community edition, to install `docker` you could use:
> 
> ```
> dpkg -s "docker-ce" &> /dev/null 
> if [ "$?" -ne "0" ]; then 
>         curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
>         sudo add-apt-repository \
>            "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
>            $(lsb_release -cs) \
>            stable"
>         
>         sudo apt -y purge docker docker-engine docker.io
>         sudo apt -y update
>         sudo apt -y install docker-ce
>         sudo groupadd docker
>         sudo usermod -aG docker "$USER"
>   sudo systemctl enable docker
>   sudo systemctl start docker
> fi
> ```

Thanks for the pointers that this was PHP related. I upgraded to php 7.3 and re-ran ```m4b-tool --version```, output gave no errors and provided the following output:

```bash
m4b-tool v.0.4.0

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  chapters  Adds chapters to m4b file
  help      Displays help for a command
  list      Lists commands
  merge     Merges a set of files to one single file
  split     Splits an m4b file into parts
```
This can be marked as solved, I thank you for your time, i'm off to play......

**Comment by sandreas** [comment]
> I've not played with dockers yet and would rather not on this machine. Ill try to resolve the php issue so I can run natively......

I understand this - `docker` is a big topic, i just wanted to point out, that docker has many advantages over native install, but it is not a must have :-)

As you tried and failed with PHP 7.0 I would like to keep this open, since the documentation suggests installing PHP >= 7.0, which is no longer correct.

I'll fix this in the next days.

**Comment by littlejeem** [comment]
Hi
I've spun up an Ubuntu VM running 18.04 and run through your instructions. 18.04 installs php 7.2.
The output of ```m4b-tool --version``` is:

```bash
m4b-tool v.0.4.0
```
I'll play with this and see if all works as expected

**Comment by sandreas** [comment]
Ok, fixed. Just a Hint: Update `m4b-tool` to v.0.4.2 - it is the latest release. Also a documentation issue that i fixed with this commit ;) Sorry...
