### ISSUE TITLE
Memory leak during large Batch audiobook conversion

### ISSUE THREAD

**Issue by jeromeof** [sandreas/m4b-tool#44]
I have about 100 audiobooks organised in folders structures and am using the batch conversion to create .m4b files but it runs out of memory during this process.

[mp3float @ 0x5645ffd84100] overread, skip -6 enddists: -4 -4
[mp3float @ 0x5645ffd84100] overread, skip -7 enddists: -6 -6
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:41:14.05 bitrate=N/A speed=79.5x    
video:1kB audio:213098kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 67108872 bytes) in phar:///usr/local/bin/m4b-tool/src/library/M4bTool/StringUtilities/Runes.php on line 26
an error occured, that has not been caught:
Array
(
    [type] => 1
    [message] => Allowed memory size of 134217728 bytes exhausted (tried to allocate 67108872 bytes)
    [file] => phar:///usr/local/bin/m4b-tool/src/library/M4bTool/StringUtilities/Runes.php
    [line] => 26
)

**Comment by sandreas** [comment]
I just wanted to ask, if this one was fixed with the commit in the other bug?! Then i would close this issue.

**Comment by jeromeof** [comment]
I think it was - but I currently switched to a bash script will loops around all the folders and calls your process multiple times - I wanted to sort of guarantee that I could leave it running for days and not worry about any memory issues and this script (based on one you have in this repo) seemed like the easiest way do go. But I did monitor memory briefly the other evening and it seems like it stayed low so I think you fixed the problem
