### ISSUE TITLE
Merge fails with chapters shorter than 1 second

### ISSUE THREAD

**Issue by mafrye** [sandreas/m4b-tool#47]
# Summary
I'm running m4b-tool built from source in Ubuntu on Windows Subsystem for Linux.  When trying to merge a book of mp3 files, the conversion of mp3 chapter files to m4b is successful, but the recombination step fails if an m4b file is less than 1 second long.  I believe this is caused by the length metadata tag storing down to seconds rather than hundredths or thousandths of a second.  I was able to work around this issue by manually adding a second of silence to the m4b file using audacity (ffmpeg could probably do this too), but I expect there's a more elegant way to do this.

# Details
The < 1 sec. length causes `$this->meta->inspectExactDuration($file)` (src/library/M4bTool/Chapter/ChapterHandler.php, line 98) to return NULL to $duration, which causes `            $chapter = new Chapter($lastStart, $duration, $chapterName);` (src/library/M4bTool/Chapter/ChapterHandler.php, line 99) to throw an error.

# Solution
I'm unsure where the inspectExactDuration function comes from, but it could probably be modified such that it handles valid "zero-length" files or calculates length rather than pulling it from metadata.

# Trace

```
Argument 2 passed to M4bTool\Audio\Chapter::__construct() must be an instance of Sandreas\Time\TimeUnit, null given, called in phar:///home/<user>/new/m4b-tool/dist/m4b-tool.phar/src/library/M4bTool/Chapter/ChapterHandler.php on line 99
trace: #0 phar:///home/<user>/new/m4b-tool/dist/m4b-tool.phar/src/library/M4bTool/Chapter/ChapterHandler.php(99): M4bTool\Audio\Chapter->__construct(Object(Sandreas\Time\TimeUnit), NULL, 'MAPS')
#1 phar:///home/<user>/new/m4b-tool/dist/m4b-tool.phar/src/library/M4bTool/Command/MergeCommand.php(445): M4bTool\Chapter\ChapterHandler->buildChaptersFromFiles(Array, Array)
#2 phar:///home/<user>/new/m4b-tool/dist/m4b-tool.phar/src/library/M4bTool/Command/MergeCommand.php(371): M4bTool\Command\MergeCommand->processInputFiles()
#3 phar:///home/<user>/new/m4b-tool/dist/m4b-tool.phar/src/library/M4bTool/Command/MergeCommand.php(165): M4bTool\Command\MergeCommand->processFiles(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar:///home/<user>/new/m4b-tool/dist/m4b-tool.phar/vendor/symfony/console/Command/Command.php(255): M4bTool\Command\MergeCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///home/<user>/new/m4b-tool/dist/m4b-tool.phar/vendor/symfony/console/Application.php(915): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///home/<user>/new/m4b-tool/dist/m4b-tool.phar/vendor/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(M4bTool\Command\MergeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///home/<user>/new/m4b-tool/dist/m4b-tool.phar/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///home/<user>/new/m4b-tool/dist/m4b-tool.phar/bin/m4b-tool.php(33): Symfony\Component\Console\Application->run()
#9 /home/<user>/new/m4b-tool/dist/m4b-tool.phar(10): require('phar:///home/<user>...')
#10 {main}
```

**Comment by sandreas** [comment]
Ok, thank you for the detailed description. 

Here is a possibly fixed build (but a shot in the dark) - should work. 

[m4b-tool.tar.gz](https://github.com/sandreas/m4b-tool/files/3597132/m4b-tool.tar.gz)

If its not fixed, I'll take a closer look at it, in the meantime it would be great if you could provide:
- the full command you are running (e.g. `m4b-tool merge data/audiobook --output-file=merged.m4b`
- A sample `mp3` file with < 1s length (shouldn't be too big)

**Comment by mafrye** [comment]
That totally fixed it!  The command I was using was `./m4b-tool.phar -vvv --jobs=6 merge The\ Wheel\ of\ Time/01\ -\ The\ Eye\ of\ the\ World/ --output-file m4b/Robert\ Jordan/The\ Wheel\ of\ Time/01\ -\ The\ Eye\ of\ the\ World.m4b`.

[Here's the problem file.](https://github.com/sandreas/m4b-tool/files/3597316/02.-.Maps.txt) (mp3 renamed to txt so I can upload it)

**Comment by sandreas** [comment]
Great, then I know for sure whats the problem. Thanks for reporting, I'll commit the fix as soon as i've written a test for this case.
