### ISSUE TITLE
Conversion fails if output file is not specified

### ISSUE THREAD

**Issue by ryandesign** [sandreas/m4b-tool#49]
Hello,

I'm trying to use m4b-tool for the first time and I'm encountering a few problems. I'm on macOS High Sierra and I've installed m4b-tool 0.4.2 using a MacPorts Portfile I just wrote. (I'll submit that Portfile into the official MacPorts repository once I'm sure m4b-tool is working.)

I have a folder of AIFF files (/private/tmp/m4b-test). The files don't have any tag metadata. In that folder, I run:

```
$ m4b-tool merge --include-extensions=aiff .
```

The error is:

```
extracting cover to ./cover.jpg failed
could not convert /private/tmp/m4b-test/1.aiff to -tmpfiles/1-1-finished.m4b
```

If I specify `--output-file test.m4b` then I can get past that error (and on to another one, for which I'll file a separate issue).

**Comment by sandreas** [comment]
I think this should be fixed in the latest release - but I'll double check before closing this issue...

**Comment by sandreas** [comment]
Fixed in latest sourcecode, performs a check, that `--output-file` is a required parameter for `merge`. Thanks for reporting.
