### ISSUE TITLE
Conversion fails if chapters.txt file does not exist

### ISSUE THREAD

**Issue by ryandesign** [sandreas/m4b-tool#50]
Hello,

On macOS High Sierra, using m4b-tool 0.4.2 installed using MacPorts, in a folder of AIFF files with no tag metadata, I run:

```
$ m4b-tool merge --include-extensions=aiff --output-file=test.m4b .
```

The error I get is:

```
extracting cover to ./cover.jpg failed
Argument 2 passed to M4bTool\Audio\Chapter::__construct() must be an instance of Sandreas\Time\TimeUnit, null given, called in phar:///opt/local/bin/m4b-tool/src/library/M4bTool/Chapter/ChapterHandler.php on line 95
```

If I create an empty file called chapters.txt in the same directory, then m4b-tool succeeds.

**Comment by sandreas** [comment]
I think this should be fixed in the latest release - but I'll double check before closing this issue...

**Comment by sandreas** [comment]
Had to do with chapters, but it seems that it was the filename generation of `<audiofile>.chapters.txt` - should be fixed in the latest code. I'll prepare a `latest-release` in the next days.
