### ISSUE TITLE
Unable to build docker image

### ISSUE THREAD

**Issue by jasonblewis** [sandreas/m4b-tool#53]
Hi,
On debian 9, I'm unable to build the docker image:
```
---- INSTALL BUILD DEPENDENCIES ----
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
```

**Comment by sandreas** [comment]
Thanks for reporting. Seems that this might be a temporary error.

> temporary error (try again later)

I'm pretty sure, this is a NOT problem of the Dockerfile in `m4b-tool` but I'll take a look in the next days :-)

**Comment by sandreas** [comment]
I tried with debian 9, everything is working fine. Are you still experiencing this issue?

**Comment by jasonblewis** [comment]
Closing as there seems to be something wrong with docker on my machine. Sorry for the false report.

**Comment by sandreas** [comment]
Nevermind, thanks for clearing this up :-)
