### ISSUE TITLE
Not detecting chapters?

### ISSUE THREAD

**Issue by stkb** [sandreas/m4b-tool#6]
Hi! Thanks for making this.

Sorry if I missed something, but is m4b-tool supposed to read chapters from the .m4b file when doing a split? I get an error when trying to split a file, that it's expecting a chapters.txt, but I expected it to extract that information from the file:

```
$ m4b-tool split book.m4b
Your ffmpeg version cannot produce top quality aac using encoder aac instead of libfdk_aac
export chapter list of book.m4b

In SplitCommand.php line 69:

  split command assumes that file .\book.chapters.txt exists and is readable

split [-d|--debug] [--debug-filename [DEBUG-FILENAME]] [-f|--force] [--no-cache] [--audio-format [AUDIO-FORMAT]] [--audio-channels [AUDIO-CHANNELS]] [--audio-bitrate [AUDIO-BITRATE]] [--audio-samplerate [AUDIO-SAMPLERATE]] [--audio-codec [AUDIO-CODEC]] [--adjust-for-ipod] [--name [NAME]] [--album [ALBUM]] [--artist [ARTIST]] [--genre [GENRE]] [--writer [WRITER]] [--albumartist [ALBUMARTIST]] [--year [YEAR]] [--cover [COVER]] [--skip-cover] [--use-existing-chapters-file] [--] <input>
```

The chapters in the file are already correct (`ffprobe -i book.m4b -show_chapters` shows them)

**Comment by sandreas** [comment]
m4b-tool splitting command needs `ffmpeg` AND `mp4chaps` to be installed (mp4chaps is part of `mp4v2`- see readme.md for details)

When splitting an m4b-file by chapter, following steps are performed:

- extract chapter information from `book.m4b` (mp4chaps -x book.m4b), which produces `book.chapters.txt` in the same directory
- parse chapter information from book.chapters.txt (extract start, end and title of each chapter)
- use ffmpeg to extract each chapter in the book.m4b and write files and metadata into `book_splitted`directory


- Could you please check, if `mp4chaps` command is available on your command line?
- If not, install mp4v2 and it should work
- If so, could you please provide information about your system? (OS, PHP-Version, etc.)

**Comment by stkb** [comment]
Thanks, that was it.

I was putting together a [scoop](https://github.com/lukesampson/scoop#readme) package for m4b-tool (I'm on Windows) and I thought I'd first just try putting `libmp4v2` and the `.exe's` in the same dir as m4b-tool to see if that worked.

Making sure `mp4chaps.exe` was on my PATH fixed it.
