### ISSUE TITLE
split creates each file larger than the last

### ISSUE THREAD

**Issue by gazpachoking** [sandreas/m4b-tool#61]
Not exactly sure what is happening here. It seems as though the file size and length of each successive file created by the `split` command includes the whole book from the beginning. Each chapter file is larger than the last. When I listen to them, they seem to have the right audio though, so I'm not exactly sure why that is. In this screen shot you can see the file sizes (of an in progress split command) the length of each file as reported by VLC, and the commands I used to transform a monolithic mp3 first into a chapterized m4b, then split again into chapter files as mp3. (the first file visible in VLC is the chapterized m4b created by merge command, where everything seems correct)

![image](https://user-images.githubusercontent.com/187133/69468518-78048000-0d5a-11ea-9195-ad3d28e01fe5.png)

**Comment by gazpachoking** [comment]
I'm using the 2019-11-20 pre-release from a docker container btw.

**Comment by sandreas** [comment]
Interesting... i did not notice that but I'm on it.
