### ISSUE TITLE
Homebrew setup if only using lossless split and merge

### ISSUE THREAD

**Issue by gennaios** [sandreas/m4b-tool#66]
Hello,

Because of the required pinned taps, sometimes homebrew is picky when updating, requiring manually uninstalling, reinstalling, or updating, requirements, e.g., I cannot run simply `brew update` without additional required steps. In the case when I am using merely lossless merge and split, is there a simpler setup such that homebrew would auto-update nicely? If not yet, perhaps you'd consider it. If needed, with warnings if one tries a convert and it cannot be done at the highest quality.

**Comment by sandreas** [comment]
> In the case when I am using merely lossless merge and split, is there a simpler setup such that homebrew would auto-update nicely?

Currently i don't see a possibility to improve this - or at least with my little `brew` experience. Unfortunately the required `ffmpeg` AND `mp4v2` are custom versions, that have to be compiled manually. The instructions for `brew` to install `m4b-tool` have been updated recently, where `tap-pin` is no longer required / supported.  Does this solve your issue?

> If not yet, perhaps you'd consider it.
If you know a better way to `brew` `m4b-tool`, it would be great if you could provide more information about this. I'm not aware of any way but I'm no expert.

> If needed, with warnings if one tries a convert and it cannot be done at the highest quality.
I integrated a warning in the latest code: `Your ffmpeg version does not support libfdk_aac for best audio quality` (only if `ffmpeg` does not support it).


I personally use the docker image for my setup on MacOS - it is much easier to keep it up to date and all it requires is an `alias`.

**Comment by gennaios** [comment]
> Currently i don't see a possibility to improve this - or at least with my little `brew` experience. Unfortunately the required `ffmpeg` AND `mp4v2` are custom versions, that have to be compiled manually. The instructions for `brew` to install `m4b-tool` have been updated recently, where `tap-pin` is no longer required / supported. Does this solve your issue?

I had just uninstalled and reinstalled with the new instructions. I'll see if it auto-updates without need for intervention with the next update.

btw, the Stick to defaults instructions need updating: `homebrew-ffmpeg/ffmpeg/ffmpeg`. It may be possible that one can merely `brew install sandreas/tap/m4b-tool` and it'll install the dependencies if one is using defaults.

Question remains: with defaults, is that good enough for lossless splits and merges, since that is the only thing I use? If yes, maybe a note in the README.

> If you know a better way to `brew` `m4b-tool`, it would be great if you could provide more information about this. I'm not aware of any way but I'm no expert.

I'll later test and see if I can find more info.

> I personally use the docker image for my setup on MacOS - it is much easier to keep it up to date and all it requires is an `alias`.

Since I use macOS as my main OS and update brew regularly, I'd like to if possible have less needed intervention. Will look at it more when I have a chance. Thank you for the help.

**Comment by sandreas** [comment]
> Question remains: with defaults, is that good enough for lossless splits and merges, since that is the only thing I use?

Mmh, i might have misunderstood you. The word *lossless* is a bit unclear. Sure there is a possibility to perform *lossless* merges by providing `--no-conversion` but i think that splits can only be done *lossless*, if you specify the output format being equal to the input file and `ffmpeg` decides to transcode instead of re-encode. There is no such thing as `--no-conversion` for split at the moment.

If *lossless* means *best possible audio quality with lib_fdkaac*, I confirm that the `brew` instructions will result in `ffmpeg` using this *non free* encoder. To check that, you could run the following shell command:
```
ffmpeg -hide_banner -codecs 2>&1 | grep libfdk > /dev/null && echo "libfdk is available for best audio quality"
```

Another option would be to use the [latest Pre-Release](https://github.com/sandreas/m4b-tool/releases/tag/latest) with support of `--audio-profile=aac_lc`. This would result in using `fdkaac` instead of `ffmpeg` - also providing libfdk. 

BUT: I did not run any *objective* tests regarding audio quality and comparing the output of different encoders. Relying on statements of the authors of `ffmpeg`, the audio quality of `ffmpeg`s default encoder is pretty decent, but even better with `libfdk_aac`. 

My personal tests resulted in the following:
- I hardly noticed a difference between `ffmpeg` without and with `libfdk_aac` on 64kbps
- `fdkaac` and the `--audio-profile=aac_he` or `--audio-profile=aac_he_v2` produced a far lower quality than using `ffmpeg` with `libfdk_aac` on 32kbps
- `fdkaac` and `--audio-profile=aac_lc` produced a file that sounded petty much the same as `ffmpeg` with `libfdk_aac`

**Comment by gennaios** [comment]
> Mmh, i might have misunderstood you. The word _lossless_ is a bit unclear. Sure there is a possibility to perform _lossless_ merges by providing `--no-conversion` but i think that splits can only be done _lossless_, if you specify the output format being equal to the input file and `ffmpeg` decides to transcode instead of re-encode. There is no such thing as `--no-conversion` for split at the moment.

Indeed, I could have been more clear. Generally, it seems that those in audio and image circles refer to lossless as truly meaning such, e.g. FLAC and ALAC are lossless, PNG and TIFF can be, etc. One can endlessly convert between formats w/o losing quality. Yes I mean merges using `--no-conversion`. I assume that since no codec is needed, not having them in the compile would be ok.

I haven't used split yet. I tend to split with another app for my use with audiobooks, as sometimes sellers don't include all chapter markers, so I split with a GUI app. I then edit the metadata, and merge with m4b-tool. Such makes me think, for merges, unless one is specifying a codec and bitrate, why isn't it automatically `--no-conversion`? Maybe some limitation though that seems like a sensible default.

**Comment by sandreas** [comment]
> FLAC and ALAC are lossless
`m4b-tool` should support *FLAC* as well as *ALAC* and *PNG* for covers - *ALAC* should even work in `m4b` files on Apple devices.

> why isn't it automatically --no-conversion?
I found no possible way to *detect* current codec accurately to decide if a conversion is really required or not. Although the codec detection is doable, the bitrate detection is never accurate. So using `--no-conversion` by default would result in non-working / damaged output files in most cases. I already tried that pretty hard but with no success.

> I tend to split with another app for my use with audiobooks, as sometimes sellers don't include all chapter markers, so I split with a GUI app. I then edit the metadata, and merge with m4b-tool.

That sounds like a 2 step process, where 1 step might be enough, except the case that you need both, the split version and the merged version with metadata... If you only need the resulting file, it might be a lot easier as soon as `m4b-tool` v.0.5.0 is out, supporting

```
m4b-tool meta --import-all audiobook.m4b
```

where files like `description.txt` and further metadata formats in the same directory should be supported (e.g. `opf` files). But this is something i'm working on atm.

**Comment by gennaios** [comment]
> I found no possible way to _detect_ current codec accurately to decide if a conversion is really required or not. Although the codec detection is doable, the bitrate detection is never accurate. So using `--no-conversion` by default would result in non-working / damaged output files in most cases. I already tried that pretty hard but with no success.

I see. It may be possible that I asked this same question before. :)
 
> > I tend to split with another app for my use with audiobooks, as sometimes sellers don't include all chapter markers, so I split with a GUI app. I then edit the metadata, and merge with m4b-tool.
> 
> That sounds like a 2 step process, where 1 step might be enough, except the case that you need both, the split version and the merged version with metadata... If you only need the resulting file, it might be a lot easier as soon as `m4b-tool` v.0.5.0 is out …

My use of m4b-tool for merged chapterized m4b's began since until recently watchOS didn't support syncing of audiobooks, so I created podcasts out of them. I still use the separate split files elsewhere.

Thanks for the help. Feel free to close the issue.
