### ISSUE TITLE
Out of memory exception with Docker image

### ISSUE THREAD

**Issue by gubler** [sandreas/m4b-tool#68]
I have build the latest docker image and it is working _mostly_ well. I have a few books that it is running out of memory on when processing.

My command is:
```
docker run -it --rm -u $(id -u):$(id -g) -v $(pwd):/mnt m4b-tool merge AUDIOBOOK_DIRECTORY --jobs=4 --audio-bitrate=64k --mark-tracks --audio-format=mp3 --audio-codec=libmp3lame --output-file='book.mp3'
```

The error I receive is:

```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 68606456 bytes) in phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/AbstractCommand.php on line 308
an error occured, that has not been caught:
Array
(
    [type] => 1
    [message] => Allowed memory size of 134217728 bytes exhausted (tried to allocate 68606456 bytes)
    [file] => phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/AbstractCommand.php
    [line] => 308
)
```

I have plenty of memory to throw at this - but I'm not sure if there is a way for me to do so.

I am on macOS Catalina, using Docker for Mac. I have increased the RAM for the Docker for Mac VM to 4GB and received the same error, so I assume this is from how PHP in the docker image is configured.

**Comment by sandreas** [comment]
Issue #44 might be similar - it has been fixed in the [latest pre-release](https://github.com/sandreas/m4b-tool/releases/tag/latest)

For Install instructions, see https://github.com/sandreas/m4b-tool#dockerize-a-pre-release-or-an-older-release-version

It would be great if you could test this with the latest pre-release, if the issue has been fixed.

**Comment by gubler** [comment]
Tried this with the nightly build and I ran into the same error.

**Comment by sandreas** [comment]
> Tried this with the nightly build and I ran into the same error.

Ok, thank you very much for trying out. I'll try to reproduce the problem, in the meantime, may i ask you about the characteristics of your audio sources...?:

- How many source files are in the directory?
- What size are the files (min, max, average)?

Thank you, I'll tell you when i found out something.

**Comment by gubler** [comment]
The first directory in this tree listing worked. The second did not:

```
Permissions Size User  Date Modified Name
drwxr-xr-x@    - dev88  8 Jan 13:05  .
drwxr-xr-x     - dev88  4 Jan 16:26  ├── Graham-McNeill--Horus-Heresy-23--Angel-Exterminatus
.rw-r--r--@  16M dev88 29 Dec  2019  │  ├── 01 Book 1 Theogonies 1.mp3
.rw-r--r--@  42M dev88 29 Dec  2019  │  ├── 02 Chapter 01.mp3
.rw-r--r--@  37M dev88 29 Dec  2019  │  ├── 03 Chapter 02.mp3
.rw-r--r--@  32M dev88 29 Dec  2019  │  ├── 04 Chapter 03.mp3
.rw-r--r--@  35M dev88 29 Dec  2019  │  ├── 05 Chapter 04.mp3
.rw-r--r--@  39M dev88 29 Dec  2019  │  ├── 06 Chapter 05.mp3
.rw-r--r--@  37M dev88 29 Dec  2019  │  ├── 07 Chapter 06.mp3
.rw-r--r--@  33M dev88 29 Dec  2019  │  ├── 08 Chapter 07.mp3
.rw-r--r--@  46M dev88 29 Dec  2019  │  ├── 09 Chapter 08.mp3
.rw-r--r--@  17M dev88 29 Dec  2019  │  ├── 10 Book 2 Theogonies 2.mp3
.rw-r--r--@  36M dev88 29 Dec  2019  │  ├── 11 Chapter 09.mp3
.rw-r--r--@  41M dev88 29 Dec  2019  │  ├── 12 Chapter 10.mp3
.rw-r--r--@  46M dev88 29 Dec  2019  │  ├── 13 Chapter 11.mp3
.rw-r--r--@  37M dev88 29 Dec  2019  │  ├── 14 Chapter 12.mp3
.rw-r--r--@  31M dev88 29 Dec  2019  │  ├── 15 Chapter 13.mp3
.rw-r--r--@  31M dev88 29 Dec  2019  │  ├── 16 Chapter 14.mp3
.rw-r--r--@  33M dev88 29 Dec  2019  │  ├── 17 Chapter 15.mp3
.rw-r--r--@  35M dev88 29 Dec  2019  │  ├── 18 Chapter 16.mp3
.rw-r--r--@  41M dev88 29 Dec  2019  │  ├── 19 Chapter 17.mp3
.rw-r--r--@  15M dev88 29 Dec  2019  │  ├── 20 Book 3 Theogonies 3.mp3
.rw-r--r--@  39M dev88 29 Dec  2019  │  ├── 21 Chapter 18.mp3
.rw-r--r--@  37M dev88 29 Dec  2019  │  ├── 22 Chapter 19.mp3
.rw-r--r--@  37M dev88 29 Dec  2019  │  ├── 23 Chapter 20.mp3
.rw-r--r--@  39M dev88 29 Dec  2019  │  ├── 24 Chapter 21.mp3
.rw-r--r--@  30M dev88 29 Dec  2019  │  ├── 25 Chapter 22.mp3
.rw-r--r--@  35M dev88 29 Dec  2019  │  ├── 26 Chapter 23.mp3
.rw-r--r--@  36M dev88 29 Dec  2019  │  ├── 27 Chapter 24.mp3
.rw-r--r--@  30M dev88 29 Dec  2019  │  ├── 28 Chapter 25.mp3
.rw-r--r--@  34M dev88 29 Dec  2019  │  ├── 29 Chapter 26.mp3
.rw-r--r--@  28M dev88 29 Dec  2019  │  ├── 30 Chapter 27.mp3
.rw-r--r--@ 8.8M dev88 29 Dec  2019  │  ├── 31 Theogonies 4.mp3
.rw-r--r--@ 123k dev88  4 Jan 16:26  │  └── cover.jpg
drwxr-xr-x     - dev88  5 Jan  8:08  ├── Graham-McNeill--Horus-Heresy-33--War-Without-End
.rw-r--r--@  94M dev88  5 Jan  7:48  │  ├── 01 The Divine Adoratrice.mp3
.rw-r--r--@  42M dev88  5 Jan  7:46  │  ├── 02 Howl of the Hearthworld.mp3
.rw-r--r--@  16M dev88  5 Jan  7:46  │  ├── 03 Lord of the Red Sands.mp3
.rw-r--r--@  45M dev88  5 Jan  7:47  │  ├── 04 Artefacts.mp3
.rw-r--r--@ 100M dev88  5 Jan  7:48  │  ├── 05 Hands of the Emperor.mp3
.rw-r--r--@  18M dev88  5 Jan  7:46  │  ├── 06 The Phoenician.mp3
.rw-r--r--@  80M dev88  5 Jan  7:46  │  ├── 07 Sermon of Exodus.mp3
.rw-r--r--@  50M dev88  5 Jan  7:48  │  ├── 08 By The Lion's Command.mp3
.rw-r--r--@  79M dev88  5 Jan  7:47  │  ├── 09 The Harrowing.mp3
.rw-r--r--@  56M dev88  5 Jan  7:47  │  ├── 10 All That Remains.mp3
.rw-r--r--@ 115M dev88  5 Jan  7:48  │  ├── 11 Gunsight.mp3
.rw-r--r--@  94M dev88  5 Jan  7:48  │  ├── 12 Allegiance.mp3
.rw-r--r--@  65M dev88  5 Jan  7:48  │  ├── 13 Daemonology.mp3
.rw-r--r--@  14M dev88  5 Jan  7:46  │  ├── 14 Black Oculus.mp3
.rw-r--r--@  48M dev88  5 Jan  7:46  │  ├── 15 Virtues of the Sons.mp3
.rw-r--r--@  82M dev88  5 Jan  7:48  │  ├── 16 The Laurel of Defiance.mp3
.rw-r--r--@  65M dev88  5 Jan  7:48  │  ├── 17 A Safe and Shadowed Place.mp3
.rw-r--r--@  49M dev88  5 Jan  7:46  │  ├── 18 Imperfect.mp3
.rw-r--r--@  63M dev88  5 Jan  7:48  │  ├── 19 Chirurgeon.mp3
.rw-r--r--@ 112M dev88  5 Jan  7:47  │  ├── 20 Twisted.mp3
.rw-r--r--@ 103M dev88  5 Jan  7:48  │  ├── 21 Wolf Mother.mp3
.rw-r--r--@ 126k dev88  5 Jan  7:27  │  └── cover.jpg
.rw-r--r--@ 1.4k dev88  6 Jan  6:42  └── processor.php
```

**Comment by sandreas** [comment]
Ok, I think I might have an idea whats wrong... the lines, that cause the memory problem are:

```
        $process = $this->ffmpeg($command, $message);
// this is the line...
        $metaDataOutput = $process->getOutput() . PHP_EOL . $process->getErrorOutput();
```

This means, that the `ffmpeg` output of existing metadata (or maybe an error message) might be so huge, that the php memory limit of 128MB is not enough to handle the `ffmpeg` output. It also might be a garbage collector issue, which is not freeing enough memory, that the problem raises only after analyzing a more than one file.

A quick fix might be to just throw more memory at the problem (I think i will change the docker image to use 512MB as PHP memory limit by default), but i also would like to track this down to prevent memory leaks or misbehaviour in `m4b-tool`.

I'll get back to you as soon as I know more.

**Comment by gubler** [comment]
I have tried it with both 512M and 1G and I'm still getting the out of memory error.

This is what the `tmp` directory looks like when the out of memory error occurs:

```
Size  Name
 31M  01-01 The Divine Adoratrice-finished.mp3
 14M  02-02 Howl of the Hearthworld-finished.mp3
5.5M  03-03 Lord of the Red Sands-finished.mp3
 15M  04-04 Artefacts-finished.mp3
 33M  05-05 Hands of the Emperor-finished.mp3
6.3M  06-06 The Phoenician-finished.mp3
 26M  07-07 Sermon of Exodus-finished.mp3
 16M  08-08 By The Lion's Command-finished.mp3
 26M  09-09 The Harrowing-finished.mp3
 18M  10-10 All That Remains-finished.mp3
 38M  11-11 Gunsight-finished.mp3
 31M  12-12 Allegiance-finished.mp3
 21M  13-13 Daemonology-finished.mp3
4.6M  14-14 Black Oculus-finished.mp3
 16M  15-15 Virtues of the Sons-finished.mp3
 27M  16-16 The Laurel of Defiance-finished.mp3
 21M  17-17 A Safe and Shadowed Place-finished.mp3
 16M  18-18 Imperfect-finished.mp3
 21M  19-19 Chirurgeon-finished.mp3
 37M  20-20 Twisted-finished.mp3
 34M  21-21 Wolf Mother-finished.mp3
466M  tmp_m.mp3
```

If you want, I can share the mp3s I am working with so you can test on your system.

**Comment by sandreas** [comment]
> I have tried it with both 512M and 1G and I'm still getting the out of memory error.

Maybe i misunderstood you. You wrote:

>  I have increased the RAM for the Docker for Mac VM to 4GB and received the same error, so I assume this is from how PHP in the docker image is configured.

The Docker-RAM has nothing to do with the PHP config. PHP is configured by `memory_limit = 128M` in `/etc/php7/php.ini` within the docker image, by default this is configured to `128M`.

Did you mean, that you changed the `php.ini` or just increased the amount of RAM available to Docker for MAC?  If not, I recently changed the `Dockerfile` of `m4b-tool` to use `512MB`. Perhaps you are successful with the latest `Dockerfile`.

> If you want, I can share the mp3s I am working with so you can test on your system.

This would be great - I've sent you an email, please check your SPAM folder, if you did not receive one :-)

**Comment by gubler** [comment]
Clarification:

- Originally I tried increasing the RAM of the Docker for Mac VM from 2G to 4G, but that did not work (because the Out of Memory is from PHP's 128M limit).
- This time, I tried increasing the `memory_limit` value in the `php.ini` config to both 512M (using your update from today) and then increasing it again to 1G when the 512M failed.

I will follow up with you over email about the files.

**Comment by sandreas** [comment]
Ok, got the files but till now i had no luck with reproducing the issue (i tried really hard!). I'll prepare a "debug"-Version of `m4b-tool` for your system, so that we might track this down on the system where the problem is definetely reproducable... I'll get back to you as soon as I got something new.

**Comment by sandreas** [comment]
Ok, latest pre-release is updated. You could try it with this one - but be careful and backup your data. To reproduce further issues (if not fixed), please:
- Use the `--debug` flag, that creates a log file and send me the logfile (be sure to remove personal data from it)
- Provide the full command that you executed (`m4b-tool merge ....`)

**Comment by gubler** [comment]
Still getting the `PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 536870920 bytes)` error. I have attached the log file.

Command: 

`docker run -it --rm -u $(id -u):$(id -g) -v "$(pwd)":/mnt m4b-tool merge Graham-McNeill--Horus-Heresy-33--War-Without-End --jobs=4 --audio-bitrate=64k --mark-tracks --audio-format=mp3 --audio-codec=libmp3lame --output-file='book.mp3' --debug`

[m4b-tool.log.zip](https://github.com/sandreas/m4b-tool/files/4213832/m4b-tool.log.zip)

**Comment by sandreas** [comment]
Thank you. Well, one thing is strange. The latest `pre-release` does not support `--mark-tracks` and cannot be started with this option. So either you did not update to the latest pre-release or you did not provide the exact command line you executed. 

The logs were pretty helpful, so there seems to be something wrong with the stream:

```
Application provided invalid, non monotonically increasing dts to muxer in stream 0
```
This message is flooding the output, so this is the reason, why the memory limit is exceeded. I added a paramter to suppress all unnecessary output.

Be sure to check out the latest pre-release.

**Comment by gubler** [comment]
Sorry for the long delay - its been crazy here.

I really appreciate all the work you have been putting in on this issue.

### Latest Attempt

1. I deleted my existing docker image.
2. Made sure to check out latest HEAD (Feb 20 according to `git log`)
3. Rebuilt the docker image from scratch

The command I used, copied direct from my zsh history:

`docker run -it --rm -u $(id -u):$(id -g) -v "$(pwd)":/mnt m4b-tool merge Graham-McNeill--Horus-Heresy-33--War-Without-End --jobs=4 --audio-bitrate=64k --mark-tracks --audio-format=mp3 --audio-codec=libmp3lame --output-file='book.mp3' --debug`

And ran into the same error. Here is the [log.zip](https://github.com/sandreas/m4b-tool/files/4269494/log.zip)

There are still a bunch of same error:

```
Application provided invalid, non monotonically increasing dts to muxer in stream 0
```

There is also this error that isn't in the log file:

```
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 268435464 bytes) in phar:///usr/local/bin/m4b-tool/src/library/M4bTool/StringUtilities/Runes.php on line 26
```

I don't know if there is something weird with my computer (not sure how that would matter since I am using the docker image, but I am a novice when it comes to docker) or I just have some weird mp3 files.

Or if I'm doing something completely wrong :(

**Comment by sandreas** [comment]
I'm sure it is not your fault - my instructions could be better, too. I'm trying to help you out, you already have helped to improve `m4b-tool`, which I really appreciate. 

So here are some detailed instructions to get the latest build (most important step is the :

```
# 1. clone m4b-tool repository
git clone https://github.com/sandreas/m4b-tool.git

# 2. change directory
cd m4b-tool

# 3. Replace the "latest" link in the dockerfile with the "pre-release" version
sed -i.bak "s/https:\/\/github.com\/sandreas\/m4b-tool\/releases\/latest\/download\/m4b-tool.tar.gz/https:\/\/github.com\/sandreas\/m4b-tool\/files\/4215734\/m4b-tool.tar.gz/g" ./Dockerfile

# 4. Check that the link has been replaced
diff Dockerfile Dockerfile.bak

# 5. build docker image with no cache - this will take a while
docker build --no-cache . -t m4b-tool

# 6. create an alias for m4b-tool running docker 
alias m4b-tool='docker run -it --rm -u $(id -u):$(id -g) -v "$(pwd)":/mnt m4b-tool'

# 7. testing the command
m4b-tool --version
```

**Comment by gubler** [comment]
`--mark-tracks` gave me the expected error and the it looks like the test book built successfully!

Gonna test a few more books and make sure everything is still solid and follow up afterwards - but for now this looks resolved :)

**Comment by gubler** [comment]
Everything seems to be good with the pre-release version. Closing this issue.

Thank you again for all the help :)

**Comment by sandreas** [comment]
Glad to hear that. Thank you for providing such useful information and your efforts to reproduce the bug :-) Have a nice day.
