### ISSUE TITLE
chapters --merge-similar fails due to php permission error

### ISSUE THREAD

**Issue by totallyGreg** [sandreas/m4b-tool#69]
I had this issue initial on OS X installed with brew.  I decided to try the docker container and it failed with the exact same error.

Changing the permissions (chmod 777 all files) did not solve the issue as it fails with the same error.  
`
❯ m4b-tool chapters --merge-similar --first-chapter-offset 6000 --last-chapter-offset 8000 -m 5de63394-9aca-47c2-84c8-a0c4a93b012b "fry.m4b"
PHP Warning:  file_put_contents(/fry.chapters.txt): failed to open stream: Permission denied in phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/ChaptersCommand.php on line 302
an error occured, that has not been caught:
Array
(
    [type] => 2
    [message] => file_put_contents(/fry.chapters.txt): failed to open stream: Permission denied
    [file] => phar:///usr/local/bin/m4b-tool/src/library/M4bTool/Command/ChaptersCommand.php
    [line] => 302
)
`

**Comment by sandreas** [comment]
Thanks for reporting, I'll check this in the next days.

**Comment by sandreas** [comment]
Ok, i think i got it. I will try to build a pre-release as soon as possible, so that you can test the improvements

**Comment by totallyGreg** [comment]
Cool thanks, I'll look for the pre-release and let you know how it works.

**Comment by sandreas** [comment]
Ok, latest pre-release is updated. You could try it with this one - but be careful and backup your data.

**Comment by totallyGreg** [comment]
Unfortunately this does not seem to be working.  I rebuilt the docker image and it ran without any errors, but also with out any chapter information.  
The correct chapter information does show up in the debug logs however.  

❯ m4b-tool --version
m4b-tool latest-18-g81d2ea1
❯ m4b-tool chapters --debug --logfile=Fry.debug.log --merge-similar -m c95b2567-f609-4cfa-83d4-80d23a60f817 Fry.m4b
❯ mp4chaps -l Fry.m4b
File "Fry.m4b" does not contain chapters of type QuickTime and Nero
❯ ls -l Fry.chapters.txt
-rw-r--r--  1 totally  staff  0 Feb 19 15:50 Fry.chapters.txt

As a side note.  m4b-tool merge, seems to combine the 3 files into a single m4b successfully but it stripped out out of the chapter information that was present prior to merging.

**Comment by sandreas** [comment]
Ok, then I have to take a look again... sorry and thank you for testing.

**Comment by sandreas** [comment]
So, i tried everything with the latest pre-release and it did work in all cases... 
Would you mind trying a last time with the `--no-cache` parameter and telling me, if it is working? If not, could you provide the debug log?

**Comment by totallyGreg** [comment]
[Fry.debug.log](https://github.com/sandreas/m4b-tool/files/4977841/Fry.debug.log)

Given three m4b files with matching chapter files in Fry directory.  The m4b files each contain the correct chapter data which is where the chapters files were extracted from.  
```
alias m4b-tool
m4b-tool='docker run -it --rm -u $(id -u):$(id -g) -v "$(pwd)":/mnt m4b-tool'
m4b-tool latest-33-g535d379
m4b-tool merge --no-cache --debug --logfile=Fry.debug.log --jobs=1 --no-conversion "Fry/" --output-file=Fry.m4b
```

Reasults in a correct single file, but Chapters from file 2 and 3 have the same time offsets as their individual files.  Thus three chapters all start at 00:00:00.000 and nothing is longer than 11 hours. If I add the total time from file 1 to the file 2 chapters they all spot on.  Same for adding file 1 and 2 total time to file 3 chapters.

**Comment by sandreas** [comment]
I think I got it (sorry for the little delay ;-) 
Problem was, that files with multiple chapters did not regard the offset of the first file. Should work with the next pre-release.
