### ISSUE TITLE
Adding no-conversion switch for splitting files

### ISSUE THREAD

**Issue by daniel-jozsef** [sandreas/m4b-tool#70]
I really need the ability to cut m4b books into mp4 chapter files with no encoding (`-ac copy` in ffmpeg).

Ffmpeg supports splitting audio streams without re-encoding. I took the ffmpeg command run by m4b-tool, and added `--acodec copy` to it, and it ran in a fraction of the time, and output a smaller file size:

```
ffmpeg -hide_banner -i "book.m4b" -vn -f mp4 -ss 00:00:00.000 -t 00:43:19.135 -acodec copy -map a -y "chapter1.mp4"
```

The only drawback is that the cuts won't be as precise, so split chapters will overlap by a few seconds. For me, this is a small price to pay, I'd rather not transcode something and get marginaly worse audio quality in exchange for 10% larger file size.

So I see no reason not to have no-conversion for split too. If someone can point out which source files need to be modified, I'd be glad to do the change myself and open a pull request, as this is a make-or-break feature for me, honestly.

**Comment by sandreas** [comment]
I think this is already fixed in the latest [pre-release](https://github.com/sandreas/m4b-tool/releases/tag/latest)... Please read instructions carefully, this is not a stable release.

**Comment by daniel-jozsef** [comment]
Thanks, nice! :)
