### ISSUE TITLE
merge producing output m4b doubled in length and size from source created from ffmpeg -concat

### ISSUE THREAD

**Issue by raisindetre** [sandreas/m4b-tool#73]
I have a use-case where I have an audiobook made-up of several mp3s, each containing multiple chapters. I wanted to create a chapter list with distinct chapters so used the following ffmpeg command to join the files into a single MP3:

`ls *.mp3 | sed -e "s/\(.*\)/file '\1'/" | ffmpeg -protocol_whitelist 'file,pipe' -f concat -safe 0 -i - -c copy output.mp3`

I am using my own ffmpeg scripts to detect silences in the joined file and build a chapters.txt file of the form:

> 00:00:33.012 Introduction
> 00:25:09.790 Part One
> 00:25:15.800 Ch1: The nature of things
> 

...
I place this file and the input file in a data directory and run the following m4b-tool merge command to generate an m4b:
` m4b-tool merge -v  --audio-bitrate=64k --audio-samplerate=44100 --audio-channels=1  data --output-file=data/output.m4b`

When the command runs, it indicates its processing two files:
`preparing conversion with 1 simultaneous job, please wait...
   0 remaining /    2 total, preparing next task |`

The created file is twice the file size and duration of the original input. Playing it, the chapter markers are out of sync and the audio is repeated.

I have tried stripping metadata from the source file but this doesn't make any difference:
`ffmpeg -i data/output.m4b -map_metadata -1 -c:v copy -c:a copy data/output_clean.m4b 
` 
Here is mediainfo output for the original mp3 and generated m4b:

**Source mp3 File**
`General
Complete name                            : data/output.mp3
Format                                   : MPEG Audio
File size                                : 273 MiB
Duration                                 : 9 h 56 min
Overall bit rate mode                    : Constant
Overall bit rate                         : 64.0 kb/s
Writing library                          : LAMEUUULAME3.91

Audio
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Format settings                          : Joint stereo / MS Stereo
Duration                                 : 9 h 56 min
Bit rate mode                            : Constant
Bit rate                                 : 64.0 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 kHz
Frame rate                               : 38.281 FPS (1152 SPF)
Compression mode                         : Lossy
Stream size                              : 273 MiB (100%)
Writing library                          : LAMEUUULAME3.91`
 
**Generated m4b file**
`General
Complete name                            : data/output_from_clean.m4b
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/mp41)
File size                                : 573 MiB
Duration                                 : 19 h 53 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 67.1 kb/s
ContentType                              : Audiobook
Tagged date                              : UTC 2020-02-29 06:22:09
Writing application                      : Lavf58.20.100 / m4b-tool

Audio
ID                                       : 1
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 19 h 53 min
Bit rate mode                            : Variable
Bit rate                                 : 66.2 kb/s
Maximum bit rate                         : 109 kb/s
Channel(s)                               : 1 channel
Channel layout                           : C
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 561 MiB (98%)
Default                                  : Yes
Alternate group                          : 1
Menus                                    : 2

Menu #1
00:00:00.000                             : 1
09:56:44.868                             : 2

Menu #2
ID                                       : 2
Codec ID                                 : text
Duration                                 : 19 h 53 min
Encoded date                             : UTC 2020-02-29 06:22:09
Tagged date                              : UTC 2020-02-29 06:22:09
Bit rate mode                            : CBR
Menu For                                 : 1
Duration_FirstFrame                      : -268
00:00:00.000                             : 1
09:56:44.868                             : 2
`
You can see the resulting file has generated two menus, the second showing the doubled duration which I assume are symptomatic of the problem? How do I avoid this?

**Comment by sandreas** [comment]
Did you use the latest pre-release? I think this might already be fixed.

**Comment by raisindetre** [comment]
Ah - ok. No I'm using 0.4.2 stable.

**Comment by sandreas** [comment]
So i updated the instructions how to install the pre-release. If you find the time to check, if it is fixed (or not), I'll close the ticket or take a closer look.

**Comment by sandreas** [comment]
Ok, since i could not reproduce this, for now the issue will be closed. If you find the time to test the newest pre-release and still getting the same issue, feel free to reopen it.

**Comment by chudsaviet** [comment]
I'm seeing the same bug. Version is 0.4.2 .

**Comment by sandreas** [comment]
Try latest pre-release...  I'm planning a stable in the next weeks...
