### ISSUE TITLE
Memory leak during conversion

### ISSUE THREAD

**Issue by rubylaser** [sandreas/m4b-tool#76]
I'm experiencing a similar issue to [this previously solved issue](https://github.com/sandreas/m4b-tool/issues/44). I have compiled the latest version on Docker following your directions.  
`m4b-tool v.0.4.2`

I have successfully converted a bunch of my audiobooks, but I have found one that I cannot get to convert. Here is the command that I'm using (this is on a dual socket E5-2670v2 machine).
`m4b-tool merge -vv --jobs=8 --name="Children of Dune" --series="Dune Saga" --series-part="3" --writer="Frank Herbert" --artist="Frank Herbert" --album="Children of Dune" --output-file="Frank Herbert - Dune Saga - Children of Dune - Book 3/Children of Dune.m4b" "Frank Herbert - Children of Dune"
`
Here is the error that I'm receiving.
`
determine highest available audio codec
reading metadata and streaminfo for file /mnt/Frank Herbert - Children of Dune/Dune Chronicles III_ Children of Dune.mp3
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+++++++++
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 67108872 bytes) in phar:///usr/local/bin/m4b-tool/src/library/M4bTool/StringUtilities/Runes.php on line 26
an error occured, that has not been caught:
Array
(
    [type] => 1
    [message] => Allowed memory size of 134217728 bytes exhausted (tried to allocate 67108872 bytes)
    [file] => phar:///usr/local/bin/m4b-tool/src/library/M4bTool/StringUtilities/Runes.php
    [line] => 26
)
`
I'd appreciate any insight that you might offer.  And, thanks for this awesome tool! It's worked great other than this one snag.

**Comment by sandreas** [comment]
As i see this closed i think that you might have tried the latest release and it is fixed... if you still need help feel free to reopen the ticket.

> And, thanks for this awesome tool! 
Glad too hear you like it :-)
