### ISSUE TITLE
"cover.jpg" not being used when batch-merging

### ISSUE THREAD

**Issue by nemosmithasf** [sandreas/m4b-tool#79]
Here is the context: https://we.tl/t-Vdc5wLRiWr

As you can see, the "cover.jpg" is not embedded when you run the merge function.

**Comment by sandreas** [comment]
Thanks for reporting and the context. I'll take a look in the next days.

**Comment by sandreas** [comment]
Quick Update:
It seems, that not the cover is the problem, but `ffmpeg` is producing bogus `m4b` temporary files out of your source `mp3` files before the merge. With the latest pre-release i get an error:

```
tmp_The Art of Thinking Clearly 06-16-45-842.m4b": invalid atom size, extends outside parent atom - skipping to end of "" "" 1229206276 vs 69932346
```

That does not necessarily mean there is something wrong with your files for `ffmpeg`, but it means something is wrong when converting the `mp3` to `m4b` - maybe the conversion parameters for `ffmpeg` are wrong, maybe it is a bug in `ffmpeg` -  but i have to look at this in detail, which will take some time.

**Comment by nemosmithasf** [comment]
Thanks for the good work, I look forward to seeing what you find out

**Comment by sandreas** [comment]
Ok, should be fixed. Next pre-release is coming soon.
