### ISSUE TITLE
How to split an audio book into chapters without re-encoding?

### ISSUE THREAD

**Issue by derniwi** [sandreas/m4b-tool#81]
Is it possible to splt an audio book containing chapter information into single files without re-encoding?

I tried using the parameter
--ffmpeg-param -acodec:copy
but this leads to empty files.

Best regards
Nils

**Comment by sandreas** [comment]
Did you try `--no-conversion` with the latest pre-release?

**Comment by derniwi** [comment]
No. How can I get the pre-release using a Mac and Homebrew?

**Comment by sandreas** [comment]
Just replace the binary with the latest version:
```
# download latest prerelease
cd /tmp && wget -c https://github.com/sandreas/m4b-tool/files/4215734/m4b-tool.tar.gz && tar xzf m4b-tool.tar.gz && rm m4b-tool.tar.gz && chmod +x m4b-tool.phar && 
sudo mv m4b-tool.phar $(which m4b-tool)

# check version
m4b-tool --version
# m4b-tool latest-19-gdb42c19
```

**Comment by derniwi** [comment]
Yes, it works with the pre-release. Thank you.
