### ISSUE TITLE
m4b-tool does not embed covers

### ISSUE THREAD

**Issue by glgoose** [sandreas/m4b-tool#82]
If I run m4b-tool with a folder containing a cover.png, it does not embed the cover and shows an error message.

OS: macOS Catalina Version 10.15.4
Command: `m4b-tool merge audio.mp4 -o output.m4b`
Error: Exporting cover to audio.art[0].jpg failed

Attached files: cover.png

**Comment by sandreas** [comment]
Thanks for reporting. I confirm that `png` covers are not fully supported yet. Should be an easy fix, I'll try to fix it in the next days.

**Comment by sandreas** [comment]
Only `png` covers were not embedded - should be fixed now. Latest pre-release has been updated.
