### ISSUE TITLE
Can't Find Files on Windows 10

### ISSUE THREAD

**Issue by sebclark** [sandreas/m4b-tool#83]
OS: Windows 10:
PHP: Tried 7.1 and 7.4
m4b-tools: tried 0.4.1 and 0.4.2

I have managed to make this work on windows with fdkaac after a lot of messing around. One thing that I noticed is that for windows the merge input folder doesn't work if you leave the trailing slash on the directory structure:

"cannot read metadata, file does not exist"

The solution I found (not sure if it is a simple missing slash from the code) is to remove the trailing slash from the input folder:
m4b-tool merge "C:\m4b-tool\input\Test" --output-file="c:\m4b-tool\input\Test\merged.m4b"

Edited Sorry: This isn't a code problem, but rather command prompt is treating "c:\m4b-tool\input\Test\" as escaping the quote. You can remove the slash, or escape it with another slash.

**Comment by sebclark** [comment]
Windows - batch processing problem. The directory slashes are causing a problem in Windows - the output directory can either have no slash, forward slash or backslash - giving different outputs:

m4b-tool merge --audio-bitrate=64k --audio-samplerate=22050 --max-chapter-length=300,900 --include-extensions=mp3,m4b,m4a --jobs=8 "input" --batch-pattern="input\%a\%n" --output-file="output\"
PHP Warning:  mkdir(): No such file or directory in phar://C:/PHP7/phars/m4b-tool.phar/src/library/M4bTool/Command/MergeCommand.php on line 748

Warning: mkdir(): No such file or directory in phar://C:/PHP7/phars/m4b-tool.phar/src/library/M4bTool/Command/MergeCommand.php on line 748
Could not create temp directory output"/Author\Title\Title-tmpfiles</>

m4b-tool merge --audio-bitrate=64k --audio-samplerate=22050 --max-chapter-length=300,900 --include-extensions=mp3,m4b,m4a --jobs=8 "input" --batch-pattern="input\%a\%n" --output-file="output/"
could not merge to output/Author\Title\Title-tmpfiles\/tmp_Title.m4b

Also the output directory must go as the final parameter or else Windows tries to create the directory name including everything after --output-file="

**Comment by sandreas** [comment]
Thank you for reporting this. Let me first ask you some questions:

- Did you try the latest pre-release? (I think many issues have been fixed here and it is already stable enough for all day usage in most cases)
- Did you try using Slashes instead of Backslashes? (e.g. C:/my-folder/ - as long as you are not using UNC-Paths like `\\my-server\share\folder` this should also work)

Anyways using slashes is just a workaround and what you found could indeed be an issue on windows. I'll take a look at it in the near future.

**Comment by sebclark** [comment]
I have tried forward slashes and forward slashes with full path - both result in the same issue.

**Comment by sandreas** [comment]
Great thank you. Then i try to fix this in the next pre-release.
