### ISSUE TITLE
Batch Path Output Issue - Windows

### ISSUE THREAD

**Issue by sebclark** [sandreas/m4b-tool#84]
Windows - batch processing problem. The output directory slashes are causing a problem in Windows:

c:\m4b-tool>m4b-tool merge --audio-bitrate=64k --audio-samplerate=22050 --max-chapter-length=300,900 --include-extensions=mp3,m4b,m4a --jobs=8 "input" --batch-pattern="input\%a\%n" --output-file="output\\"
could not merge to output/Author\Title\Title-tmpfiles\tmp_Title.m4b

c:\m4b-tool>m4b-tool merge --audio-bitrate=64k --audio-samplerate=22050 --max-chapter-length=300,900 --include-extensions=mp3,m4b,m4a --jobs=8 "input" --batch-pattern="input\%a\%n" --output-file="output"
could not merge to output/Author\Title\Title-tmpfiles\tmp_Title.m4b

-vvv log

ffmpeg -nostats -loglevel panic -hide_banner -f concat -safe 0 -vn -i "output/Author\Title\Title-tmpfiles\tmp_Title.m4b.listing.txt" -max_muxing_queue_size 9999 -c copy -f mp4 "output/Author\Title\Title-tmpfiles\tmp_\Title.m4b"

**Comment by sandreas** [comment]
This one is pretty similar to #83 - same instructions here:

- Try latest pre-release
- Try using slashes instead of backslashes

I'll take a look in the near future.

**Comment by sandreas** [comment]
Should be fixed in the latest code, pre-release will follow. Make sure to use `/` in `--batch-pattern`

**Comment by sebclark** [comment]
Thanks for the fast response and the great effort with this tool - it is excellent! Can i compile this latest code into a phar myself? or I should wait for the pre-release?

**Comment by sandreas** [comment]
I uploaded it today :-)
