### ISSUE TITLE
Build error (sandreas/mp4v2) server offline HTTP 500

### ISSUE THREAD

**Issue by WoodpeckerBaby** [sandreas/m4b-tool#91]
https://github.com/sandreas/mp4v2/archive/master.zip

This repo is offline, install via docker fails.

`---- COMPILE SANDREAS MP4V2 (for sort-title, sort-album and sort-author) ----
--2020-07-13 06:18:56--  https://github.com/sandreas/mp4v2/archive/master.zip
Resolving github.com... 13.114.40.48
Connecting to github.com|13.114.40.48|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/sandreas/mp4v2/zip/master [following]
--2020-07-13 06:18:56--  https://codeload.github.com/sandreas/mp4v2/zip/master
Resolving codeload.github.com... 13.112.159.149
Connecting to codeload.github.com|13.112.159.149|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2020-07-13 06:18:56 ERROR 500: Internal Server Error.`

**Comment by sandreas** [comment]
Github was down... if the issue is still happening, please feel free to reopen :-)

https://www.githubstatus.com/incidents/j597fw8kv04c
