### ISSUE TITLE
Website Documentation Incorrect/Out of Date

### ISSUE THREAD

**Issue by anthonyattard** [sandreas/m4b-tool#94]
The documentation at http://m4b-tool.fynder.de/ for the docker section is out of date from what is listed in the readme on GitHub and does not work. 

The line that is incorrectly listed as
`# build docker image - this will take a while
docker build docker -t m4b-tool`
while the working command in the readme is
`docker build . -t m4b-tool`

**Comment by sandreas** [comment]
fixed :-) Thanks for reporting.
