### ISSUE TITLE
Add narrator and Musicbrainz ID to batch tags

### ISSUE THREAD

**Issue by eduo** [sandreas/m4b-tool#96]
Add narrator and Musicbrainz ID to batch tags

Currently there isn't a way to add musicbrainz ID in batch mode. It would be nice to have this and narrator as batch tags.

**Comment by sandreas** [comment]
Hey, thanks for reporting. I'm not sure, i understood this correctly... Which field do you think should `narrator` and `musicbrainz-id` be stored in?

**Comment by sandreas** [comment]
Since there is no feedback for a pretty long time, I'll close this for now. Feel free to reopen the issue, if you like.
