### ISSUE TITLE
Hardware acceleration

### ISSUE THREAD

**Issue by mweitzel2005** [sandreas/m4b-tool#97]
Is there a way to tap into `ffmpeg`'s hardware acceleration support using `m4b-tool`?

**Comment by sandreas** [comment]
There is an option to append `ffmpeg` parameters, that are not supported by default - all the values are appended to the ffmpeg call itself without any check or modification, so according to https://trac.ffmpeg.org/wiki/HWAccelIntro you could try to do something like

```
m4b-tool .... --ffmpeg-param="-hwaccel" --ffmpeg-param="dxva2"
```

which would result in:

```
ffmpeg -hwaccell dxva2
```

Or use any other valid combination of parameters for ffmpeg...

Is that what you meant?

**Comment by mweitzel2005** [comment]
Yes, thank you. That's exactly what I meant! Must have missed it in the docs. Thanks again!

**Comment by sandreas** [comment]
Great... I'll close this for now.
