### ISSUE TITLE
Chapter Name

### ISSUE THREAD

**Issue by SirSquirr3l** [sandreas/m4b-tool#98]
Hi there,

the Track Titles in my MP3-Files are named Chapter 01, Chapter 02, Chapter 03 and so on.

The Chapters in in the .m4b-File are named like this:

00:00:00.000 1
00:09:39.941 2
00:19:19.072 3
00:28:59.588 4
00:38:35.794 5
00:48:23.023 6

Using option --use-filenames-as-chapters has the same result. 

If I rename the Titles to 01 - Somewhere, 02 - Anywhere - everything works fine. 

Any suggestions?!

Thanks

**Comment by sandreas** [comment]
In case you closed the issue by accident:

```
      --no-chapter-reindexing                    Do not perform any reindexing for index-only chapter names (by default m4b-tool will try to detect index-only chapters like Chapter 1, Chapter 2 and reindex it with its numbers only)
```
