### ISSUE TITLE
"Could not detect length for file"

### ISSUE THREAD

**Issue by Ciantic** [sandreas/m4b-tool#99]
The M4B Tool seems to assume that length is in seconds, see [this code line](https://github.com/sandreas/m4b-tool/blob/6902f1eda28f1a89c193b6cef7f33c7b77d68c66/src/library/Executables/Mp4info.php#L41).

However I have latest mp4info and it seems to be giving length in *milliseconds*, thus I get error like this:

```
Could not detect length for file 01-finished.m4b, output 'File:
  major brand:      isom
  minor version:    200
  compatible brand: isom
  compatible brand: iso2
  compatible brand: mp41
  fast start:       yes

Movie:
  duration:   19012 ms
  time scale: 1000
  fragments:  no

Found 1 Tracks
Track 1:
  flags:        3 ENABLED IN-MOVIE
  id:           1
  type:         Audio
  duration: 19012 ms
...
```

**Comment by sandreas** [comment]
Thanks for the detailed report... Fixed in the last commit. I will add this to the next `pre-release`.
